---
- name: Pre-Configure Workstation
  hosts: k8s_cluster
  become: true
  gather_facts: true
  roles:
    - role: eanble-iscsi
    - role: longhorn-disks
    - role: init-wol
    # Sysbox CE deb + (Ubuntu 25.04+) fusermount3 AppArmor local allow for sysboxfs
    - role: install-sysbox-runc
