// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface AiProviderSettings {
    /**
     * AWS Bedrock settings. Valid only for `type = "bedrock"` or `type = "anthropic"`.
     */
    bedrock?: outputs.AiProviderSettingsBedrock;
}

export interface AiProviderSettingsBedrock {
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * AWS secret access key for Bedrock.
     */
    accessKeySecretWo?: string;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * AWS access key ID for Bedrock. See [Coder's Amazon Bedrock provider docs](https://coder.com/docs/ai-coder/ai-gateway/providers#amazon-bedrock).
     */
    accessKeyWo?: string;
    /**
     * Version for Bedrock write-only credentials. Bump this value to send, rotate, or clear credentials.
     */
    credentialsWoVersion?: number;
    /**
     * STS external ID the server generates and sends on the AssumeRole call when <span pulumi-lang-nodejs="`roleArn`" pulumi-lang-dotnet="`RoleArn`" pulumi-lang-go="`roleArn`" pulumi-lang-python="`role_arn`" pulumi-lang-yaml="`roleArn`" pulumi-lang-java="`roleArn`" pulumi-lang-hcl="`role_arn`">`roleArn`</span> is set. Reference it in the assumed role's trust policy `sts:ExternalId` condition. Null until <span pulumi-lang-nodejs="`roleArn`" pulumi-lang-dotnet="`RoleArn`" pulumi-lang-go="`roleArn`" pulumi-lang-python="`role_arn`" pulumi-lang-yaml="`roleArn`" pulumi-lang-java="`roleArn`" pulumi-lang-hcl="`role_arn`">`roleArn`</span> is first configured; stable afterwards. Requires Coder v2.36.0 or later.
     */
    externalId: string;
    /**
     * Primary Bedrock model identifier.
     */
    model: string;
    /**
     * AWS region for Bedrock. If omitted, derived from the canonical Bedrock <span pulumi-lang-nodejs="`baseUrl`" pulumi-lang-dotnet="`BaseUrl`" pulumi-lang-go="`baseUrl`" pulumi-lang-python="`base_url`" pulumi-lang-yaml="`baseUrl`" pulumi-lang-java="`baseUrl`" pulumi-lang-hcl="`base_url`">`baseUrl`</span> attribute.
     */
    region: string;
    /**
     * ARN of an AWS IAM role to assume via STS before calling Bedrock. The base identity (the AWS SDK default credential chain or the static credentials) signs the AssumeRole call, and the temporary credentials sign Bedrock requests. Omit to call Bedrock with the base identity directly. Requires Coder v2.35.0 or later.
     */
    roleArn?: string;
    /**
     * Small/fast Bedrock model identifier used for background tasks.
     */
    smallFastModel: string;
}

export interface GetGroupMember {
    /**
     * Unix timestamp of when the member was created.
     */
    createdAt: number;
    email: string;
    id: string;
    /**
     * Unix timestamp of when the member was last seen.
     */
    lastSeenAt: number;
    /**
     * The login type of the member. Can be <span pulumi-lang-nodejs="`oidc`" pulumi-lang-dotnet="`Oidc`" pulumi-lang-go="`oidc`" pulumi-lang-python="`oidc`" pulumi-lang-yaml="`oidc`" pulumi-lang-java="`oidc`" pulumi-lang-hcl="`oidc`">`oidc`</span>, <span pulumi-lang-nodejs="`token`" pulumi-lang-dotnet="`Token`" pulumi-lang-go="`token`" pulumi-lang-python="`token`" pulumi-lang-yaml="`token`" pulumi-lang-java="`token`" pulumi-lang-hcl="`token`">`token`</span>, <span pulumi-lang-nodejs="`password`" pulumi-lang-dotnet="`Password`" pulumi-lang-go="`password`" pulumi-lang-python="`password`" pulumi-lang-yaml="`password`" pulumi-lang-java="`password`" pulumi-lang-hcl="`password`">`password`</span>, <span pulumi-lang-nodejs="`github`" pulumi-lang-dotnet="`Github`" pulumi-lang-go="`github`" pulumi-lang-python="`github`" pulumi-lang-yaml="`github`" pulumi-lang-java="`github`" pulumi-lang-hcl="`github`">`github`</span> or <span pulumi-lang-nodejs="`none`" pulumi-lang-dotnet="`None`" pulumi-lang-go="`none`" pulumi-lang-python="`none`" pulumi-lang-yaml="`none`" pulumi-lang-java="`none`" pulumi-lang-hcl="`none`">`none`</span>.
     */
    loginType: string;
    /**
     * The status of the member. Can be <span pulumi-lang-nodejs="`active`" pulumi-lang-dotnet="`Active`" pulumi-lang-go="`active`" pulumi-lang-python="`active`" pulumi-lang-yaml="`active`" pulumi-lang-java="`active`" pulumi-lang-hcl="`active`">`active`</span>, <span pulumi-lang-nodejs="`dormant`" pulumi-lang-dotnet="`Dormant`" pulumi-lang-go="`dormant`" pulumi-lang-python="`dormant`" pulumi-lang-yaml="`dormant`" pulumi-lang-java="`dormant`" pulumi-lang-hcl="`dormant`">`dormant`</span> or <span pulumi-lang-nodejs="`suspended`" pulumi-lang-dotnet="`Suspended`" pulumi-lang-go="`suspended`" pulumi-lang-python="`suspended`" pulumi-lang-yaml="`suspended`" pulumi-lang-java="`suspended`" pulumi-lang-hcl="`suspended`">`suspended`</span>.
     */
    status: string;
    username: string;
}

export interface GetTemplateAcl {
    groups: outputs.GetTemplateAclGroup[];
    users: outputs.GetTemplateAclUser[];
}

export interface GetTemplateAclGroup {
    id: string;
    role: string;
}

export interface GetTemplateAclUser {
    id: string;
    role: string;
}

export interface GetTemplateAutoStopRequirement {
    /**
     * List of days of the week on which restarts are required. Restarts happen within the user's quiet hours (in their configured timezone). If no days are specified, restarts are not required.
     */
    daysOfWeeks: string[];
    /**
     * Weeks is the number of weeks between required restarts. Weeks are synced across all workspaces (and Coder deployments) using modulo math on a hardcoded epoch week of January 2nd, 2023 (the first Monday of 2023). Values of 0 or 1 indicate weekly restarts. Values of 2 indicate fortnightly restarts, etc.
     */
    weeks: number;
}

export interface OrganizationGroupSync {
    /**
     * Controls whether groups will be created if they are missing.
     */
    autoCreateMissing?: boolean;
    /**
     * The claim field that specifies what groups a user should be in.
     */
    field?: string;
    /**
     * A map from OIDC group name to Coder group ID.
     */
    mapping?: {[key: string]: string[]};
    /**
     * A regular expression that will be used to filter the groups returned by the OIDC provider. Any group not matched will be ignored.
     */
    regexFilter?: string;
}

export interface OrganizationRoleSync {
    /**
     * The claim field that specifies what organization roles a user should be given.
     */
    field?: string;
    /**
     * A map from OIDC group name to Coder organization role.
     */
    mapping?: {[key: string]: string[]};
}

export interface TemplateAcl {
    groups: outputs.TemplateAclGroup[];
    users: outputs.TemplateAclUser[];
}

export interface TemplateAclGroup {
    id: string;
    role: string;
}

export interface TemplateAclUser {
    id: string;
    role: string;
}

export interface TemplateAutoStopRequirement {
    /**
     * List of days of the week on which restarts are required. Restarts happen within the user's quiet hours (in their configured timezone). If no days are specified, restarts are not required.
     */
    daysOfWeeks: string[];
    /**
     * Weeks is the number of weeks between required restarts. Weeks are synced across all workspaces (and Coder deployments) using modulo math on a hardcoded epoch week of January 2nd, 2023 (the first Monday of 2023). Values of 0 or 1 indicate weekly restarts. Values of 2 indicate fortnightly restarts, etc.
     */
    weeks: number;
}

export interface TemplateVersion {
    /**
     * Whether this version is the active version of the template. Only one version can be active at a time.
     */
    active: boolean;
    /**
     * A path to the directory to create the template version from. Changes in the directory contents will trigger the creation of a new template version.
     */
    directory: string;
    directoryHash: string;
    id: string;
    /**
     * A message describing the changes in this version of the template. Messages longer than 72 characters will be truncated.
     */
    message: string;
    /**
     * The name of the template version. Automatically generated if not provided. If provided, the name *must* change each time the directory contents, or the <span pulumi-lang-nodejs="`tfVars`" pulumi-lang-dotnet="`TfVars`" pulumi-lang-go="`tfVars`" pulumi-lang-python="`tf_vars`" pulumi-lang-yaml="`tfVars`" pulumi-lang-java="`tfVars`" pulumi-lang-hcl="`tf_vars`">`tfVars`</span> attribute are updated.
     */
    name: string;
    /**
     * Provisioner tags for the template version.
     */
    provisionerTags?: outputs.TemplateVersionProvisionerTag[];
    /**
     * Terraform variables for the template version.
     */
    tfVars?: outputs.TemplateVersionTfVar[];
}

export interface TemplateVersionProvisionerTag {
    name: string;
    value: string;
}

export interface TemplateVersionTfVar {
    name: string;
    value: string;
}

