// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Application extends pulumi.CustomResource {
    /**
     * Get an existing Application resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ApplicationState, opts?: pulumi.CustomResourceOptions): Application {
        return new Application(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'argocd:index/application:Application';

    /**
     * Returns true if the given object is an instance of Application.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Application {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Application.__pulumiType;
    }

    declare public readonly applicationId: pulumi.Output<string>;
    /**
     * Whether to applying cascading deletion when application is removed.
     */
    declare public readonly cascade: pulumi.Output<boolean | undefined>;
    /**
     * Standard Kubernetes object metadata. For more info see the [Kubernetes reference](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#metadata).
     */
    declare public readonly metadata: pulumi.Output<outputs.ApplicationMetadata>;
    /**
     * The application specification.
     */
    declare public readonly spec: pulumi.Output<outputs.ApplicationSpec>;
    /**
     * Status information for the application. **Note**: this is not guaranteed to be up to date immediately after creating/updating an application unless `wait=true`.
     */
    declare public /*out*/ readonly statuses: pulumi.Output<outputs.ApplicationStatus[]>;
    /**
     * Trigger sync immediately after create/update. Helps in case when a Sync window is defined. It is required that the sync window is defined with <span pulumi-lang-nodejs="`manualSync " pulumi-lang-dotnet="`ManualSync " pulumi-lang-go="`manualSync " pulumi-lang-python="`manual_sync " pulumi-lang-yaml="`manualSync " pulumi-lang-java="`manualSync " pulumi-lang-hcl="`manual_sync ">`manualSync </span>= true`.
     */
    declare public readonly sync: pulumi.Output<boolean | undefined>;
    declare public readonly timeouts: pulumi.Output<outputs.ApplicationTimeouts | undefined>;
    /**
     * Whether to validate the application spec before creating or updating the application.
     */
    declare public readonly validate: pulumi.Output<boolean | undefined>;
    /**
     * Upon application creation or update, wait for application health/sync status to be healthy/Synced, upon application deletion, wait for application to be removed, when set to true. Wait timeouts are controlled by Terraform Create, Update and Delete resource timeouts (all default to 5 minutes). **Note**: if ArgoCD decides not to sync an application (e.g. because the project to which the application belongs has a <span pulumi-lang-nodejs="`syncWindow`" pulumi-lang-dotnet="`SyncWindow`" pulumi-lang-go="`syncWindow`" pulumi-lang-python="`sync_window`" pulumi-lang-yaml="`syncWindow`" pulumi-lang-java="`syncWindow`" pulumi-lang-hcl="`sync_window`">`syncWindow`</span> applied) then you will experience an expected timeout event if `wait = true`.
     */
    declare public readonly wait: pulumi.Output<boolean | undefined>;

    /**
     * Create a Application resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ApplicationArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ApplicationArgs | ApplicationState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ApplicationState | undefined;
            resourceInputs["applicationId"] = state?.applicationId;
            resourceInputs["cascade"] = state?.cascade;
            resourceInputs["metadata"] = state?.metadata;
            resourceInputs["spec"] = state?.spec;
            resourceInputs["statuses"] = state?.statuses;
            resourceInputs["sync"] = state?.sync;
            resourceInputs["timeouts"] = state?.timeouts;
            resourceInputs["validate"] = state?.validate;
            resourceInputs["wait"] = state?.wait;
        } else {
            const args = argsOrState as ApplicationArgs | undefined;
            if (args?.metadata === undefined && !opts.urn) {
                throw new Error("Missing required property 'metadata'");
            }
            if (args?.spec === undefined && !opts.urn) {
                throw new Error("Missing required property 'spec'");
            }
            resourceInputs["applicationId"] = args?.applicationId;
            resourceInputs["cascade"] = args?.cascade;
            resourceInputs["metadata"] = args?.metadata;
            resourceInputs["spec"] = args?.spec;
            resourceInputs["sync"] = args?.sync;
            resourceInputs["timeouts"] = args?.timeouts;
            resourceInputs["validate"] = args?.validate;
            resourceInputs["wait"] = args?.wait;
            resourceInputs["statuses"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Application.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Application resources.
 */
export interface ApplicationState {
    applicationId?: pulumi.Input<string | undefined>;
    /**
     * Whether to applying cascading deletion when application is removed.
     */
    cascade?: pulumi.Input<boolean | undefined>;
    /**
     * Standard Kubernetes object metadata. For more info see the [Kubernetes reference](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#metadata).
     */
    metadata?: pulumi.Input<inputs.ApplicationMetadata | undefined>;
    /**
     * The application specification.
     */
    spec?: pulumi.Input<inputs.ApplicationSpec | undefined>;
    /**
     * Status information for the application. **Note**: this is not guaranteed to be up to date immediately after creating/updating an application unless `wait=true`.
     */
    statuses?: pulumi.Input<pulumi.Input<inputs.ApplicationStatus>[] | undefined>;
    /**
     * Trigger sync immediately after create/update. Helps in case when a Sync window is defined. It is required that the sync window is defined with <span pulumi-lang-nodejs="`manualSync " pulumi-lang-dotnet="`ManualSync " pulumi-lang-go="`manualSync " pulumi-lang-python="`manual_sync " pulumi-lang-yaml="`manualSync " pulumi-lang-java="`manualSync " pulumi-lang-hcl="`manual_sync ">`manualSync </span>= true`.
     */
    sync?: pulumi.Input<boolean | undefined>;
    timeouts?: pulumi.Input<inputs.ApplicationTimeouts | undefined>;
    /**
     * Whether to validate the application spec before creating or updating the application.
     */
    validate?: pulumi.Input<boolean | undefined>;
    /**
     * Upon application creation or update, wait for application health/sync status to be healthy/Synced, upon application deletion, wait for application to be removed, when set to true. Wait timeouts are controlled by Terraform Create, Update and Delete resource timeouts (all default to 5 minutes). **Note**: if ArgoCD decides not to sync an application (e.g. because the project to which the application belongs has a <span pulumi-lang-nodejs="`syncWindow`" pulumi-lang-dotnet="`SyncWindow`" pulumi-lang-go="`syncWindow`" pulumi-lang-python="`sync_window`" pulumi-lang-yaml="`syncWindow`" pulumi-lang-java="`syncWindow`" pulumi-lang-hcl="`sync_window`">`syncWindow`</span> applied) then you will experience an expected timeout event if `wait = true`.
     */
    wait?: pulumi.Input<boolean | undefined>;
}

/**
 * The set of arguments for constructing a Application resource.
 */
export interface ApplicationArgs {
    applicationId?: pulumi.Input<string | undefined>;
    /**
     * Whether to applying cascading deletion when application is removed.
     */
    cascade?: pulumi.Input<boolean | undefined>;
    /**
     * Standard Kubernetes object metadata. For more info see the [Kubernetes reference](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#metadata).
     */
    metadata: pulumi.Input<inputs.ApplicationMetadata>;
    /**
     * The application specification.
     */
    spec: pulumi.Input<inputs.ApplicationSpec>;
    /**
     * Trigger sync immediately after create/update. Helps in case when a Sync window is defined. It is required that the sync window is defined with <span pulumi-lang-nodejs="`manualSync " pulumi-lang-dotnet="`ManualSync " pulumi-lang-go="`manualSync " pulumi-lang-python="`manual_sync " pulumi-lang-yaml="`manualSync " pulumi-lang-java="`manualSync " pulumi-lang-hcl="`manual_sync ">`manualSync </span>= true`.
     */
    sync?: pulumi.Input<boolean | undefined>;
    timeouts?: pulumi.Input<inputs.ApplicationTimeouts | undefined>;
    /**
     * Whether to validate the application spec before creating or updating the application.
     */
    validate?: pulumi.Input<boolean | undefined>;
    /**
     * Upon application creation or update, wait for application health/sync status to be healthy/Synced, upon application deletion, wait for application to be removed, when set to true. Wait timeouts are controlled by Terraform Create, Update and Delete resource timeouts (all default to 5 minutes). **Note**: if ArgoCD decides not to sync an application (e.g. because the project to which the application belongs has a <span pulumi-lang-nodejs="`syncWindow`" pulumi-lang-dotnet="`SyncWindow`" pulumi-lang-go="`syncWindow`" pulumi-lang-python="`sync_window`" pulumi-lang-yaml="`syncWindow`" pulumi-lang-java="`syncWindow`" pulumi-lang-hcl="`sync_window`">`syncWindow`</span> applied) then you will experience an expected timeout event if `wait = true`.
     */
    wait?: pulumi.Input<boolean | undefined>;
}
