// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class ApplicationSet extends pulumi.CustomResource {
    /**
     * Get an existing ApplicationSet resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ApplicationSetState, opts?: pulumi.CustomResourceOptions): ApplicationSet {
        return new ApplicationSet(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'argocd:index/applicationSet:ApplicationSet';

    /**
     * Returns true if the given object is an instance of ApplicationSet.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ApplicationSet {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ApplicationSet.__pulumiType;
    }

    declare public readonly applicationSetId: pulumi.Output<string>;
    /**
     * Standard Kubernetes object metadata. For more info see the [Kubernetes reference](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#metadata).
     */
    declare public readonly metadata: pulumi.Output<outputs.ApplicationSetMetadata>;
    /**
     * ArgoCD application set resource spec.
     */
    declare public readonly spec: pulumi.Output<outputs.ApplicationSetSpec>;

    /**
     * Create a ApplicationSet resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ApplicationSetArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ApplicationSetArgs | ApplicationSetState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ApplicationSetState | undefined;
            resourceInputs["applicationSetId"] = state?.applicationSetId;
            resourceInputs["metadata"] = state?.metadata;
            resourceInputs["spec"] = state?.spec;
        } else {
            const args = argsOrState as ApplicationSetArgs | undefined;
            if (args?.metadata === undefined && !opts.urn) {
                throw new Error("Missing required property 'metadata'");
            }
            if (args?.spec === undefined && !opts.urn) {
                throw new Error("Missing required property 'spec'");
            }
            resourceInputs["applicationSetId"] = args?.applicationSetId;
            resourceInputs["metadata"] = args?.metadata;
            resourceInputs["spec"] = args?.spec;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ApplicationSet.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering ApplicationSet resources.
 */
export interface ApplicationSetState {
    applicationSetId?: pulumi.Input<string | undefined>;
    /**
     * Standard Kubernetes object metadata. For more info see the [Kubernetes reference](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#metadata).
     */
    metadata?: pulumi.Input<inputs.ApplicationSetMetadata | undefined>;
    /**
     * ArgoCD application set resource spec.
     */
    spec?: pulumi.Input<inputs.ApplicationSetSpec | undefined>;
}

/**
 * The set of arguments for constructing a ApplicationSet resource.
 */
export interface ApplicationSetArgs {
    applicationSetId?: pulumi.Input<string | undefined>;
    /**
     * Standard Kubernetes object metadata. For more info see the [Kubernetes reference](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#metadata).
     */
    metadata: pulumi.Input<inputs.ApplicationSetMetadata>;
    /**
     * ArgoCD application set resource spec.
     */
    spec: pulumi.Input<inputs.ApplicationSetSpec>;
}
