// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class GpgKey extends pulumi.CustomResource {
    /**
     * Get an existing GpgKey resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: GpgKeyState, opts?: pulumi.CustomResourceOptions): GpgKey {
        return new GpgKey(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'argocd:index/gpgKey:GpgKey';

    /**
     * Returns true if the given object is an instance of GpgKey.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is GpgKey {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === GpgKey.__pulumiType;
    }

    /**
     * Fingerprint is the fingerprint of the key
     */
    declare public /*out*/ readonly fingerprint: pulumi.Output<string>;
    /**
     * Owner holds the owner identification, e.g. a name and e-mail address
     */
    declare public /*out*/ readonly owner: pulumi.Output<string>;
    /**
     * Raw key data of the GPG key to create
     */
    declare public readonly publicKey: pulumi.Output<string>;
    /**
     * SubType holds the key's sub type (e.g. rsa4096)
     */
    declare public /*out*/ readonly subType: pulumi.Output<string>;
    /**
     * Trust holds the level of trust assigned to this key
     */
    declare public /*out*/ readonly trust: pulumi.Output<string>;

    /**
     * Create a GpgKey resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: GpgKeyArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: GpgKeyArgs | GpgKeyState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as GpgKeyState | undefined;
            resourceInputs["fingerprint"] = state?.fingerprint;
            resourceInputs["owner"] = state?.owner;
            resourceInputs["publicKey"] = state?.publicKey;
            resourceInputs["subType"] = state?.subType;
            resourceInputs["trust"] = state?.trust;
        } else {
            const args = argsOrState as GpgKeyArgs | undefined;
            if (args?.publicKey === undefined && !opts.urn) {
                throw new Error("Missing required property 'publicKey'");
            }
            resourceInputs["publicKey"] = args?.publicKey;
            resourceInputs["fingerprint"] = undefined /*out*/;
            resourceInputs["owner"] = undefined /*out*/;
            resourceInputs["subType"] = undefined /*out*/;
            resourceInputs["trust"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(GpgKey.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering GpgKey resources.
 */
export interface GpgKeyState {
    /**
     * Fingerprint is the fingerprint of the key
     */
    fingerprint?: pulumi.Input<string | undefined>;
    /**
     * Owner holds the owner identification, e.g. a name and e-mail address
     */
    owner?: pulumi.Input<string | undefined>;
    /**
     * Raw key data of the GPG key to create
     */
    publicKey?: pulumi.Input<string | undefined>;
    /**
     * SubType holds the key's sub type (e.g. rsa4096)
     */
    subType?: pulumi.Input<string | undefined>;
    /**
     * Trust holds the level of trust assigned to this key
     */
    trust?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a GpgKey resource.
 */
export interface GpgKeyArgs {
    /**
     * Raw key data of the GPG key to create
     */
    publicKey: pulumi.Input<string>;
}
