// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class RepositoryCredentials extends pulumi.CustomResource {
    /**
     * Get an existing RepositoryCredentials resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RepositoryCredentialsState, opts?: pulumi.CustomResourceOptions): RepositoryCredentials {
        return new RepositoryCredentials(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'argocd:index/repositoryCredentials:RepositoryCredentials';

    /**
     * Returns true if the given object is an instance of RepositoryCredentials.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RepositoryCredentials {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RepositoryCredentials.__pulumiType;
    }

    /**
     * Whether `helm-oci` support should be enabled for this repo. Can only be set to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span> when <span pulumi-lang-nodejs="`type`" pulumi-lang-dotnet="`Type`" pulumi-lang-go="`type`" pulumi-lang-python="`type`" pulumi-lang-yaml="`type`" pulumi-lang-java="`type`" pulumi-lang-hcl="`type`">`type`</span> is <span pulumi-lang-nodejs="`helm`" pulumi-lang-dotnet="`Helm`" pulumi-lang-go="`helm`" pulumi-lang-python="`helm`" pulumi-lang-yaml="`helm`" pulumi-lang-java="`helm`" pulumi-lang-hcl="`helm`">`helm`</span>.
     */
    declare public readonly enableOci: pulumi.Output<boolean>;
    /**
     * GitHub API URL for GitHub app authentication
     */
    declare public readonly githubappEnterpriseBaseUrl: pulumi.Output<string | undefined>;
    /**
     * GitHub App ID of the app used to access the repo for GitHub app authentication
     */
    declare public readonly githubappId: pulumi.Output<string | undefined>;
    /**
     * ID of the installed GitHub App for GitHub app authentication
     */
    declare public readonly githubappInstallationId: pulumi.Output<string | undefined>;
    /**
     * Private key data (PEM) for authentication via GitHub app
     */
    declare public readonly githubappPrivateKey: pulumi.Output<string | undefined>;
    /**
     * Password for authenticating at the repo server
     */
    declare public readonly password: pulumi.Output<string | undefined>;
    /**
     * Private key data for authenticating at the repo server using SSH (only Git repos)
     */
    declare public readonly sshPrivateKey: pulumi.Output<string | undefined>;
    /**
     * TLS client cert data for authenticating at the repo server
     */
    declare public readonly tlsClientCertData: pulumi.Output<string | undefined>;
    /**
     * TLS client cert key for authenticating at the repo server
     */
    declare public readonly tlsClientCertKey: pulumi.Output<string | undefined>;
    /**
     * Type of the repository credentials. Can be either <span pulumi-lang-nodejs="`git`" pulumi-lang-dotnet="`Git`" pulumi-lang-go="`git`" pulumi-lang-python="`git`" pulumi-lang-yaml="`git`" pulumi-lang-java="`git`" pulumi-lang-hcl="`git`">`git`</span>, <span pulumi-lang-nodejs="`oci`" pulumi-lang-dotnet="`Oci`" pulumi-lang-go="`oci`" pulumi-lang-python="`oci`" pulumi-lang-yaml="`oci`" pulumi-lang-java="`oci`" pulumi-lang-hcl="`oci`">`oci`</span> or <span pulumi-lang-nodejs="`helm`" pulumi-lang-dotnet="`Helm`" pulumi-lang-go="`helm`" pulumi-lang-python="`helm`" pulumi-lang-yaml="`helm`" pulumi-lang-java="`helm`" pulumi-lang-hcl="`helm`">`helm`</span>. <span pulumi-lang-nodejs="`git`" pulumi-lang-dotnet="`Git`" pulumi-lang-go="`git`" pulumi-lang-python="`git`" pulumi-lang-yaml="`git`" pulumi-lang-java="`git`" pulumi-lang-hcl="`git`">`git`</span> is assumed if empty or absent.
     */
    declare public readonly type: pulumi.Output<string>;
    /**
     * URL that these credentials match to
     */
    declare public readonly url: pulumi.Output<string>;
    /**
     * Whether `Azure-Workload-identity` should be enabled for this repository.
     */
    declare public readonly useAzureWorkloadIdentity: pulumi.Output<boolean>;
    /**
     * Username for authenticating at the repo server
     */
    declare public readonly username: pulumi.Output<string | undefined>;

    /**
     * Create a RepositoryCredentials resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RepositoryCredentialsArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RepositoryCredentialsArgs | RepositoryCredentialsState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as RepositoryCredentialsState | undefined;
            resourceInputs["enableOci"] = state?.enableOci;
            resourceInputs["githubappEnterpriseBaseUrl"] = state?.githubappEnterpriseBaseUrl;
            resourceInputs["githubappId"] = state?.githubappId;
            resourceInputs["githubappInstallationId"] = state?.githubappInstallationId;
            resourceInputs["githubappPrivateKey"] = state?.githubappPrivateKey;
            resourceInputs["password"] = state?.password;
            resourceInputs["sshPrivateKey"] = state?.sshPrivateKey;
            resourceInputs["tlsClientCertData"] = state?.tlsClientCertData;
            resourceInputs["tlsClientCertKey"] = state?.tlsClientCertKey;
            resourceInputs["type"] = state?.type;
            resourceInputs["url"] = state?.url;
            resourceInputs["useAzureWorkloadIdentity"] = state?.useAzureWorkloadIdentity;
            resourceInputs["username"] = state?.username;
        } else {
            const args = argsOrState as RepositoryCredentialsArgs | undefined;
            if (args?.url === undefined && !opts.urn) {
                throw new Error("Missing required property 'url'");
            }
            resourceInputs["enableOci"] = args?.enableOci;
            resourceInputs["githubappEnterpriseBaseUrl"] = args?.githubappEnterpriseBaseUrl;
            resourceInputs["githubappId"] = args?.githubappId;
            resourceInputs["githubappInstallationId"] = args?.githubappInstallationId;
            resourceInputs["githubappPrivateKey"] = args?.githubappPrivateKey ? pulumi.secret(args.githubappPrivateKey) : undefined;
            resourceInputs["password"] = args?.password ? pulumi.secret(args.password) : undefined;
            resourceInputs["sshPrivateKey"] = args?.sshPrivateKey ? pulumi.secret(args.sshPrivateKey) : undefined;
            resourceInputs["tlsClientCertData"] = args?.tlsClientCertData;
            resourceInputs["tlsClientCertKey"] = args?.tlsClientCertKey ? pulumi.secret(args.tlsClientCertKey) : undefined;
            resourceInputs["type"] = args?.type;
            resourceInputs["url"] = args?.url;
            resourceInputs["useAzureWorkloadIdentity"] = args?.useAzureWorkloadIdentity;
            resourceInputs["username"] = args?.username;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["githubappPrivateKey", "password", "sshPrivateKey", "tlsClientCertKey"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(RepositoryCredentials.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering RepositoryCredentials resources.
 */
export interface RepositoryCredentialsState {
    /**
     * Whether `helm-oci` support should be enabled for this repo. Can only be set to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span> when <span pulumi-lang-nodejs="`type`" pulumi-lang-dotnet="`Type`" pulumi-lang-go="`type`" pulumi-lang-python="`type`" pulumi-lang-yaml="`type`" pulumi-lang-java="`type`" pulumi-lang-hcl="`type`">`type`</span> is <span pulumi-lang-nodejs="`helm`" pulumi-lang-dotnet="`Helm`" pulumi-lang-go="`helm`" pulumi-lang-python="`helm`" pulumi-lang-yaml="`helm`" pulumi-lang-java="`helm`" pulumi-lang-hcl="`helm`">`helm`</span>.
     */
    enableOci?: pulumi.Input<boolean | undefined>;
    /**
     * GitHub API URL for GitHub app authentication
     */
    githubappEnterpriseBaseUrl?: pulumi.Input<string | undefined>;
    /**
     * GitHub App ID of the app used to access the repo for GitHub app authentication
     */
    githubappId?: pulumi.Input<string | undefined>;
    /**
     * ID of the installed GitHub App for GitHub app authentication
     */
    githubappInstallationId?: pulumi.Input<string | undefined>;
    /**
     * Private key data (PEM) for authentication via GitHub app
     */
    githubappPrivateKey?: pulumi.Input<string | undefined>;
    /**
     * Password for authenticating at the repo server
     */
    password?: pulumi.Input<string | undefined>;
    /**
     * Private key data for authenticating at the repo server using SSH (only Git repos)
     */
    sshPrivateKey?: pulumi.Input<string | undefined>;
    /**
     * TLS client cert data for authenticating at the repo server
     */
    tlsClientCertData?: pulumi.Input<string | undefined>;
    /**
     * TLS client cert key for authenticating at the repo server
     */
    tlsClientCertKey?: pulumi.Input<string | undefined>;
    /**
     * Type of the repository credentials. Can be either <span pulumi-lang-nodejs="`git`" pulumi-lang-dotnet="`Git`" pulumi-lang-go="`git`" pulumi-lang-python="`git`" pulumi-lang-yaml="`git`" pulumi-lang-java="`git`" pulumi-lang-hcl="`git`">`git`</span>, <span pulumi-lang-nodejs="`oci`" pulumi-lang-dotnet="`Oci`" pulumi-lang-go="`oci`" pulumi-lang-python="`oci`" pulumi-lang-yaml="`oci`" pulumi-lang-java="`oci`" pulumi-lang-hcl="`oci`">`oci`</span> or <span pulumi-lang-nodejs="`helm`" pulumi-lang-dotnet="`Helm`" pulumi-lang-go="`helm`" pulumi-lang-python="`helm`" pulumi-lang-yaml="`helm`" pulumi-lang-java="`helm`" pulumi-lang-hcl="`helm`">`helm`</span>. <span pulumi-lang-nodejs="`git`" pulumi-lang-dotnet="`Git`" pulumi-lang-go="`git`" pulumi-lang-python="`git`" pulumi-lang-yaml="`git`" pulumi-lang-java="`git`" pulumi-lang-hcl="`git`">`git`</span> is assumed if empty or absent.
     */
    type?: pulumi.Input<string | undefined>;
    /**
     * URL that these credentials match to
     */
    url?: pulumi.Input<string | undefined>;
    /**
     * Whether `Azure-Workload-identity` should be enabled for this repository.
     */
    useAzureWorkloadIdentity?: pulumi.Input<boolean | undefined>;
    /**
     * Username for authenticating at the repo server
     */
    username?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a RepositoryCredentials resource.
 */
export interface RepositoryCredentialsArgs {
    /**
     * Whether `helm-oci` support should be enabled for this repo. Can only be set to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span> when <span pulumi-lang-nodejs="`type`" pulumi-lang-dotnet="`Type`" pulumi-lang-go="`type`" pulumi-lang-python="`type`" pulumi-lang-yaml="`type`" pulumi-lang-java="`type`" pulumi-lang-hcl="`type`">`type`</span> is <span pulumi-lang-nodejs="`helm`" pulumi-lang-dotnet="`Helm`" pulumi-lang-go="`helm`" pulumi-lang-python="`helm`" pulumi-lang-yaml="`helm`" pulumi-lang-java="`helm`" pulumi-lang-hcl="`helm`">`helm`</span>.
     */
    enableOci?: pulumi.Input<boolean | undefined>;
    /**
     * GitHub API URL for GitHub app authentication
     */
    githubappEnterpriseBaseUrl?: pulumi.Input<string | undefined>;
    /**
     * GitHub App ID of the app used to access the repo for GitHub app authentication
     */
    githubappId?: pulumi.Input<string | undefined>;
    /**
     * ID of the installed GitHub App for GitHub app authentication
     */
    githubappInstallationId?: pulumi.Input<string | undefined>;
    /**
     * Private key data (PEM) for authentication via GitHub app
     */
    githubappPrivateKey?: pulumi.Input<string | undefined>;
    /**
     * Password for authenticating at the repo server
     */
    password?: pulumi.Input<string | undefined>;
    /**
     * Private key data for authenticating at the repo server using SSH (only Git repos)
     */
    sshPrivateKey?: pulumi.Input<string | undefined>;
    /**
     * TLS client cert data for authenticating at the repo server
     */
    tlsClientCertData?: pulumi.Input<string | undefined>;
    /**
     * TLS client cert key for authenticating at the repo server
     */
    tlsClientCertKey?: pulumi.Input<string | undefined>;
    /**
     * Type of the repository credentials. Can be either <span pulumi-lang-nodejs="`git`" pulumi-lang-dotnet="`Git`" pulumi-lang-go="`git`" pulumi-lang-python="`git`" pulumi-lang-yaml="`git`" pulumi-lang-java="`git`" pulumi-lang-hcl="`git`">`git`</span>, <span pulumi-lang-nodejs="`oci`" pulumi-lang-dotnet="`Oci`" pulumi-lang-go="`oci`" pulumi-lang-python="`oci`" pulumi-lang-yaml="`oci`" pulumi-lang-java="`oci`" pulumi-lang-hcl="`oci`">`oci`</span> or <span pulumi-lang-nodejs="`helm`" pulumi-lang-dotnet="`Helm`" pulumi-lang-go="`helm`" pulumi-lang-python="`helm`" pulumi-lang-yaml="`helm`" pulumi-lang-java="`helm`" pulumi-lang-hcl="`helm`">`helm`</span>. <span pulumi-lang-nodejs="`git`" pulumi-lang-dotnet="`Git`" pulumi-lang-go="`git`" pulumi-lang-python="`git`" pulumi-lang-yaml="`git`" pulumi-lang-java="`git`" pulumi-lang-hcl="`git`">`git`</span> is assumed if empty or absent.
     */
    type?: pulumi.Input<string | undefined>;
    /**
     * URL that these credentials match to
     */
    url: pulumi.Input<string>;
    /**
     * Whether `Azure-Workload-identity` should be enabled for this repository.
     */
    useAzureWorkloadIdentity?: pulumi.Input<boolean | undefined>;
    /**
     * Username for authenticating at the repo server
     */
    username?: pulumi.Input<string | undefined>;
}
