// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class AgentsSystemPrompt extends pulumi.CustomResource {
    /**
     * Get an existing AgentsSystemPrompt resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AgentsSystemPromptState, opts?: pulumi.CustomResourceOptions): AgentsSystemPrompt {
        return new AgentsSystemPrompt(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'coderd:index/agentsSystemPrompt:AgentsSystemPrompt';

    /**
     * Returns true if the given object is an instance of AgentsSystemPrompt.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AgentsSystemPrompt {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AgentsSystemPrompt.__pulumiType;
    }

    /**
     * Whether the custom prompt is appended to Coder's built-in system prompt (<span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>, the default) or replaces it entirely (<span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>).
     */
    declare public readonly includeDefaultSystemPrompt: pulumi.Output<boolean>;
    /**
     * The custom system prompt text, typically `file("${path.module}/system-prompt.md")`. Limited to 128 KiB after sanitization.
     */
    declare public readonly systemPrompt: pulumi.Output<string>;

    /**
     * Create a AgentsSystemPrompt resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AgentsSystemPromptArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AgentsSystemPromptArgs | AgentsSystemPromptState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AgentsSystemPromptState | undefined;
            resourceInputs["includeDefaultSystemPrompt"] = state?.includeDefaultSystemPrompt;
            resourceInputs["systemPrompt"] = state?.systemPrompt;
        } else {
            const args = argsOrState as AgentsSystemPromptArgs | undefined;
            if (args?.systemPrompt === undefined && !opts.urn) {
                throw new Error("Missing required property 'systemPrompt'");
            }
            resourceInputs["includeDefaultSystemPrompt"] = args?.includeDefaultSystemPrompt;
            resourceInputs["systemPrompt"] = args?.systemPrompt;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(AgentsSystemPrompt.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering AgentsSystemPrompt resources.
 */
export interface AgentsSystemPromptState {
    /**
     * Whether the custom prompt is appended to Coder's built-in system prompt (<span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>, the default) or replaces it entirely (<span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>).
     */
    includeDefaultSystemPrompt?: pulumi.Input<boolean | undefined>;
    /**
     * The custom system prompt text, typically `file("${path.module}/system-prompt.md")`. Limited to 128 KiB after sanitization.
     */
    systemPrompt?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a AgentsSystemPrompt resource.
 */
export interface AgentsSystemPromptArgs {
    /**
     * Whether the custom prompt is appended to Coder's built-in system prompt (<span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>, the default) or replaces it entirely (<span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>).
     */
    includeDefaultSystemPrompt?: pulumi.Input<boolean | undefined>;
    /**
     * The custom system prompt text, typically `file("${path.module}/system-prompt.md")`. Limited to 128 KiB after sanitization.
     */
    systemPrompt: pulumi.Input<string>;
}
