// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class AgentsDefaultModel extends pulumi.CustomResource {
    /**
     * Get an existing AgentsDefaultModel resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AgentsDefaultModelState, opts?: pulumi.CustomResourceOptions): AgentsDefaultModel {
        return new AgentsDefaultModel(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'coderd:index/agentsDefaultModel:AgentsDefaultModel';

    /**
     * Returns true if the given object is an instance of AgentsDefaultModel.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AgentsDefaultModel {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AgentsDefaultModel.__pulumiType;
    }

    /**
     * ID of the <span pulumi-lang-nodejs="`coderd.AgentsModel`" pulumi-lang-dotnet="`coderd.AgentsModel`" pulumi-lang-go="`AgentsModel`" pulumi-lang-python="`AgentsModel`" pulumi-lang-yaml="`coderd.AgentsModel`" pulumi-lang-java="`coderd.AgentsModel`" pulumi-lang-hcl="`coderd_agents_model`">`coderd.AgentsModel`</span> to mark as the organization's default. Usually this is `coderd_agents_model.<name>.id`.
     */
    declare public readonly modelId: pulumi.Output<string>;
    /**
     * Organization ID whose default Agents model is managed.
     */
    declare public readonly organizationId: pulumi.Output<string>;

    /**
     * Create a AgentsDefaultModel resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AgentsDefaultModelArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AgentsDefaultModelArgs | AgentsDefaultModelState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AgentsDefaultModelState | undefined;
            resourceInputs["modelId"] = state?.modelId;
            resourceInputs["organizationId"] = state?.organizationId;
        } else {
            const args = argsOrState as AgentsDefaultModelArgs | undefined;
            if (args?.modelId === undefined && !opts.urn) {
                throw new Error("Missing required property 'modelId'");
            }
            if (args?.organizationId === undefined && !opts.urn) {
                throw new Error("Missing required property 'organizationId'");
            }
            resourceInputs["modelId"] = args?.modelId;
            resourceInputs["organizationId"] = args?.organizationId;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(AgentsDefaultModel.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering AgentsDefaultModel resources.
 */
export interface AgentsDefaultModelState {
    /**
     * ID of the <span pulumi-lang-nodejs="`coderd.AgentsModel`" pulumi-lang-dotnet="`coderd.AgentsModel`" pulumi-lang-go="`AgentsModel`" pulumi-lang-python="`AgentsModel`" pulumi-lang-yaml="`coderd.AgentsModel`" pulumi-lang-java="`coderd.AgentsModel`" pulumi-lang-hcl="`coderd_agents_model`">`coderd.AgentsModel`</span> to mark as the organization's default. Usually this is `coderd_agents_model.<name>.id`.
     */
    modelId?: pulumi.Input<string | undefined>;
    /**
     * Organization ID whose default Agents model is managed.
     */
    organizationId?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a AgentsDefaultModel resource.
 */
export interface AgentsDefaultModelArgs {
    /**
     * ID of the <span pulumi-lang-nodejs="`coderd.AgentsModel`" pulumi-lang-dotnet="`coderd.AgentsModel`" pulumi-lang-go="`AgentsModel`" pulumi-lang-python="`AgentsModel`" pulumi-lang-yaml="`coderd.AgentsModel`" pulumi-lang-java="`coderd.AgentsModel`" pulumi-lang-hcl="`coderd_agents_model`">`coderd.AgentsModel`</span> to mark as the organization's default. Usually this is `coderd_agents_model.<name>.id`.
     */
    modelId: pulumi.Input<string>;
    /**
     * Organization ID whose default Agents model is managed.
     */
    organizationId: pulumi.Input<string>;
}
