// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class AgentsModel extends pulumi.CustomResource {
    /**
     * Get an existing AgentsModel resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AgentsModelState, opts?: pulumi.CustomResourceOptions): AgentsModel {
        return new AgentsModel(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'coderd:index/agentsModel:AgentsModel';

    /**
     * Returns true if the given object is an instance of AgentsModel.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AgentsModel {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AgentsModel.__pulumiType;
    }

    /**
     * AI provider ID that backs this model. Usually this is `coderd_ai_provider.<name>.id`. Updating it re-derives the read-only <span pulumi-lang-nodejs="`providerType`" pulumi-lang-dotnet="`ProviderType`" pulumi-lang-go="`providerType`" pulumi-lang-python="`provider_type`" pulumi-lang-yaml="`providerType`" pulumi-lang-java="`providerType`" pulumi-lang-hcl="`provider_type`">`providerType`</span> from the referenced provider.
     */
    declare public readonly aiProviderId: pulumi.Output<string>;
    /**
     * Percentage of the context window at which Coder should compact chat context. Defaults to 70 and must be between 0 and 100.
     */
    declare public readonly compressionThreshold: pulumi.Output<number>;
    /**
     * Maximum context window for this model. Must be greater than zero.
     */
    declare public readonly contextLimit: pulumi.Output<number>;
    /**
     * Creation timestamp as Unix seconds.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<number>;
    /**
     * Display name shown in Coder.
     */
    declare public readonly displayName: pulumi.Output<string>;
    /**
     * Whether this model configuration is enabled. Defaults to true.
     */
    declare public readonly enabled: pulumi.Output<boolean>;
    /**
     * Model identifier to use with the referenced provider.
     */
    declare public readonly model: pulumi.Output<string>;
    /**
     * Optional JSON blob of per-call tuning for the model, such as <span pulumi-lang-nodejs="`maxOutputTokens`" pulumi-lang-dotnet="`MaxOutputTokens`" pulumi-lang-go="`maxOutputTokens`" pulumi-lang-python="`max_output_tokens`" pulumi-lang-yaml="`maxOutputTokens`" pulumi-lang-java="`maxOutputTokens`" pulumi-lang-hcl="`max_output_tokens`">`maxOutputTokens`</span>, <span pulumi-lang-nodejs="`temperature`" pulumi-lang-dotnet="`Temperature`" pulumi-lang-go="`temperature`" pulumi-lang-python="`temperature`" pulumi-lang-yaml="`temperature`" pulumi-lang-java="`temperature`" pulumi-lang-hcl="`temperature`">`temperature`</span>, <span pulumi-lang-nodejs="`topP`" pulumi-lang-dotnet="`TopP`" pulumi-lang-go="`topP`" pulumi-lang-python="`top_p`" pulumi-lang-yaml="`topP`" pulumi-lang-java="`topP`" pulumi-lang-hcl="`top_p`">`topP`</span>, <span pulumi-lang-nodejs="`cost`" pulumi-lang-dotnet="`Cost`" pulumi-lang-go="`cost`" pulumi-lang-python="`cost`" pulumi-lang-yaml="`cost`" pulumi-lang-java="`cost`" pulumi-lang-hcl="`cost`">`cost`</span>, and <span pulumi-lang-nodejs="`providerOptions`" pulumi-lang-dotnet="`ProviderOptions`" pulumi-lang-go="`providerOptions`" pulumi-lang-python="`provider_options`" pulumi-lang-yaml="`providerOptions`" pulumi-lang-java="`providerOptions`" pulumi-lang-hcl="`provider_options`">`providerOptions`</span>. See the field reference (including per-provider <span pulumi-lang-nodejs="`providerOptions`" pulumi-lang-dotnet="`ProviderOptions`" pulumi-lang-go="`providerOptions`" pulumi-lang-python="`provider_options`" pulumi-lang-yaml="`providerOptions`" pulumi-lang-java="`providerOptions`" pulumi-lang-hcl="`provider_options`">`providerOptions`</span>) at https://pkg.go.dev/github.com/coder/coder/v2/codersdk#ChatModelCallConfig.
     */
    declare public readonly modelConfig: pulumi.Output<string | undefined>;
    /**
     * Provider type derived by Coder from <span pulumi-lang-nodejs="`aiProviderId`" pulumi-lang-dotnet="`AiProviderId`" pulumi-lang-go="`aiProviderId`" pulumi-lang-python="`ai_provider_id`" pulumi-lang-yaml="`aiProviderId`" pulumi-lang-java="`aiProviderId`" pulumi-lang-hcl="`ai_provider_id`">`aiProviderId`</span>, for example <span pulumi-lang-nodejs="`openai`" pulumi-lang-dotnet="`Openai`" pulumi-lang-go="`openai`" pulumi-lang-python="`openai`" pulumi-lang-yaml="`openai`" pulumi-lang-java="`openai`" pulumi-lang-hcl="`openai`">`openai`</span>, <span pulumi-lang-nodejs="`anthropic`" pulumi-lang-dotnet="`Anthropic`" pulumi-lang-go="`anthropic`" pulumi-lang-python="`anthropic`" pulumi-lang-yaml="`anthropic`" pulumi-lang-java="`anthropic`" pulumi-lang-hcl="`anthropic`">`anthropic`</span>, or <span pulumi-lang-nodejs="`bedrock`" pulumi-lang-dotnet="`Bedrock`" pulumi-lang-go="`bedrock`" pulumi-lang-python="`bedrock`" pulumi-lang-yaml="`bedrock`" pulumi-lang-java="`bedrock`" pulumi-lang-hcl="`bedrock`">`bedrock`</span>.
     */
    declare public /*out*/ readonly providerType: pulumi.Output<string>;
    /**
     * Last update timestamp as Unix seconds.
     */
    declare public /*out*/ readonly updatedAt: pulumi.Output<number>;

    /**
     * Create a AgentsModel resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AgentsModelArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AgentsModelArgs | AgentsModelState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AgentsModelState | undefined;
            resourceInputs["aiProviderId"] = state?.aiProviderId;
            resourceInputs["compressionThreshold"] = state?.compressionThreshold;
            resourceInputs["contextLimit"] = state?.contextLimit;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["displayName"] = state?.displayName;
            resourceInputs["enabled"] = state?.enabled;
            resourceInputs["model"] = state?.model;
            resourceInputs["modelConfig"] = state?.modelConfig;
            resourceInputs["providerType"] = state?.providerType;
            resourceInputs["updatedAt"] = state?.updatedAt;
        } else {
            const args = argsOrState as AgentsModelArgs | undefined;
            if (args?.aiProviderId === undefined && !opts.urn) {
                throw new Error("Missing required property 'aiProviderId'");
            }
            if (args?.contextLimit === undefined && !opts.urn) {
                throw new Error("Missing required property 'contextLimit'");
            }
            if (args?.model === undefined && !opts.urn) {
                throw new Error("Missing required property 'model'");
            }
            resourceInputs["aiProviderId"] = args?.aiProviderId;
            resourceInputs["compressionThreshold"] = args?.compressionThreshold;
            resourceInputs["contextLimit"] = args?.contextLimit;
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["model"] = args?.model;
            resourceInputs["modelConfig"] = args?.modelConfig;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["providerType"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(AgentsModel.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering AgentsModel resources.
 */
export interface AgentsModelState {
    /**
     * AI provider ID that backs this model. Usually this is `coderd_ai_provider.<name>.id`. Updating it re-derives the read-only <span pulumi-lang-nodejs="`providerType`" pulumi-lang-dotnet="`ProviderType`" pulumi-lang-go="`providerType`" pulumi-lang-python="`provider_type`" pulumi-lang-yaml="`providerType`" pulumi-lang-java="`providerType`" pulumi-lang-hcl="`provider_type`">`providerType`</span> from the referenced provider.
     */
    aiProviderId?: pulumi.Input<string | undefined>;
    /**
     * Percentage of the context window at which Coder should compact chat context. Defaults to 70 and must be between 0 and 100.
     */
    compressionThreshold?: pulumi.Input<number | undefined>;
    /**
     * Maximum context window for this model. Must be greater than zero.
     */
    contextLimit?: pulumi.Input<number | undefined>;
    /**
     * Creation timestamp as Unix seconds.
     */
    createdAt?: pulumi.Input<number | undefined>;
    /**
     * Display name shown in Coder.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Whether this model configuration is enabled. Defaults to true.
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * Model identifier to use with the referenced provider.
     */
    model?: pulumi.Input<string | undefined>;
    /**
     * Optional JSON blob of per-call tuning for the model, such as <span pulumi-lang-nodejs="`maxOutputTokens`" pulumi-lang-dotnet="`MaxOutputTokens`" pulumi-lang-go="`maxOutputTokens`" pulumi-lang-python="`max_output_tokens`" pulumi-lang-yaml="`maxOutputTokens`" pulumi-lang-java="`maxOutputTokens`" pulumi-lang-hcl="`max_output_tokens`">`maxOutputTokens`</span>, <span pulumi-lang-nodejs="`temperature`" pulumi-lang-dotnet="`Temperature`" pulumi-lang-go="`temperature`" pulumi-lang-python="`temperature`" pulumi-lang-yaml="`temperature`" pulumi-lang-java="`temperature`" pulumi-lang-hcl="`temperature`">`temperature`</span>, <span pulumi-lang-nodejs="`topP`" pulumi-lang-dotnet="`TopP`" pulumi-lang-go="`topP`" pulumi-lang-python="`top_p`" pulumi-lang-yaml="`topP`" pulumi-lang-java="`topP`" pulumi-lang-hcl="`top_p`">`topP`</span>, <span pulumi-lang-nodejs="`cost`" pulumi-lang-dotnet="`Cost`" pulumi-lang-go="`cost`" pulumi-lang-python="`cost`" pulumi-lang-yaml="`cost`" pulumi-lang-java="`cost`" pulumi-lang-hcl="`cost`">`cost`</span>, and <span pulumi-lang-nodejs="`providerOptions`" pulumi-lang-dotnet="`ProviderOptions`" pulumi-lang-go="`providerOptions`" pulumi-lang-python="`provider_options`" pulumi-lang-yaml="`providerOptions`" pulumi-lang-java="`providerOptions`" pulumi-lang-hcl="`provider_options`">`providerOptions`</span>. See the field reference (including per-provider <span pulumi-lang-nodejs="`providerOptions`" pulumi-lang-dotnet="`ProviderOptions`" pulumi-lang-go="`providerOptions`" pulumi-lang-python="`provider_options`" pulumi-lang-yaml="`providerOptions`" pulumi-lang-java="`providerOptions`" pulumi-lang-hcl="`provider_options`">`providerOptions`</span>) at https://pkg.go.dev/github.com/coder/coder/v2/codersdk#ChatModelCallConfig.
     */
    modelConfig?: pulumi.Input<string | undefined>;
    /**
     * Provider type derived by Coder from <span pulumi-lang-nodejs="`aiProviderId`" pulumi-lang-dotnet="`AiProviderId`" pulumi-lang-go="`aiProviderId`" pulumi-lang-python="`ai_provider_id`" pulumi-lang-yaml="`aiProviderId`" pulumi-lang-java="`aiProviderId`" pulumi-lang-hcl="`ai_provider_id`">`aiProviderId`</span>, for example <span pulumi-lang-nodejs="`openai`" pulumi-lang-dotnet="`Openai`" pulumi-lang-go="`openai`" pulumi-lang-python="`openai`" pulumi-lang-yaml="`openai`" pulumi-lang-java="`openai`" pulumi-lang-hcl="`openai`">`openai`</span>, <span pulumi-lang-nodejs="`anthropic`" pulumi-lang-dotnet="`Anthropic`" pulumi-lang-go="`anthropic`" pulumi-lang-python="`anthropic`" pulumi-lang-yaml="`anthropic`" pulumi-lang-java="`anthropic`" pulumi-lang-hcl="`anthropic`">`anthropic`</span>, or <span pulumi-lang-nodejs="`bedrock`" pulumi-lang-dotnet="`Bedrock`" pulumi-lang-go="`bedrock`" pulumi-lang-python="`bedrock`" pulumi-lang-yaml="`bedrock`" pulumi-lang-java="`bedrock`" pulumi-lang-hcl="`bedrock`">`bedrock`</span>.
     */
    providerType?: pulumi.Input<string | undefined>;
    /**
     * Last update timestamp as Unix seconds.
     */
    updatedAt?: pulumi.Input<number | undefined>;
}

/**
 * The set of arguments for constructing a AgentsModel resource.
 */
export interface AgentsModelArgs {
    /**
     * AI provider ID that backs this model. Usually this is `coderd_ai_provider.<name>.id`. Updating it re-derives the read-only <span pulumi-lang-nodejs="`providerType`" pulumi-lang-dotnet="`ProviderType`" pulumi-lang-go="`providerType`" pulumi-lang-python="`provider_type`" pulumi-lang-yaml="`providerType`" pulumi-lang-java="`providerType`" pulumi-lang-hcl="`provider_type`">`providerType`</span> from the referenced provider.
     */
    aiProviderId: pulumi.Input<string>;
    /**
     * Percentage of the context window at which Coder should compact chat context. Defaults to 70 and must be between 0 and 100.
     */
    compressionThreshold?: pulumi.Input<number | undefined>;
    /**
     * Maximum context window for this model. Must be greater than zero.
     */
    contextLimit: pulumi.Input<number>;
    /**
     * Display name shown in Coder.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Whether this model configuration is enabled. Defaults to true.
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * Model identifier to use with the referenced provider.
     */
    model: pulumi.Input<string>;
    /**
     * Optional JSON blob of per-call tuning for the model, such as <span pulumi-lang-nodejs="`maxOutputTokens`" pulumi-lang-dotnet="`MaxOutputTokens`" pulumi-lang-go="`maxOutputTokens`" pulumi-lang-python="`max_output_tokens`" pulumi-lang-yaml="`maxOutputTokens`" pulumi-lang-java="`maxOutputTokens`" pulumi-lang-hcl="`max_output_tokens`">`maxOutputTokens`</span>, <span pulumi-lang-nodejs="`temperature`" pulumi-lang-dotnet="`Temperature`" pulumi-lang-go="`temperature`" pulumi-lang-python="`temperature`" pulumi-lang-yaml="`temperature`" pulumi-lang-java="`temperature`" pulumi-lang-hcl="`temperature`">`temperature`</span>, <span pulumi-lang-nodejs="`topP`" pulumi-lang-dotnet="`TopP`" pulumi-lang-go="`topP`" pulumi-lang-python="`top_p`" pulumi-lang-yaml="`topP`" pulumi-lang-java="`topP`" pulumi-lang-hcl="`top_p`">`topP`</span>, <span pulumi-lang-nodejs="`cost`" pulumi-lang-dotnet="`Cost`" pulumi-lang-go="`cost`" pulumi-lang-python="`cost`" pulumi-lang-yaml="`cost`" pulumi-lang-java="`cost`" pulumi-lang-hcl="`cost`">`cost`</span>, and <span pulumi-lang-nodejs="`providerOptions`" pulumi-lang-dotnet="`ProviderOptions`" pulumi-lang-go="`providerOptions`" pulumi-lang-python="`provider_options`" pulumi-lang-yaml="`providerOptions`" pulumi-lang-java="`providerOptions`" pulumi-lang-hcl="`provider_options`">`providerOptions`</span>. See the field reference (including per-provider <span pulumi-lang-nodejs="`providerOptions`" pulumi-lang-dotnet="`ProviderOptions`" pulumi-lang-go="`providerOptions`" pulumi-lang-python="`provider_options`" pulumi-lang-yaml="`providerOptions`" pulumi-lang-java="`providerOptions`" pulumi-lang-hcl="`provider_options`">`providerOptions`</span>) at https://pkg.go.dev/github.com/coder/coder/v2/codersdk#ChatModelCallConfig.
     */
    modelConfig?: pulumi.Input<string | undefined>;
}
