// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class AgentsMcpServer extends pulumi.CustomResource {
    /**
     * Get an existing AgentsMcpServer resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AgentsMcpServerState, opts?: pulumi.CustomResourceOptions): AgentsMcpServer {
        return new AgentsMcpServer(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'coderd:index/agentsMcpServer:AgentsMcpServer';

    /**
     * Returns true if the given object is an instance of AgentsMcpServer.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AgentsMcpServer {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AgentsMcpServer.__pulumiType;
    }

    /**
     * Whether tools from this server are available in plan mode. Defaults to false.
     */
    declare public readonly allowInPlanMode: pulumi.Output<boolean>;
    /**
     * HTTP header used for API key authentication. It must be configured when creating a server with <span pulumi-lang-nodejs="`authType " pulumi-lang-dotnet="`AuthType " pulumi-lang-go="`authType " pulumi-lang-python="`auth_type " pulumi-lang-yaml="`authType " pulumi-lang-java="`authType " pulumi-lang-hcl="`auth_type ">`authType </span>= <span pulumi-lang-nodejs=""apiKey"" pulumi-lang-dotnet=""ApiKey"" pulumi-lang-go=""apiKey"" pulumi-lang-python=""api_key"" pulumi-lang-yaml=""apiKey"" pulumi-lang-java=""apiKey"" pulumi-lang-hcl=""api_key"">"apiKey"</span>` or changing its auth type to it.
     */
    declare public readonly apiKeyHeader: pulumi.Output<string>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * API key value. Bump <span pulumi-lang-nodejs="`apiKeyValueWoVersion`" pulumi-lang-dotnet="`ApiKeyValueWoVersion`" pulumi-lang-go="`apiKeyValueWoVersion`" pulumi-lang-python="`api_key_value_wo_version`" pulumi-lang-yaml="`apiKeyValueWoVersion`" pulumi-lang-java="`apiKeyValueWoVersion`" pulumi-lang-hcl="`api_key_value_wo_version`">`apiKeyValueWoVersion`</span> to rotate it.
     */
    declare public readonly apiKeyValueWo: pulumi.Output<string | undefined>;
    /**
     * Version for the write-only API key value. Bump it whenever the value changes.
     */
    declare public readonly apiKeyValueWoVersion: pulumi.Output<number | undefined>;
    /**
     * Authentication type. Valid values are <span pulumi-lang-nodejs="`none`" pulumi-lang-dotnet="`None`" pulumi-lang-go="`none`" pulumi-lang-python="`none`" pulumi-lang-yaml="`none`" pulumi-lang-java="`none`" pulumi-lang-hcl="`none`">`none`</span>, <span pulumi-lang-nodejs="`oauth2`" pulumi-lang-dotnet="`Oauth2`" pulumi-lang-go="`oauth2`" pulumi-lang-python="`oauth2`" pulumi-lang-yaml="`oauth2`" pulumi-lang-java="`oauth2`" pulumi-lang-hcl="`oauth2`">`oauth2`</span>, <span pulumi-lang-nodejs="`apiKey`" pulumi-lang-dotnet="`ApiKey`" pulumi-lang-go="`apiKey`" pulumi-lang-python="`api_key`" pulumi-lang-yaml="`apiKey`" pulumi-lang-java="`apiKey`" pulumi-lang-hcl="`api_key`">`apiKey`</span>, <span pulumi-lang-nodejs="`customHeaders`" pulumi-lang-dotnet="`CustomHeaders`" pulumi-lang-go="`customHeaders`" pulumi-lang-python="`custom_headers`" pulumi-lang-yaml="`customHeaders`" pulumi-lang-java="`customHeaders`" pulumi-lang-hcl="`custom_headers`">`customHeaders`</span>, and <span pulumi-lang-nodejs="`userOidc`" pulumi-lang-dotnet="`UserOidc`" pulumi-lang-go="`userOidc`" pulumi-lang-python="`user_oidc`" pulumi-lang-yaml="`userOidc`" pulumi-lang-java="`userOidc`" pulumi-lang-hcl="`user_oidc`">`userOidc`</span>. Defaults to <span pulumi-lang-nodejs="`none`" pulumi-lang-dotnet="`None`" pulumi-lang-go="`none`" pulumi-lang-python="`none`" pulumi-lang-yaml="`none`" pulumi-lang-java="`none`" pulumi-lang-hcl="`none`">`none`</span>. Changing this value invalidates users' stored OAuth tokens and clears secrets for the previous authentication type.
     */
    declare public readonly authType: pulumi.Output<string>;
    /**
     * Availability policy. Valid values are <span pulumi-lang-nodejs="`forceOn`" pulumi-lang-dotnet="`ForceOn`" pulumi-lang-go="`forceOn`" pulumi-lang-python="`force_on`" pulumi-lang-yaml="`forceOn`" pulumi-lang-java="`forceOn`" pulumi-lang-hcl="`force_on`">`forceOn`</span>, <span pulumi-lang-nodejs="`defaultOn`" pulumi-lang-dotnet="`DefaultOn`" pulumi-lang-go="`defaultOn`" pulumi-lang-python="`default_on`" pulumi-lang-yaml="`defaultOn`" pulumi-lang-java="`defaultOn`" pulumi-lang-hcl="`default_on`">`defaultOn`</span>, and <span pulumi-lang-nodejs="`defaultOff`" pulumi-lang-dotnet="`DefaultOff`" pulumi-lang-go="`defaultOff`" pulumi-lang-python="`default_off`" pulumi-lang-yaml="`defaultOff`" pulumi-lang-java="`defaultOff`" pulumi-lang-hcl="`default_off`">`defaultOff`</span>. Defaults to <span pulumi-lang-nodejs="`defaultOff`" pulumi-lang-dotnet="`DefaultOff`" pulumi-lang-go="`defaultOff`" pulumi-lang-python="`default_off`" pulumi-lang-yaml="`defaultOff`" pulumi-lang-java="`defaultOff`" pulumi-lang-hcl="`default_off`">`defaultOff`</span>.
     */
    declare public readonly availability: pulumi.Output<string>;
    /**
     * Unix timestamp when the MCP server configuration was created.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<number>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * HTTP headers used for custom header authentication. Bump <span pulumi-lang-nodejs="`customHeadersWoVersion`" pulumi-lang-dotnet="`CustomHeadersWoVersion`" pulumi-lang-go="`customHeadersWoVersion`" pulumi-lang-python="`custom_headers_wo_version`" pulumi-lang-yaml="`customHeadersWoVersion`" pulumi-lang-java="`customHeadersWoVersion`" pulumi-lang-hcl="`custom_headers_wo_version`">`customHeadersWoVersion`</span> to replace them.
     */
    declare public readonly customHeadersWo: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * Version for the write-only custom headers. Bump it whenever the map changes.
     */
    declare public readonly customHeadersWoVersion: pulumi.Output<number | undefined>;
    /**
     * Description shown in Coder.
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * Display name shown in Coder.
     */
    declare public readonly displayName: pulumi.Output<string>;
    /**
     * Whether the MCP server is enabled. Defaults to false.
     */
    declare public readonly enabled: pulumi.Output<boolean>;
    /**
     * Whether Coder identity headers are forwarded to the MCP server. Defaults to false.
     */
    declare public readonly forwardCoderHeaders: pulumi.Output<boolean>;
    /**
     * Icon URL shown in Coder.
     */
    declare public readonly iconUrl: pulumi.Output<string>;
    /**
     * Whether the model may select this MCP server based on intent. Defaults to false.
     */
    declare public readonly modelIntent: pulumi.Output<boolean>;
    /**
     * OAuth2 authorization URL. It can be populated by server-side discovery.
     */
    declare public readonly oauth2AuthUrl: pulumi.Output<string>;
    /**
     * OAuth2 client ID. Leave this, <span pulumi-lang-nodejs="`oauth2AuthUrl`" pulumi-lang-dotnet="`Oauth2AuthUrl`" pulumi-lang-go="`oauth2AuthUrl`" pulumi-lang-python="`oauth2_auth_url`" pulumi-lang-yaml="`oauth2AuthUrl`" pulumi-lang-java="`oauth2AuthUrl`" pulumi-lang-hcl="`oauth2_auth_url`">`oauth2AuthUrl`</span>, and <span pulumi-lang-nodejs="`oauth2TokenUrl`" pulumi-lang-dotnet="`Oauth2TokenUrl`" pulumi-lang-go="`oauth2TokenUrl`" pulumi-lang-python="`oauth2_token_url`" pulumi-lang-yaml="`oauth2TokenUrl`" pulumi-lang-java="`oauth2TokenUrl`" pulumi-lang-hcl="`oauth2_token_url`">`oauth2TokenUrl`</span> unset at creation to use OAuth discovery and dynamic client registration; switching an existing server back to discovery requires replacing the resource. Changing it invalidates users' stored OAuth tokens.
     */
    declare public readonly oauth2ClientId: pulumi.Output<string>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * OAuth2 client secret. Bump <span pulumi-lang-nodejs="`oauth2ClientSecretWoVersion`" pulumi-lang-dotnet="`Oauth2ClientSecretWoVersion`" pulumi-lang-go="`oauth2ClientSecretWoVersion`" pulumi-lang-python="`oauth2_client_secret_wo_version`" pulumi-lang-yaml="`oauth2ClientSecretWoVersion`" pulumi-lang-java="`oauth2ClientSecretWoVersion`" pulumi-lang-hcl="`oauth2_client_secret_wo_version`">`oauth2ClientSecretWoVersion`</span> to rotate it.
     */
    declare public readonly oauth2ClientSecretWo: pulumi.Output<string | undefined>;
    /**
     * Version for the write-only OAuth2 client secret. Bump it whenever the secret changes.
     */
    declare public readonly oauth2ClientSecretWoVersion: pulumi.Output<number | undefined>;
    /**
     * OAuth2 token revocation URL. It can be populated by server-side discovery. Changing it invalidates users' stored OAuth tokens.
     */
    declare public readonly oauth2RevocationUrl: pulumi.Output<string>;
    /**
     * Space-separated OAuth2 scopes.
     */
    declare public readonly oauth2Scopes: pulumi.Output<string>;
    /**
     * OAuth2 token URL. It can be populated by server-side discovery. Changing it invalidates users' stored OAuth tokens.
     */
    declare public readonly oauth2TokenUrl: pulumi.Output<string>;
    /**
     * Organization ID that owns the MCP server configuration. Defaults to the provider default organization ID.
     */
    declare public readonly organizationId: pulumi.Output<string>;
    /**
     * Organization-unique slug for the MCP server. The slug can be updated in place.
     */
    declare public readonly slug: pulumi.Output<string>;
    /**
     * Tool names that are allowed. An empty set allows all tools unless denied.
     */
    declare public readonly toolAllowLists: pulumi.Output<string[]>;
    /**
     * Tool names that are denied.
     */
    declare public readonly toolDenyLists: pulumi.Output<string[]>;
    /**
     * MCP transport. Valid values are <span pulumi-lang-nodejs="`streamableHttp`" pulumi-lang-dotnet="`StreamableHttp`" pulumi-lang-go="`streamableHttp`" pulumi-lang-python="`streamable_http`" pulumi-lang-yaml="`streamableHttp`" pulumi-lang-java="`streamableHttp`" pulumi-lang-hcl="`streamable_http`">`streamableHttp`</span> and <span pulumi-lang-nodejs="`sse`" pulumi-lang-dotnet="`Sse`" pulumi-lang-go="`sse`" pulumi-lang-python="`sse`" pulumi-lang-yaml="`sse`" pulumi-lang-java="`sse`" pulumi-lang-hcl="`sse`">`sse`</span>. Defaults to <span pulumi-lang-nodejs="`streamableHttp`" pulumi-lang-dotnet="`StreamableHttp`" pulumi-lang-go="`streamableHttp`" pulumi-lang-python="`streamable_http`" pulumi-lang-yaml="`streamableHttp`" pulumi-lang-java="`streamableHttp`" pulumi-lang-hcl="`streamable_http`">`streamableHttp`</span>.
     */
    declare public readonly transport: pulumi.Output<string>;
    /**
     * Unix timestamp when the MCP server configuration was last updated.
     */
    declare public /*out*/ readonly updatedAt: pulumi.Output<number>;
    /**
     * MCP server URL. Changing this value invalidates users' stored OAuth tokens.
     */
    declare public readonly url: pulumi.Output<string>;

    /**
     * Create a AgentsMcpServer resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AgentsMcpServerArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AgentsMcpServerArgs | AgentsMcpServerState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AgentsMcpServerState | undefined;
            resourceInputs["allowInPlanMode"] = state?.allowInPlanMode;
            resourceInputs["apiKeyHeader"] = state?.apiKeyHeader;
            resourceInputs["apiKeyValueWo"] = state?.apiKeyValueWo;
            resourceInputs["apiKeyValueWoVersion"] = state?.apiKeyValueWoVersion;
            resourceInputs["authType"] = state?.authType;
            resourceInputs["availability"] = state?.availability;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["customHeadersWo"] = state?.customHeadersWo;
            resourceInputs["customHeadersWoVersion"] = state?.customHeadersWoVersion;
            resourceInputs["description"] = state?.description;
            resourceInputs["displayName"] = state?.displayName;
            resourceInputs["enabled"] = state?.enabled;
            resourceInputs["forwardCoderHeaders"] = state?.forwardCoderHeaders;
            resourceInputs["iconUrl"] = state?.iconUrl;
            resourceInputs["modelIntent"] = state?.modelIntent;
            resourceInputs["oauth2AuthUrl"] = state?.oauth2AuthUrl;
            resourceInputs["oauth2ClientId"] = state?.oauth2ClientId;
            resourceInputs["oauth2ClientSecretWo"] = state?.oauth2ClientSecretWo;
            resourceInputs["oauth2ClientSecretWoVersion"] = state?.oauth2ClientSecretWoVersion;
            resourceInputs["oauth2RevocationUrl"] = state?.oauth2RevocationUrl;
            resourceInputs["oauth2Scopes"] = state?.oauth2Scopes;
            resourceInputs["oauth2TokenUrl"] = state?.oauth2TokenUrl;
            resourceInputs["organizationId"] = state?.organizationId;
            resourceInputs["slug"] = state?.slug;
            resourceInputs["toolAllowLists"] = state?.toolAllowLists;
            resourceInputs["toolDenyLists"] = state?.toolDenyLists;
            resourceInputs["transport"] = state?.transport;
            resourceInputs["updatedAt"] = state?.updatedAt;
            resourceInputs["url"] = state?.url;
        } else {
            const args = argsOrState as AgentsMcpServerArgs | undefined;
            if (args?.displayName === undefined && !opts.urn) {
                throw new Error("Missing required property 'displayName'");
            }
            if (args?.slug === undefined && !opts.urn) {
                throw new Error("Missing required property 'slug'");
            }
            if (args?.url === undefined && !opts.urn) {
                throw new Error("Missing required property 'url'");
            }
            resourceInputs["allowInPlanMode"] = args?.allowInPlanMode;
            resourceInputs["apiKeyHeader"] = args?.apiKeyHeader;
            resourceInputs["apiKeyValueWo"] = args?.apiKeyValueWo ? pulumi.secret(args.apiKeyValueWo) : undefined;
            resourceInputs["apiKeyValueWoVersion"] = args?.apiKeyValueWoVersion;
            resourceInputs["authType"] = args?.authType;
            resourceInputs["availability"] = args?.availability;
            resourceInputs["customHeadersWo"] = args?.customHeadersWo ? pulumi.secret(args.customHeadersWo) : undefined;
            resourceInputs["customHeadersWoVersion"] = args?.customHeadersWoVersion;
            resourceInputs["description"] = args?.description;
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["forwardCoderHeaders"] = args?.forwardCoderHeaders;
            resourceInputs["iconUrl"] = args?.iconUrl;
            resourceInputs["modelIntent"] = args?.modelIntent;
            resourceInputs["oauth2AuthUrl"] = args?.oauth2AuthUrl;
            resourceInputs["oauth2ClientId"] = args?.oauth2ClientId;
            resourceInputs["oauth2ClientSecretWo"] = args?.oauth2ClientSecretWo ? pulumi.secret(args.oauth2ClientSecretWo) : undefined;
            resourceInputs["oauth2ClientSecretWoVersion"] = args?.oauth2ClientSecretWoVersion;
            resourceInputs["oauth2RevocationUrl"] = args?.oauth2RevocationUrl;
            resourceInputs["oauth2Scopes"] = args?.oauth2Scopes;
            resourceInputs["oauth2TokenUrl"] = args?.oauth2TokenUrl;
            resourceInputs["organizationId"] = args?.organizationId;
            resourceInputs["slug"] = args?.slug;
            resourceInputs["toolAllowLists"] = args?.toolAllowLists;
            resourceInputs["toolDenyLists"] = args?.toolDenyLists;
            resourceInputs["transport"] = args?.transport;
            resourceInputs["url"] = args?.url;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["apiKeyValueWo", "customHeadersWo", "oauth2ClientSecretWo"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(AgentsMcpServer.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering AgentsMcpServer resources.
 */
export interface AgentsMcpServerState {
    /**
     * Whether tools from this server are available in plan mode. Defaults to false.
     */
    allowInPlanMode?: pulumi.Input<boolean | undefined>;
    /**
     * HTTP header used for API key authentication. It must be configured when creating a server with <span pulumi-lang-nodejs="`authType " pulumi-lang-dotnet="`AuthType " pulumi-lang-go="`authType " pulumi-lang-python="`auth_type " pulumi-lang-yaml="`authType " pulumi-lang-java="`authType " pulumi-lang-hcl="`auth_type ">`authType </span>= <span pulumi-lang-nodejs=""apiKey"" pulumi-lang-dotnet=""ApiKey"" pulumi-lang-go=""apiKey"" pulumi-lang-python=""api_key"" pulumi-lang-yaml=""apiKey"" pulumi-lang-java=""apiKey"" pulumi-lang-hcl=""api_key"">"apiKey"</span>` or changing its auth type to it.
     */
    apiKeyHeader?: pulumi.Input<string | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * API key value. Bump <span pulumi-lang-nodejs="`apiKeyValueWoVersion`" pulumi-lang-dotnet="`ApiKeyValueWoVersion`" pulumi-lang-go="`apiKeyValueWoVersion`" pulumi-lang-python="`api_key_value_wo_version`" pulumi-lang-yaml="`apiKeyValueWoVersion`" pulumi-lang-java="`apiKeyValueWoVersion`" pulumi-lang-hcl="`api_key_value_wo_version`">`apiKeyValueWoVersion`</span> to rotate it.
     */
    apiKeyValueWo?: pulumi.Input<string | undefined>;
    /**
     * Version for the write-only API key value. Bump it whenever the value changes.
     */
    apiKeyValueWoVersion?: pulumi.Input<number | undefined>;
    /**
     * Authentication type. Valid values are <span pulumi-lang-nodejs="`none`" pulumi-lang-dotnet="`None`" pulumi-lang-go="`none`" pulumi-lang-python="`none`" pulumi-lang-yaml="`none`" pulumi-lang-java="`none`" pulumi-lang-hcl="`none`">`none`</span>, <span pulumi-lang-nodejs="`oauth2`" pulumi-lang-dotnet="`Oauth2`" pulumi-lang-go="`oauth2`" pulumi-lang-python="`oauth2`" pulumi-lang-yaml="`oauth2`" pulumi-lang-java="`oauth2`" pulumi-lang-hcl="`oauth2`">`oauth2`</span>, <span pulumi-lang-nodejs="`apiKey`" pulumi-lang-dotnet="`ApiKey`" pulumi-lang-go="`apiKey`" pulumi-lang-python="`api_key`" pulumi-lang-yaml="`apiKey`" pulumi-lang-java="`apiKey`" pulumi-lang-hcl="`api_key`">`apiKey`</span>, <span pulumi-lang-nodejs="`customHeaders`" pulumi-lang-dotnet="`CustomHeaders`" pulumi-lang-go="`customHeaders`" pulumi-lang-python="`custom_headers`" pulumi-lang-yaml="`customHeaders`" pulumi-lang-java="`customHeaders`" pulumi-lang-hcl="`custom_headers`">`customHeaders`</span>, and <span pulumi-lang-nodejs="`userOidc`" pulumi-lang-dotnet="`UserOidc`" pulumi-lang-go="`userOidc`" pulumi-lang-python="`user_oidc`" pulumi-lang-yaml="`userOidc`" pulumi-lang-java="`userOidc`" pulumi-lang-hcl="`user_oidc`">`userOidc`</span>. Defaults to <span pulumi-lang-nodejs="`none`" pulumi-lang-dotnet="`None`" pulumi-lang-go="`none`" pulumi-lang-python="`none`" pulumi-lang-yaml="`none`" pulumi-lang-java="`none`" pulumi-lang-hcl="`none`">`none`</span>. Changing this value invalidates users' stored OAuth tokens and clears secrets for the previous authentication type.
     */
    authType?: pulumi.Input<string | undefined>;
    /**
     * Availability policy. Valid values are <span pulumi-lang-nodejs="`forceOn`" pulumi-lang-dotnet="`ForceOn`" pulumi-lang-go="`forceOn`" pulumi-lang-python="`force_on`" pulumi-lang-yaml="`forceOn`" pulumi-lang-java="`forceOn`" pulumi-lang-hcl="`force_on`">`forceOn`</span>, <span pulumi-lang-nodejs="`defaultOn`" pulumi-lang-dotnet="`DefaultOn`" pulumi-lang-go="`defaultOn`" pulumi-lang-python="`default_on`" pulumi-lang-yaml="`defaultOn`" pulumi-lang-java="`defaultOn`" pulumi-lang-hcl="`default_on`">`defaultOn`</span>, and <span pulumi-lang-nodejs="`defaultOff`" pulumi-lang-dotnet="`DefaultOff`" pulumi-lang-go="`defaultOff`" pulumi-lang-python="`default_off`" pulumi-lang-yaml="`defaultOff`" pulumi-lang-java="`defaultOff`" pulumi-lang-hcl="`default_off`">`defaultOff`</span>. Defaults to <span pulumi-lang-nodejs="`defaultOff`" pulumi-lang-dotnet="`DefaultOff`" pulumi-lang-go="`defaultOff`" pulumi-lang-python="`default_off`" pulumi-lang-yaml="`defaultOff`" pulumi-lang-java="`defaultOff`" pulumi-lang-hcl="`default_off`">`defaultOff`</span>.
     */
    availability?: pulumi.Input<string | undefined>;
    /**
     * Unix timestamp when the MCP server configuration was created.
     */
    createdAt?: pulumi.Input<number | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * HTTP headers used for custom header authentication. Bump <span pulumi-lang-nodejs="`customHeadersWoVersion`" pulumi-lang-dotnet="`CustomHeadersWoVersion`" pulumi-lang-go="`customHeadersWoVersion`" pulumi-lang-python="`custom_headers_wo_version`" pulumi-lang-yaml="`customHeadersWoVersion`" pulumi-lang-java="`customHeadersWoVersion`" pulumi-lang-hcl="`custom_headers_wo_version`">`customHeadersWoVersion`</span> to replace them.
     */
    customHeadersWo?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * Version for the write-only custom headers. Bump it whenever the map changes.
     */
    customHeadersWoVersion?: pulumi.Input<number | undefined>;
    /**
     * Description shown in Coder.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Display name shown in Coder.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Whether the MCP server is enabled. Defaults to false.
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * Whether Coder identity headers are forwarded to the MCP server. Defaults to false.
     */
    forwardCoderHeaders?: pulumi.Input<boolean | undefined>;
    /**
     * Icon URL shown in Coder.
     */
    iconUrl?: pulumi.Input<string | undefined>;
    /**
     * Whether the model may select this MCP server based on intent. Defaults to false.
     */
    modelIntent?: pulumi.Input<boolean | undefined>;
    /**
     * OAuth2 authorization URL. It can be populated by server-side discovery.
     */
    oauth2AuthUrl?: pulumi.Input<string | undefined>;
    /**
     * OAuth2 client ID. Leave this, <span pulumi-lang-nodejs="`oauth2AuthUrl`" pulumi-lang-dotnet="`Oauth2AuthUrl`" pulumi-lang-go="`oauth2AuthUrl`" pulumi-lang-python="`oauth2_auth_url`" pulumi-lang-yaml="`oauth2AuthUrl`" pulumi-lang-java="`oauth2AuthUrl`" pulumi-lang-hcl="`oauth2_auth_url`">`oauth2AuthUrl`</span>, and <span pulumi-lang-nodejs="`oauth2TokenUrl`" pulumi-lang-dotnet="`Oauth2TokenUrl`" pulumi-lang-go="`oauth2TokenUrl`" pulumi-lang-python="`oauth2_token_url`" pulumi-lang-yaml="`oauth2TokenUrl`" pulumi-lang-java="`oauth2TokenUrl`" pulumi-lang-hcl="`oauth2_token_url`">`oauth2TokenUrl`</span> unset at creation to use OAuth discovery and dynamic client registration; switching an existing server back to discovery requires replacing the resource. Changing it invalidates users' stored OAuth tokens.
     */
    oauth2ClientId?: pulumi.Input<string | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * OAuth2 client secret. Bump <span pulumi-lang-nodejs="`oauth2ClientSecretWoVersion`" pulumi-lang-dotnet="`Oauth2ClientSecretWoVersion`" pulumi-lang-go="`oauth2ClientSecretWoVersion`" pulumi-lang-python="`oauth2_client_secret_wo_version`" pulumi-lang-yaml="`oauth2ClientSecretWoVersion`" pulumi-lang-java="`oauth2ClientSecretWoVersion`" pulumi-lang-hcl="`oauth2_client_secret_wo_version`">`oauth2ClientSecretWoVersion`</span> to rotate it.
     */
    oauth2ClientSecretWo?: pulumi.Input<string | undefined>;
    /**
     * Version for the write-only OAuth2 client secret. Bump it whenever the secret changes.
     */
    oauth2ClientSecretWoVersion?: pulumi.Input<number | undefined>;
    /**
     * OAuth2 token revocation URL. It can be populated by server-side discovery. Changing it invalidates users' stored OAuth tokens.
     */
    oauth2RevocationUrl?: pulumi.Input<string | undefined>;
    /**
     * Space-separated OAuth2 scopes.
     */
    oauth2Scopes?: pulumi.Input<string | undefined>;
    /**
     * OAuth2 token URL. It can be populated by server-side discovery. Changing it invalidates users' stored OAuth tokens.
     */
    oauth2TokenUrl?: pulumi.Input<string | undefined>;
    /**
     * Organization ID that owns the MCP server configuration. Defaults to the provider default organization ID.
     */
    organizationId?: pulumi.Input<string | undefined>;
    /**
     * Organization-unique slug for the MCP server. The slug can be updated in place.
     */
    slug?: pulumi.Input<string | undefined>;
    /**
     * Tool names that are allowed. An empty set allows all tools unless denied.
     */
    toolAllowLists?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Tool names that are denied.
     */
    toolDenyLists?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * MCP transport. Valid values are <span pulumi-lang-nodejs="`streamableHttp`" pulumi-lang-dotnet="`StreamableHttp`" pulumi-lang-go="`streamableHttp`" pulumi-lang-python="`streamable_http`" pulumi-lang-yaml="`streamableHttp`" pulumi-lang-java="`streamableHttp`" pulumi-lang-hcl="`streamable_http`">`streamableHttp`</span> and <span pulumi-lang-nodejs="`sse`" pulumi-lang-dotnet="`Sse`" pulumi-lang-go="`sse`" pulumi-lang-python="`sse`" pulumi-lang-yaml="`sse`" pulumi-lang-java="`sse`" pulumi-lang-hcl="`sse`">`sse`</span>. Defaults to <span pulumi-lang-nodejs="`streamableHttp`" pulumi-lang-dotnet="`StreamableHttp`" pulumi-lang-go="`streamableHttp`" pulumi-lang-python="`streamable_http`" pulumi-lang-yaml="`streamableHttp`" pulumi-lang-java="`streamableHttp`" pulumi-lang-hcl="`streamable_http`">`streamableHttp`</span>.
     */
    transport?: pulumi.Input<string | undefined>;
    /**
     * Unix timestamp when the MCP server configuration was last updated.
     */
    updatedAt?: pulumi.Input<number | undefined>;
    /**
     * MCP server URL. Changing this value invalidates users' stored OAuth tokens.
     */
    url?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a AgentsMcpServer resource.
 */
export interface AgentsMcpServerArgs {
    /**
     * Whether tools from this server are available in plan mode. Defaults to false.
     */
    allowInPlanMode?: pulumi.Input<boolean | undefined>;
    /**
     * HTTP header used for API key authentication. It must be configured when creating a server with <span pulumi-lang-nodejs="`authType " pulumi-lang-dotnet="`AuthType " pulumi-lang-go="`authType " pulumi-lang-python="`auth_type " pulumi-lang-yaml="`authType " pulumi-lang-java="`authType " pulumi-lang-hcl="`auth_type ">`authType </span>= <span pulumi-lang-nodejs=""apiKey"" pulumi-lang-dotnet=""ApiKey"" pulumi-lang-go=""apiKey"" pulumi-lang-python=""api_key"" pulumi-lang-yaml=""apiKey"" pulumi-lang-java=""apiKey"" pulumi-lang-hcl=""api_key"">"apiKey"</span>` or changing its auth type to it.
     */
    apiKeyHeader?: pulumi.Input<string | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * API key value. Bump <span pulumi-lang-nodejs="`apiKeyValueWoVersion`" pulumi-lang-dotnet="`ApiKeyValueWoVersion`" pulumi-lang-go="`apiKeyValueWoVersion`" pulumi-lang-python="`api_key_value_wo_version`" pulumi-lang-yaml="`apiKeyValueWoVersion`" pulumi-lang-java="`apiKeyValueWoVersion`" pulumi-lang-hcl="`api_key_value_wo_version`">`apiKeyValueWoVersion`</span> to rotate it.
     */
    apiKeyValueWo?: pulumi.Input<string | undefined>;
    /**
     * Version for the write-only API key value. Bump it whenever the value changes.
     */
    apiKeyValueWoVersion?: pulumi.Input<number | undefined>;
    /**
     * Authentication type. Valid values are <span pulumi-lang-nodejs="`none`" pulumi-lang-dotnet="`None`" pulumi-lang-go="`none`" pulumi-lang-python="`none`" pulumi-lang-yaml="`none`" pulumi-lang-java="`none`" pulumi-lang-hcl="`none`">`none`</span>, <span pulumi-lang-nodejs="`oauth2`" pulumi-lang-dotnet="`Oauth2`" pulumi-lang-go="`oauth2`" pulumi-lang-python="`oauth2`" pulumi-lang-yaml="`oauth2`" pulumi-lang-java="`oauth2`" pulumi-lang-hcl="`oauth2`">`oauth2`</span>, <span pulumi-lang-nodejs="`apiKey`" pulumi-lang-dotnet="`ApiKey`" pulumi-lang-go="`apiKey`" pulumi-lang-python="`api_key`" pulumi-lang-yaml="`apiKey`" pulumi-lang-java="`apiKey`" pulumi-lang-hcl="`api_key`">`apiKey`</span>, <span pulumi-lang-nodejs="`customHeaders`" pulumi-lang-dotnet="`CustomHeaders`" pulumi-lang-go="`customHeaders`" pulumi-lang-python="`custom_headers`" pulumi-lang-yaml="`customHeaders`" pulumi-lang-java="`customHeaders`" pulumi-lang-hcl="`custom_headers`">`customHeaders`</span>, and <span pulumi-lang-nodejs="`userOidc`" pulumi-lang-dotnet="`UserOidc`" pulumi-lang-go="`userOidc`" pulumi-lang-python="`user_oidc`" pulumi-lang-yaml="`userOidc`" pulumi-lang-java="`userOidc`" pulumi-lang-hcl="`user_oidc`">`userOidc`</span>. Defaults to <span pulumi-lang-nodejs="`none`" pulumi-lang-dotnet="`None`" pulumi-lang-go="`none`" pulumi-lang-python="`none`" pulumi-lang-yaml="`none`" pulumi-lang-java="`none`" pulumi-lang-hcl="`none`">`none`</span>. Changing this value invalidates users' stored OAuth tokens and clears secrets for the previous authentication type.
     */
    authType?: pulumi.Input<string | undefined>;
    /**
     * Availability policy. Valid values are <span pulumi-lang-nodejs="`forceOn`" pulumi-lang-dotnet="`ForceOn`" pulumi-lang-go="`forceOn`" pulumi-lang-python="`force_on`" pulumi-lang-yaml="`forceOn`" pulumi-lang-java="`forceOn`" pulumi-lang-hcl="`force_on`">`forceOn`</span>, <span pulumi-lang-nodejs="`defaultOn`" pulumi-lang-dotnet="`DefaultOn`" pulumi-lang-go="`defaultOn`" pulumi-lang-python="`default_on`" pulumi-lang-yaml="`defaultOn`" pulumi-lang-java="`defaultOn`" pulumi-lang-hcl="`default_on`">`defaultOn`</span>, and <span pulumi-lang-nodejs="`defaultOff`" pulumi-lang-dotnet="`DefaultOff`" pulumi-lang-go="`defaultOff`" pulumi-lang-python="`default_off`" pulumi-lang-yaml="`defaultOff`" pulumi-lang-java="`defaultOff`" pulumi-lang-hcl="`default_off`">`defaultOff`</span>. Defaults to <span pulumi-lang-nodejs="`defaultOff`" pulumi-lang-dotnet="`DefaultOff`" pulumi-lang-go="`defaultOff`" pulumi-lang-python="`default_off`" pulumi-lang-yaml="`defaultOff`" pulumi-lang-java="`defaultOff`" pulumi-lang-hcl="`default_off`">`defaultOff`</span>.
     */
    availability?: pulumi.Input<string | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * HTTP headers used for custom header authentication. Bump <span pulumi-lang-nodejs="`customHeadersWoVersion`" pulumi-lang-dotnet="`CustomHeadersWoVersion`" pulumi-lang-go="`customHeadersWoVersion`" pulumi-lang-python="`custom_headers_wo_version`" pulumi-lang-yaml="`customHeadersWoVersion`" pulumi-lang-java="`customHeadersWoVersion`" pulumi-lang-hcl="`custom_headers_wo_version`">`customHeadersWoVersion`</span> to replace them.
     */
    customHeadersWo?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * Version for the write-only custom headers. Bump it whenever the map changes.
     */
    customHeadersWoVersion?: pulumi.Input<number | undefined>;
    /**
     * Description shown in Coder.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Display name shown in Coder.
     */
    displayName: pulumi.Input<string>;
    /**
     * Whether the MCP server is enabled. Defaults to false.
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * Whether Coder identity headers are forwarded to the MCP server. Defaults to false.
     */
    forwardCoderHeaders?: pulumi.Input<boolean | undefined>;
    /**
     * Icon URL shown in Coder.
     */
    iconUrl?: pulumi.Input<string | undefined>;
    /**
     * Whether the model may select this MCP server based on intent. Defaults to false.
     */
    modelIntent?: pulumi.Input<boolean | undefined>;
    /**
     * OAuth2 authorization URL. It can be populated by server-side discovery.
     */
    oauth2AuthUrl?: pulumi.Input<string | undefined>;
    /**
     * OAuth2 client ID. Leave this, <span pulumi-lang-nodejs="`oauth2AuthUrl`" pulumi-lang-dotnet="`Oauth2AuthUrl`" pulumi-lang-go="`oauth2AuthUrl`" pulumi-lang-python="`oauth2_auth_url`" pulumi-lang-yaml="`oauth2AuthUrl`" pulumi-lang-java="`oauth2AuthUrl`" pulumi-lang-hcl="`oauth2_auth_url`">`oauth2AuthUrl`</span>, and <span pulumi-lang-nodejs="`oauth2TokenUrl`" pulumi-lang-dotnet="`Oauth2TokenUrl`" pulumi-lang-go="`oauth2TokenUrl`" pulumi-lang-python="`oauth2_token_url`" pulumi-lang-yaml="`oauth2TokenUrl`" pulumi-lang-java="`oauth2TokenUrl`" pulumi-lang-hcl="`oauth2_token_url`">`oauth2TokenUrl`</span> unset at creation to use OAuth discovery and dynamic client registration; switching an existing server back to discovery requires replacing the resource. Changing it invalidates users' stored OAuth tokens.
     */
    oauth2ClientId?: pulumi.Input<string | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * OAuth2 client secret. Bump <span pulumi-lang-nodejs="`oauth2ClientSecretWoVersion`" pulumi-lang-dotnet="`Oauth2ClientSecretWoVersion`" pulumi-lang-go="`oauth2ClientSecretWoVersion`" pulumi-lang-python="`oauth2_client_secret_wo_version`" pulumi-lang-yaml="`oauth2ClientSecretWoVersion`" pulumi-lang-java="`oauth2ClientSecretWoVersion`" pulumi-lang-hcl="`oauth2_client_secret_wo_version`">`oauth2ClientSecretWoVersion`</span> to rotate it.
     */
    oauth2ClientSecretWo?: pulumi.Input<string | undefined>;
    /**
     * Version for the write-only OAuth2 client secret. Bump it whenever the secret changes.
     */
    oauth2ClientSecretWoVersion?: pulumi.Input<number | undefined>;
    /**
     * OAuth2 token revocation URL. It can be populated by server-side discovery. Changing it invalidates users' stored OAuth tokens.
     */
    oauth2RevocationUrl?: pulumi.Input<string | undefined>;
    /**
     * Space-separated OAuth2 scopes.
     */
    oauth2Scopes?: pulumi.Input<string | undefined>;
    /**
     * OAuth2 token URL. It can be populated by server-side discovery. Changing it invalidates users' stored OAuth tokens.
     */
    oauth2TokenUrl?: pulumi.Input<string | undefined>;
    /**
     * Organization ID that owns the MCP server configuration. Defaults to the provider default organization ID.
     */
    organizationId?: pulumi.Input<string | undefined>;
    /**
     * Organization-unique slug for the MCP server. The slug can be updated in place.
     */
    slug: pulumi.Input<string>;
    /**
     * Tool names that are allowed. An empty set allows all tools unless denied.
     */
    toolAllowLists?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Tool names that are denied.
     */
    toolDenyLists?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * MCP transport. Valid values are <span pulumi-lang-nodejs="`streamableHttp`" pulumi-lang-dotnet="`StreamableHttp`" pulumi-lang-go="`streamableHttp`" pulumi-lang-python="`streamable_http`" pulumi-lang-yaml="`streamableHttp`" pulumi-lang-java="`streamableHttp`" pulumi-lang-hcl="`streamable_http`">`streamableHttp`</span> and <span pulumi-lang-nodejs="`sse`" pulumi-lang-dotnet="`Sse`" pulumi-lang-go="`sse`" pulumi-lang-python="`sse`" pulumi-lang-yaml="`sse`" pulumi-lang-java="`sse`" pulumi-lang-hcl="`sse`">`sse`</span>. Defaults to <span pulumi-lang-nodejs="`streamableHttp`" pulumi-lang-dotnet="`StreamableHttp`" pulumi-lang-go="`streamableHttp`" pulumi-lang-python="`streamable_http`" pulumi-lang-yaml="`streamableHttp`" pulumi-lang-java="`streamableHttp`" pulumi-lang-hcl="`streamable_http`">`streamableHttp`</span>.
     */
    transport?: pulumi.Input<string | undefined>;
    /**
     * MCP server URL. Changing this value invalidates users' stored OAuth tokens.
     */
    url: pulumi.Input<string>;
}
