// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class AiModelPrice extends pulumi.CustomResource {
    /**
     * Get an existing AiModelPrice resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AiModelPriceState, opts?: pulumi.CustomResourceOptions): AiModelPrice {
        return new AiModelPrice(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'coderd:index/aiModelPrice:AiModelPrice';

    /**
     * Returns true if the given object is an instance of AiModelPrice.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AiModelPrice {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AiModelPrice.__pulumiType;
    }

    /**
     * Price per 1M tokens read from the prompt cache, in integer micro-units: <span pulumi-lang-nodejs="`1000000`" pulumi-lang-dotnet="`1000000`" pulumi-lang-go="`1000000`" pulumi-lang-python="`1000000`" pulumi-lang-yaml="`1000000`" pulumi-lang-java="`1000000`" pulumi-lang-hcl="`1000000`">`1000000`</span> is $1.00 per 1M tokens. Omit it if the price is not known, which AI Gateway counts as zero cost. Set <span pulumi-lang-nodejs="`0`" pulumi-lang-dotnet="`0`" pulumi-lang-go="`0`" pulumi-lang-python="`0`" pulumi-lang-yaml="`0`" pulumi-lang-java="`0`" pulumi-lang-hcl="`0`">`0`</span> to declare the tokens free of charge.
     */
    declare public readonly cacheReadPrice: pulumi.Output<number | undefined>;
    /**
     * Price per 1M tokens written to the prompt cache, in integer micro-units: <span pulumi-lang-nodejs="`1000000`" pulumi-lang-dotnet="`1000000`" pulumi-lang-go="`1000000`" pulumi-lang-python="`1000000`" pulumi-lang-yaml="`1000000`" pulumi-lang-java="`1000000`" pulumi-lang-hcl="`1000000`">`1000000`</span> is $1.00 per 1M tokens. Omit it if the price is not known, which AI Gateway counts as zero cost. Set <span pulumi-lang-nodejs="`0`" pulumi-lang-dotnet="`0`" pulumi-lang-go="`0`" pulumi-lang-python="`0`" pulumi-lang-yaml="`0`" pulumi-lang-java="`0`" pulumi-lang-hcl="`0`">`0`</span> to declare the tokens free of charge.
     */
    declare public readonly cacheWritePrice: pulumi.Output<number | undefined>;
    /**
     * Price per 1M input tokens, in integer micro-units: <span pulumi-lang-nodejs="`1000000`" pulumi-lang-dotnet="`1000000`" pulumi-lang-go="`1000000`" pulumi-lang-python="`1000000`" pulumi-lang-yaml="`1000000`" pulumi-lang-java="`1000000`" pulumi-lang-hcl="`1000000`">`1000000`</span> is $1.00 per 1M tokens. Omit it if the price is not known, which AI Gateway counts as zero cost. Set <span pulumi-lang-nodejs="`0`" pulumi-lang-dotnet="`0`" pulumi-lang-go="`0`" pulumi-lang-python="`0`" pulumi-lang-yaml="`0`" pulumi-lang-java="`0`" pulumi-lang-hcl="`0`">`0`</span> to declare the tokens free of charge.
     */
    declare public readonly inputPrice: pulumi.Output<number | undefined>;
    /**
     * Model name the price applies to, as shown in AI Gateway usage and spend reports, for example `claude-sonnet-4-5`. Changing this forces a new resource.
     */
    declare public readonly model: pulumi.Output<string>;
    /**
     * Price per 1M output tokens, in integer micro-units: <span pulumi-lang-nodejs="`1000000`" pulumi-lang-dotnet="`1000000`" pulumi-lang-go="`1000000`" pulumi-lang-python="`1000000`" pulumi-lang-yaml="`1000000`" pulumi-lang-java="`1000000`" pulumi-lang-hcl="`1000000`">`1000000`</span> is $1.00 per 1M tokens. Omit it if the price is not known, which AI Gateway counts as zero cost. Set <span pulumi-lang-nodejs="`0`" pulumi-lang-dotnet="`0`" pulumi-lang-go="`0`" pulumi-lang-python="`0`" pulumi-lang-yaml="`0`" pulumi-lang-java="`0`" pulumi-lang-hcl="`0`">`0`</span> to declare the tokens free of charge.
     */
    declare public readonly outputPrice: pulumi.Output<number | undefined>;
    /**
     * AI provider type the price applies to. Valid values are <span pulumi-lang-nodejs="`openai`" pulumi-lang-dotnet="`Openai`" pulumi-lang-go="`openai`" pulumi-lang-python="`openai`" pulumi-lang-yaml="`openai`" pulumi-lang-java="`openai`" pulumi-lang-hcl="`openai`">`openai`</span>, <span pulumi-lang-nodejs="`anthropic`" pulumi-lang-dotnet="`Anthropic`" pulumi-lang-go="`anthropic`" pulumi-lang-python="`anthropic`" pulumi-lang-yaml="`anthropic`" pulumi-lang-java="`anthropic`" pulumi-lang-hcl="`anthropic`">`anthropic`</span>, <span pulumi-lang-nodejs="`azure`" pulumi-lang-dotnet="`Azure`" pulumi-lang-go="`azure`" pulumi-lang-python="`azure`" pulumi-lang-yaml="`azure`" pulumi-lang-java="`azure`" pulumi-lang-hcl="`azure`">`azure`</span>, <span pulumi-lang-nodejs="`bedrock`" pulumi-lang-dotnet="`Bedrock`" pulumi-lang-go="`bedrock`" pulumi-lang-python="`bedrock`" pulumi-lang-yaml="`bedrock`" pulumi-lang-java="`bedrock`" pulumi-lang-hcl="`bedrock`">`bedrock`</span>, <span pulumi-lang-nodejs="`google`" pulumi-lang-dotnet="`Google`" pulumi-lang-go="`google`" pulumi-lang-python="`google`" pulumi-lang-yaml="`google`" pulumi-lang-java="`google`" pulumi-lang-hcl="`google`">`google`</span>, <span pulumi-lang-nodejs="`openrouter`" pulumi-lang-dotnet="`Openrouter`" pulumi-lang-go="`openrouter`" pulumi-lang-python="`openrouter`" pulumi-lang-yaml="`openrouter`" pulumi-lang-java="`openrouter`" pulumi-lang-hcl="`openrouter`">`openrouter`</span>, <span pulumi-lang-nodejs="`vercel`" pulumi-lang-dotnet="`Vercel`" pulumi-lang-go="`vercel`" pulumi-lang-python="`vercel`" pulumi-lang-yaml="`vercel`" pulumi-lang-java="`vercel`" pulumi-lang-hcl="`vercel`">`vercel`</span>, and <span pulumi-lang-nodejs="`copilot`" pulumi-lang-dotnet="`Copilot`" pulumi-lang-go="`copilot`" pulumi-lang-python="`copilot`" pulumi-lang-yaml="`copilot`" pulumi-lang-java="`copilot`" pulumi-lang-hcl="`copilot`">`copilot`</span>. `openai-compat` is not currently supported. Changing this forces a new resource.
     */
    declare public readonly providerType: pulumi.Output<string>;

    /**
     * Create a AiModelPrice resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AiModelPriceArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AiModelPriceArgs | AiModelPriceState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AiModelPriceState | undefined;
            resourceInputs["cacheReadPrice"] = state?.cacheReadPrice;
            resourceInputs["cacheWritePrice"] = state?.cacheWritePrice;
            resourceInputs["inputPrice"] = state?.inputPrice;
            resourceInputs["model"] = state?.model;
            resourceInputs["outputPrice"] = state?.outputPrice;
            resourceInputs["providerType"] = state?.providerType;
        } else {
            const args = argsOrState as AiModelPriceArgs | undefined;
            if (args?.model === undefined && !opts.urn) {
                throw new Error("Missing required property 'model'");
            }
            if (args?.providerType === undefined && !opts.urn) {
                throw new Error("Missing required property 'providerType'");
            }
            resourceInputs["cacheReadPrice"] = args?.cacheReadPrice;
            resourceInputs["cacheWritePrice"] = args?.cacheWritePrice;
            resourceInputs["inputPrice"] = args?.inputPrice;
            resourceInputs["model"] = args?.model;
            resourceInputs["outputPrice"] = args?.outputPrice;
            resourceInputs["providerType"] = args?.providerType;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(AiModelPrice.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering AiModelPrice resources.
 */
export interface AiModelPriceState {
    /**
     * Price per 1M tokens read from the prompt cache, in integer micro-units: <span pulumi-lang-nodejs="`1000000`" pulumi-lang-dotnet="`1000000`" pulumi-lang-go="`1000000`" pulumi-lang-python="`1000000`" pulumi-lang-yaml="`1000000`" pulumi-lang-java="`1000000`" pulumi-lang-hcl="`1000000`">`1000000`</span> is $1.00 per 1M tokens. Omit it if the price is not known, which AI Gateway counts as zero cost. Set <span pulumi-lang-nodejs="`0`" pulumi-lang-dotnet="`0`" pulumi-lang-go="`0`" pulumi-lang-python="`0`" pulumi-lang-yaml="`0`" pulumi-lang-java="`0`" pulumi-lang-hcl="`0`">`0`</span> to declare the tokens free of charge.
     */
    cacheReadPrice?: pulumi.Input<number | undefined>;
    /**
     * Price per 1M tokens written to the prompt cache, in integer micro-units: <span pulumi-lang-nodejs="`1000000`" pulumi-lang-dotnet="`1000000`" pulumi-lang-go="`1000000`" pulumi-lang-python="`1000000`" pulumi-lang-yaml="`1000000`" pulumi-lang-java="`1000000`" pulumi-lang-hcl="`1000000`">`1000000`</span> is $1.00 per 1M tokens. Omit it if the price is not known, which AI Gateway counts as zero cost. Set <span pulumi-lang-nodejs="`0`" pulumi-lang-dotnet="`0`" pulumi-lang-go="`0`" pulumi-lang-python="`0`" pulumi-lang-yaml="`0`" pulumi-lang-java="`0`" pulumi-lang-hcl="`0`">`0`</span> to declare the tokens free of charge.
     */
    cacheWritePrice?: pulumi.Input<number | undefined>;
    /**
     * Price per 1M input tokens, in integer micro-units: <span pulumi-lang-nodejs="`1000000`" pulumi-lang-dotnet="`1000000`" pulumi-lang-go="`1000000`" pulumi-lang-python="`1000000`" pulumi-lang-yaml="`1000000`" pulumi-lang-java="`1000000`" pulumi-lang-hcl="`1000000`">`1000000`</span> is $1.00 per 1M tokens. Omit it if the price is not known, which AI Gateway counts as zero cost. Set <span pulumi-lang-nodejs="`0`" pulumi-lang-dotnet="`0`" pulumi-lang-go="`0`" pulumi-lang-python="`0`" pulumi-lang-yaml="`0`" pulumi-lang-java="`0`" pulumi-lang-hcl="`0`">`0`</span> to declare the tokens free of charge.
     */
    inputPrice?: pulumi.Input<number | undefined>;
    /**
     * Model name the price applies to, as shown in AI Gateway usage and spend reports, for example `claude-sonnet-4-5`. Changing this forces a new resource.
     */
    model?: pulumi.Input<string | undefined>;
    /**
     * Price per 1M output tokens, in integer micro-units: <span pulumi-lang-nodejs="`1000000`" pulumi-lang-dotnet="`1000000`" pulumi-lang-go="`1000000`" pulumi-lang-python="`1000000`" pulumi-lang-yaml="`1000000`" pulumi-lang-java="`1000000`" pulumi-lang-hcl="`1000000`">`1000000`</span> is $1.00 per 1M tokens. Omit it if the price is not known, which AI Gateway counts as zero cost. Set <span pulumi-lang-nodejs="`0`" pulumi-lang-dotnet="`0`" pulumi-lang-go="`0`" pulumi-lang-python="`0`" pulumi-lang-yaml="`0`" pulumi-lang-java="`0`" pulumi-lang-hcl="`0`">`0`</span> to declare the tokens free of charge.
     */
    outputPrice?: pulumi.Input<number | undefined>;
    /**
     * AI provider type the price applies to. Valid values are <span pulumi-lang-nodejs="`openai`" pulumi-lang-dotnet="`Openai`" pulumi-lang-go="`openai`" pulumi-lang-python="`openai`" pulumi-lang-yaml="`openai`" pulumi-lang-java="`openai`" pulumi-lang-hcl="`openai`">`openai`</span>, <span pulumi-lang-nodejs="`anthropic`" pulumi-lang-dotnet="`Anthropic`" pulumi-lang-go="`anthropic`" pulumi-lang-python="`anthropic`" pulumi-lang-yaml="`anthropic`" pulumi-lang-java="`anthropic`" pulumi-lang-hcl="`anthropic`">`anthropic`</span>, <span pulumi-lang-nodejs="`azure`" pulumi-lang-dotnet="`Azure`" pulumi-lang-go="`azure`" pulumi-lang-python="`azure`" pulumi-lang-yaml="`azure`" pulumi-lang-java="`azure`" pulumi-lang-hcl="`azure`">`azure`</span>, <span pulumi-lang-nodejs="`bedrock`" pulumi-lang-dotnet="`Bedrock`" pulumi-lang-go="`bedrock`" pulumi-lang-python="`bedrock`" pulumi-lang-yaml="`bedrock`" pulumi-lang-java="`bedrock`" pulumi-lang-hcl="`bedrock`">`bedrock`</span>, <span pulumi-lang-nodejs="`google`" pulumi-lang-dotnet="`Google`" pulumi-lang-go="`google`" pulumi-lang-python="`google`" pulumi-lang-yaml="`google`" pulumi-lang-java="`google`" pulumi-lang-hcl="`google`">`google`</span>, <span pulumi-lang-nodejs="`openrouter`" pulumi-lang-dotnet="`Openrouter`" pulumi-lang-go="`openrouter`" pulumi-lang-python="`openrouter`" pulumi-lang-yaml="`openrouter`" pulumi-lang-java="`openrouter`" pulumi-lang-hcl="`openrouter`">`openrouter`</span>, <span pulumi-lang-nodejs="`vercel`" pulumi-lang-dotnet="`Vercel`" pulumi-lang-go="`vercel`" pulumi-lang-python="`vercel`" pulumi-lang-yaml="`vercel`" pulumi-lang-java="`vercel`" pulumi-lang-hcl="`vercel`">`vercel`</span>, and <span pulumi-lang-nodejs="`copilot`" pulumi-lang-dotnet="`Copilot`" pulumi-lang-go="`copilot`" pulumi-lang-python="`copilot`" pulumi-lang-yaml="`copilot`" pulumi-lang-java="`copilot`" pulumi-lang-hcl="`copilot`">`copilot`</span>. `openai-compat` is not currently supported. Changing this forces a new resource.
     */
    providerType?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a AiModelPrice resource.
 */
export interface AiModelPriceArgs {
    /**
     * Price per 1M tokens read from the prompt cache, in integer micro-units: <span pulumi-lang-nodejs="`1000000`" pulumi-lang-dotnet="`1000000`" pulumi-lang-go="`1000000`" pulumi-lang-python="`1000000`" pulumi-lang-yaml="`1000000`" pulumi-lang-java="`1000000`" pulumi-lang-hcl="`1000000`">`1000000`</span> is $1.00 per 1M tokens. Omit it if the price is not known, which AI Gateway counts as zero cost. Set <span pulumi-lang-nodejs="`0`" pulumi-lang-dotnet="`0`" pulumi-lang-go="`0`" pulumi-lang-python="`0`" pulumi-lang-yaml="`0`" pulumi-lang-java="`0`" pulumi-lang-hcl="`0`">`0`</span> to declare the tokens free of charge.
     */
    cacheReadPrice?: pulumi.Input<number | undefined>;
    /**
     * Price per 1M tokens written to the prompt cache, in integer micro-units: <span pulumi-lang-nodejs="`1000000`" pulumi-lang-dotnet="`1000000`" pulumi-lang-go="`1000000`" pulumi-lang-python="`1000000`" pulumi-lang-yaml="`1000000`" pulumi-lang-java="`1000000`" pulumi-lang-hcl="`1000000`">`1000000`</span> is $1.00 per 1M tokens. Omit it if the price is not known, which AI Gateway counts as zero cost. Set <span pulumi-lang-nodejs="`0`" pulumi-lang-dotnet="`0`" pulumi-lang-go="`0`" pulumi-lang-python="`0`" pulumi-lang-yaml="`0`" pulumi-lang-java="`0`" pulumi-lang-hcl="`0`">`0`</span> to declare the tokens free of charge.
     */
    cacheWritePrice?: pulumi.Input<number | undefined>;
    /**
     * Price per 1M input tokens, in integer micro-units: <span pulumi-lang-nodejs="`1000000`" pulumi-lang-dotnet="`1000000`" pulumi-lang-go="`1000000`" pulumi-lang-python="`1000000`" pulumi-lang-yaml="`1000000`" pulumi-lang-java="`1000000`" pulumi-lang-hcl="`1000000`">`1000000`</span> is $1.00 per 1M tokens. Omit it if the price is not known, which AI Gateway counts as zero cost. Set <span pulumi-lang-nodejs="`0`" pulumi-lang-dotnet="`0`" pulumi-lang-go="`0`" pulumi-lang-python="`0`" pulumi-lang-yaml="`0`" pulumi-lang-java="`0`" pulumi-lang-hcl="`0`">`0`</span> to declare the tokens free of charge.
     */
    inputPrice?: pulumi.Input<number | undefined>;
    /**
     * Model name the price applies to, as shown in AI Gateway usage and spend reports, for example `claude-sonnet-4-5`. Changing this forces a new resource.
     */
    model: pulumi.Input<string>;
    /**
     * Price per 1M output tokens, in integer micro-units: <span pulumi-lang-nodejs="`1000000`" pulumi-lang-dotnet="`1000000`" pulumi-lang-go="`1000000`" pulumi-lang-python="`1000000`" pulumi-lang-yaml="`1000000`" pulumi-lang-java="`1000000`" pulumi-lang-hcl="`1000000`">`1000000`</span> is $1.00 per 1M tokens. Omit it if the price is not known, which AI Gateway counts as zero cost. Set <span pulumi-lang-nodejs="`0`" pulumi-lang-dotnet="`0`" pulumi-lang-go="`0`" pulumi-lang-python="`0`" pulumi-lang-yaml="`0`" pulumi-lang-java="`0`" pulumi-lang-hcl="`0`">`0`</span> to declare the tokens free of charge.
     */
    outputPrice?: pulumi.Input<number | undefined>;
    /**
     * AI provider type the price applies to. Valid values are <span pulumi-lang-nodejs="`openai`" pulumi-lang-dotnet="`Openai`" pulumi-lang-go="`openai`" pulumi-lang-python="`openai`" pulumi-lang-yaml="`openai`" pulumi-lang-java="`openai`" pulumi-lang-hcl="`openai`">`openai`</span>, <span pulumi-lang-nodejs="`anthropic`" pulumi-lang-dotnet="`Anthropic`" pulumi-lang-go="`anthropic`" pulumi-lang-python="`anthropic`" pulumi-lang-yaml="`anthropic`" pulumi-lang-java="`anthropic`" pulumi-lang-hcl="`anthropic`">`anthropic`</span>, <span pulumi-lang-nodejs="`azure`" pulumi-lang-dotnet="`Azure`" pulumi-lang-go="`azure`" pulumi-lang-python="`azure`" pulumi-lang-yaml="`azure`" pulumi-lang-java="`azure`" pulumi-lang-hcl="`azure`">`azure`</span>, <span pulumi-lang-nodejs="`bedrock`" pulumi-lang-dotnet="`Bedrock`" pulumi-lang-go="`bedrock`" pulumi-lang-python="`bedrock`" pulumi-lang-yaml="`bedrock`" pulumi-lang-java="`bedrock`" pulumi-lang-hcl="`bedrock`">`bedrock`</span>, <span pulumi-lang-nodejs="`google`" pulumi-lang-dotnet="`Google`" pulumi-lang-go="`google`" pulumi-lang-python="`google`" pulumi-lang-yaml="`google`" pulumi-lang-java="`google`" pulumi-lang-hcl="`google`">`google`</span>, <span pulumi-lang-nodejs="`openrouter`" pulumi-lang-dotnet="`Openrouter`" pulumi-lang-go="`openrouter`" pulumi-lang-python="`openrouter`" pulumi-lang-yaml="`openrouter`" pulumi-lang-java="`openrouter`" pulumi-lang-hcl="`openrouter`">`openrouter`</span>, <span pulumi-lang-nodejs="`vercel`" pulumi-lang-dotnet="`Vercel`" pulumi-lang-go="`vercel`" pulumi-lang-python="`vercel`" pulumi-lang-yaml="`vercel`" pulumi-lang-java="`vercel`" pulumi-lang-hcl="`vercel`">`vercel`</span>, and <span pulumi-lang-nodejs="`copilot`" pulumi-lang-dotnet="`Copilot`" pulumi-lang-go="`copilot`" pulumi-lang-python="`copilot`" pulumi-lang-yaml="`copilot`" pulumi-lang-java="`copilot`" pulumi-lang-hcl="`copilot`">`copilot`</span>. `openai-compat` is not currently supported. Changing this forces a new resource.
     */
    providerType: pulumi.Input<string>;
}
