// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class AiProvider extends pulumi.CustomResource {
    /**
     * Get an existing AiProvider resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AiProviderState, opts?: pulumi.CustomResourceOptions): AiProvider {
        return new AiProvider(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'coderd:index/aiProvider:AiProvider';

    /**
     * Returns true if the given object is an instance of AiProvider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AiProvider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AiProvider.__pulumiType;
    }

    /**
     * Masked API key value returned by Coder for display only.
     */
    declare public /*out*/ readonly apiKeyMasked: pulumi.Output<string>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Plaintext API key for the provider. Not valid for <span pulumi-lang-nodejs="`bedrock`" pulumi-lang-dotnet="`Bedrock`" pulumi-lang-go="`bedrock`" pulumi-lang-python="`bedrock`" pulumi-lang-yaml="`bedrock`" pulumi-lang-java="`bedrock`" pulumi-lang-hcl="`bedrock`">`bedrock`</span> or <span pulumi-lang-nodejs="`copilot`" pulumi-lang-dotnet="`Copilot`" pulumi-lang-go="`copilot`" pulumi-lang-python="`copilot`" pulumi-lang-yaml="`copilot`" pulumi-lang-java="`copilot`" pulumi-lang-hcl="`copilot`">`copilot`</span>, or when `settings.bedrock` is set. Bump <span pulumi-lang-nodejs="`apiKeyWoVersion`" pulumi-lang-dotnet="`ApiKeyWoVersion`" pulumi-lang-go="`apiKeyWoVersion`" pulumi-lang-python="`api_key_wo_version`" pulumi-lang-yaml="`apiKeyWoVersion`" pulumi-lang-java="`apiKeyWoVersion`" pulumi-lang-hcl="`api_key_wo_version`">`apiKeyWoVersion`</span> to rotate it.
     */
    declare public readonly apiKeyWo: pulumi.Output<string | undefined>;
    /**
     * Version for the write-only API key. Required when <span pulumi-lang-nodejs="`apiKeyWo`" pulumi-lang-dotnet="`ApiKeyWo`" pulumi-lang-go="`apiKeyWo`" pulumi-lang-python="`api_key_wo`" pulumi-lang-yaml="`apiKeyWo`" pulumi-lang-java="`apiKeyWo`" pulumi-lang-hcl="`api_key_wo`">`apiKeyWo`</span> is set; bump it whenever <span pulumi-lang-nodejs="`apiKeyWo`" pulumi-lang-dotnet="`ApiKeyWo`" pulumi-lang-go="`apiKeyWo`" pulumi-lang-python="`api_key_wo`" pulumi-lang-yaml="`apiKeyWo`" pulumi-lang-java="`apiKeyWo`" pulumi-lang-hcl="`api_key_wo`">`apiKeyWo`</span> changes to rotate the stored key.
     */
    declare public readonly apiKeyWoVersion: pulumi.Output<number | undefined>;
    /**
     * Absolute HTTP(S) base URL for the upstream provider endpoint.
     */
    declare public readonly baseUrl: pulumi.Output<string>;
    /**
     * Creation timestamp as Unix seconds.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<number>;
    /**
     * Display name shown in Coder. If omitted, defaults to the provider name.
     */
    declare public readonly displayName: pulumi.Output<string>;
    /**
     * Whether this AI provider is enabled. Defaults to true.
     */
    declare public readonly enabled: pulumi.Output<boolean>;
    /**
     * Unique provider name. Must be lowercase alphanumeric words separated by hyphens.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Type-specific provider settings.
     */
    declare public readonly settings: pulumi.Output<outputs.AiProviderSettings | undefined>;
    /**
     * AI provider type. Valid values are <span pulumi-lang-nodejs="`openai`" pulumi-lang-dotnet="`Openai`" pulumi-lang-go="`openai`" pulumi-lang-python="`openai`" pulumi-lang-yaml="`openai`" pulumi-lang-java="`openai`" pulumi-lang-hcl="`openai`">`openai`</span>, <span pulumi-lang-nodejs="`anthropic`" pulumi-lang-dotnet="`Anthropic`" pulumi-lang-go="`anthropic`" pulumi-lang-python="`anthropic`" pulumi-lang-yaml="`anthropic`" pulumi-lang-java="`anthropic`" pulumi-lang-hcl="`anthropic`">`anthropic`</span>, <span pulumi-lang-nodejs="`azure`" pulumi-lang-dotnet="`Azure`" pulumi-lang-go="`azure`" pulumi-lang-python="`azure`" pulumi-lang-yaml="`azure`" pulumi-lang-java="`azure`" pulumi-lang-hcl="`azure`">`azure`</span>, <span pulumi-lang-nodejs="`bedrock`" pulumi-lang-dotnet="`Bedrock`" pulumi-lang-go="`bedrock`" pulumi-lang-python="`bedrock`" pulumi-lang-yaml="`bedrock`" pulumi-lang-java="`bedrock`" pulumi-lang-hcl="`bedrock`">`bedrock`</span>, <span pulumi-lang-nodejs="`google`" pulumi-lang-dotnet="`Google`" pulumi-lang-go="`google`" pulumi-lang-python="`google`" pulumi-lang-yaml="`google`" pulumi-lang-java="`google`" pulumi-lang-hcl="`google`">`google`</span>, `openai-compat`, <span pulumi-lang-nodejs="`openrouter`" pulumi-lang-dotnet="`Openrouter`" pulumi-lang-go="`openrouter`" pulumi-lang-python="`openrouter`" pulumi-lang-yaml="`openrouter`" pulumi-lang-java="`openrouter`" pulumi-lang-hcl="`openrouter`">`openrouter`</span>, <span pulumi-lang-nodejs="`vercel`" pulumi-lang-dotnet="`Vercel`" pulumi-lang-go="`vercel`" pulumi-lang-python="`vercel`" pulumi-lang-yaml="`vercel`" pulumi-lang-java="`vercel`" pulumi-lang-hcl="`vercel`">`vercel`</span>, and <span pulumi-lang-nodejs="`copilot`" pulumi-lang-dotnet="`Copilot`" pulumi-lang-go="`copilot`" pulumi-lang-python="`copilot`" pulumi-lang-yaml="`copilot`" pulumi-lang-java="`copilot`" pulumi-lang-hcl="`copilot`">`copilot`</span>.
     */
    declare public readonly type: pulumi.Output<string>;
    /**
     * Last update timestamp as Unix seconds.
     */
    declare public /*out*/ readonly updatedAt: pulumi.Output<number>;

    /**
     * Create a AiProvider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AiProviderArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AiProviderArgs | AiProviderState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AiProviderState | undefined;
            resourceInputs["apiKeyMasked"] = state?.apiKeyMasked;
            resourceInputs["apiKeyWo"] = state?.apiKeyWo;
            resourceInputs["apiKeyWoVersion"] = state?.apiKeyWoVersion;
            resourceInputs["baseUrl"] = state?.baseUrl;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["displayName"] = state?.displayName;
            resourceInputs["enabled"] = state?.enabled;
            resourceInputs["name"] = state?.name;
            resourceInputs["settings"] = state?.settings;
            resourceInputs["type"] = state?.type;
            resourceInputs["updatedAt"] = state?.updatedAt;
        } else {
            const args = argsOrState as AiProviderArgs | undefined;
            if (args?.baseUrl === undefined && !opts.urn) {
                throw new Error("Missing required property 'baseUrl'");
            }
            if (args?.type === undefined && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            resourceInputs["apiKeyWo"] = args?.apiKeyWo ? pulumi.secret(args.apiKeyWo) : undefined;
            resourceInputs["apiKeyWoVersion"] = args?.apiKeyWoVersion;
            resourceInputs["baseUrl"] = args?.baseUrl;
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["name"] = args?.name;
            resourceInputs["settings"] = args?.settings;
            resourceInputs["type"] = args?.type;
            resourceInputs["apiKeyMasked"] = undefined /*out*/;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["apiKeyWo"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(AiProvider.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering AiProvider resources.
 */
export interface AiProviderState {
    /**
     * Masked API key value returned by Coder for display only.
     */
    apiKeyMasked?: pulumi.Input<string | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Plaintext API key for the provider. Not valid for <span pulumi-lang-nodejs="`bedrock`" pulumi-lang-dotnet="`Bedrock`" pulumi-lang-go="`bedrock`" pulumi-lang-python="`bedrock`" pulumi-lang-yaml="`bedrock`" pulumi-lang-java="`bedrock`" pulumi-lang-hcl="`bedrock`">`bedrock`</span> or <span pulumi-lang-nodejs="`copilot`" pulumi-lang-dotnet="`Copilot`" pulumi-lang-go="`copilot`" pulumi-lang-python="`copilot`" pulumi-lang-yaml="`copilot`" pulumi-lang-java="`copilot`" pulumi-lang-hcl="`copilot`">`copilot`</span>, or when `settings.bedrock` is set. Bump <span pulumi-lang-nodejs="`apiKeyWoVersion`" pulumi-lang-dotnet="`ApiKeyWoVersion`" pulumi-lang-go="`apiKeyWoVersion`" pulumi-lang-python="`api_key_wo_version`" pulumi-lang-yaml="`apiKeyWoVersion`" pulumi-lang-java="`apiKeyWoVersion`" pulumi-lang-hcl="`api_key_wo_version`">`apiKeyWoVersion`</span> to rotate it.
     */
    apiKeyWo?: pulumi.Input<string | undefined>;
    /**
     * Version for the write-only API key. Required when <span pulumi-lang-nodejs="`apiKeyWo`" pulumi-lang-dotnet="`ApiKeyWo`" pulumi-lang-go="`apiKeyWo`" pulumi-lang-python="`api_key_wo`" pulumi-lang-yaml="`apiKeyWo`" pulumi-lang-java="`apiKeyWo`" pulumi-lang-hcl="`api_key_wo`">`apiKeyWo`</span> is set; bump it whenever <span pulumi-lang-nodejs="`apiKeyWo`" pulumi-lang-dotnet="`ApiKeyWo`" pulumi-lang-go="`apiKeyWo`" pulumi-lang-python="`api_key_wo`" pulumi-lang-yaml="`apiKeyWo`" pulumi-lang-java="`apiKeyWo`" pulumi-lang-hcl="`api_key_wo`">`apiKeyWo`</span> changes to rotate the stored key.
     */
    apiKeyWoVersion?: pulumi.Input<number | undefined>;
    /**
     * Absolute HTTP(S) base URL for the upstream provider endpoint.
     */
    baseUrl?: pulumi.Input<string | undefined>;
    /**
     * Creation timestamp as Unix seconds.
     */
    createdAt?: pulumi.Input<number | undefined>;
    /**
     * Display name shown in Coder. If omitted, defaults to the provider name.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Whether this AI provider is enabled. Defaults to true.
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * Unique provider name. Must be lowercase alphanumeric words separated by hyphens.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Type-specific provider settings.
     */
    settings?: pulumi.Input<inputs.AiProviderSettings | undefined>;
    /**
     * AI provider type. Valid values are <span pulumi-lang-nodejs="`openai`" pulumi-lang-dotnet="`Openai`" pulumi-lang-go="`openai`" pulumi-lang-python="`openai`" pulumi-lang-yaml="`openai`" pulumi-lang-java="`openai`" pulumi-lang-hcl="`openai`">`openai`</span>, <span pulumi-lang-nodejs="`anthropic`" pulumi-lang-dotnet="`Anthropic`" pulumi-lang-go="`anthropic`" pulumi-lang-python="`anthropic`" pulumi-lang-yaml="`anthropic`" pulumi-lang-java="`anthropic`" pulumi-lang-hcl="`anthropic`">`anthropic`</span>, <span pulumi-lang-nodejs="`azure`" pulumi-lang-dotnet="`Azure`" pulumi-lang-go="`azure`" pulumi-lang-python="`azure`" pulumi-lang-yaml="`azure`" pulumi-lang-java="`azure`" pulumi-lang-hcl="`azure`">`azure`</span>, <span pulumi-lang-nodejs="`bedrock`" pulumi-lang-dotnet="`Bedrock`" pulumi-lang-go="`bedrock`" pulumi-lang-python="`bedrock`" pulumi-lang-yaml="`bedrock`" pulumi-lang-java="`bedrock`" pulumi-lang-hcl="`bedrock`">`bedrock`</span>, <span pulumi-lang-nodejs="`google`" pulumi-lang-dotnet="`Google`" pulumi-lang-go="`google`" pulumi-lang-python="`google`" pulumi-lang-yaml="`google`" pulumi-lang-java="`google`" pulumi-lang-hcl="`google`">`google`</span>, `openai-compat`, <span pulumi-lang-nodejs="`openrouter`" pulumi-lang-dotnet="`Openrouter`" pulumi-lang-go="`openrouter`" pulumi-lang-python="`openrouter`" pulumi-lang-yaml="`openrouter`" pulumi-lang-java="`openrouter`" pulumi-lang-hcl="`openrouter`">`openrouter`</span>, <span pulumi-lang-nodejs="`vercel`" pulumi-lang-dotnet="`Vercel`" pulumi-lang-go="`vercel`" pulumi-lang-python="`vercel`" pulumi-lang-yaml="`vercel`" pulumi-lang-java="`vercel`" pulumi-lang-hcl="`vercel`">`vercel`</span>, and <span pulumi-lang-nodejs="`copilot`" pulumi-lang-dotnet="`Copilot`" pulumi-lang-go="`copilot`" pulumi-lang-python="`copilot`" pulumi-lang-yaml="`copilot`" pulumi-lang-java="`copilot`" pulumi-lang-hcl="`copilot`">`copilot`</span>.
     */
    type?: pulumi.Input<string | undefined>;
    /**
     * Last update timestamp as Unix seconds.
     */
    updatedAt?: pulumi.Input<number | undefined>;
}

/**
 * The set of arguments for constructing a AiProvider resource.
 */
export interface AiProviderArgs {
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Plaintext API key for the provider. Not valid for <span pulumi-lang-nodejs="`bedrock`" pulumi-lang-dotnet="`Bedrock`" pulumi-lang-go="`bedrock`" pulumi-lang-python="`bedrock`" pulumi-lang-yaml="`bedrock`" pulumi-lang-java="`bedrock`" pulumi-lang-hcl="`bedrock`">`bedrock`</span> or <span pulumi-lang-nodejs="`copilot`" pulumi-lang-dotnet="`Copilot`" pulumi-lang-go="`copilot`" pulumi-lang-python="`copilot`" pulumi-lang-yaml="`copilot`" pulumi-lang-java="`copilot`" pulumi-lang-hcl="`copilot`">`copilot`</span>, or when `settings.bedrock` is set. Bump <span pulumi-lang-nodejs="`apiKeyWoVersion`" pulumi-lang-dotnet="`ApiKeyWoVersion`" pulumi-lang-go="`apiKeyWoVersion`" pulumi-lang-python="`api_key_wo_version`" pulumi-lang-yaml="`apiKeyWoVersion`" pulumi-lang-java="`apiKeyWoVersion`" pulumi-lang-hcl="`api_key_wo_version`">`apiKeyWoVersion`</span> to rotate it.
     */
    apiKeyWo?: pulumi.Input<string | undefined>;
    /**
     * Version for the write-only API key. Required when <span pulumi-lang-nodejs="`apiKeyWo`" pulumi-lang-dotnet="`ApiKeyWo`" pulumi-lang-go="`apiKeyWo`" pulumi-lang-python="`api_key_wo`" pulumi-lang-yaml="`apiKeyWo`" pulumi-lang-java="`apiKeyWo`" pulumi-lang-hcl="`api_key_wo`">`apiKeyWo`</span> is set; bump it whenever <span pulumi-lang-nodejs="`apiKeyWo`" pulumi-lang-dotnet="`ApiKeyWo`" pulumi-lang-go="`apiKeyWo`" pulumi-lang-python="`api_key_wo`" pulumi-lang-yaml="`apiKeyWo`" pulumi-lang-java="`apiKeyWo`" pulumi-lang-hcl="`api_key_wo`">`apiKeyWo`</span> changes to rotate the stored key.
     */
    apiKeyWoVersion?: pulumi.Input<number | undefined>;
    /**
     * Absolute HTTP(S) base URL for the upstream provider endpoint.
     */
    baseUrl: pulumi.Input<string>;
    /**
     * Display name shown in Coder. If omitted, defaults to the provider name.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Whether this AI provider is enabled. Defaults to true.
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * Unique provider name. Must be lowercase alphanumeric words separated by hyphens.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Type-specific provider settings.
     */
    settings?: pulumi.Input<inputs.AiProviderSettings | undefined>;
    /**
     * AI provider type. Valid values are <span pulumi-lang-nodejs="`openai`" pulumi-lang-dotnet="`Openai`" pulumi-lang-go="`openai`" pulumi-lang-python="`openai`" pulumi-lang-yaml="`openai`" pulumi-lang-java="`openai`" pulumi-lang-hcl="`openai`">`openai`</span>, <span pulumi-lang-nodejs="`anthropic`" pulumi-lang-dotnet="`Anthropic`" pulumi-lang-go="`anthropic`" pulumi-lang-python="`anthropic`" pulumi-lang-yaml="`anthropic`" pulumi-lang-java="`anthropic`" pulumi-lang-hcl="`anthropic`">`anthropic`</span>, <span pulumi-lang-nodejs="`azure`" pulumi-lang-dotnet="`Azure`" pulumi-lang-go="`azure`" pulumi-lang-python="`azure`" pulumi-lang-yaml="`azure`" pulumi-lang-java="`azure`" pulumi-lang-hcl="`azure`">`azure`</span>, <span pulumi-lang-nodejs="`bedrock`" pulumi-lang-dotnet="`Bedrock`" pulumi-lang-go="`bedrock`" pulumi-lang-python="`bedrock`" pulumi-lang-yaml="`bedrock`" pulumi-lang-java="`bedrock`" pulumi-lang-hcl="`bedrock`">`bedrock`</span>, <span pulumi-lang-nodejs="`google`" pulumi-lang-dotnet="`Google`" pulumi-lang-go="`google`" pulumi-lang-python="`google`" pulumi-lang-yaml="`google`" pulumi-lang-java="`google`" pulumi-lang-hcl="`google`">`google`</span>, `openai-compat`, <span pulumi-lang-nodejs="`openrouter`" pulumi-lang-dotnet="`Openrouter`" pulumi-lang-go="`openrouter`" pulumi-lang-python="`openrouter`" pulumi-lang-yaml="`openrouter`" pulumi-lang-java="`openrouter`" pulumi-lang-hcl="`openrouter`">`openrouter`</span>, <span pulumi-lang-nodejs="`vercel`" pulumi-lang-dotnet="`Vercel`" pulumi-lang-go="`vercel`" pulumi-lang-python="`vercel`" pulumi-lang-yaml="`vercel`" pulumi-lang-java="`vercel`" pulumi-lang-hcl="`vercel`">`vercel`</span>, and <span pulumi-lang-nodejs="`copilot`" pulumi-lang-dotnet="`Copilot`" pulumi-lang-go="`copilot`" pulumi-lang-python="`copilot`" pulumi-lang-yaml="`copilot`" pulumi-lang-java="`copilot`" pulumi-lang-hcl="`copilot`">`copilot`</span>.
     */
    type: pulumi.Input<string>;
}
