// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class DefaultAgentsModel extends pulumi.CustomResource {
    /**
     * Get an existing DefaultAgentsModel resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DefaultAgentsModelState, opts?: pulumi.CustomResourceOptions): DefaultAgentsModel {
        return new DefaultAgentsModel(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'coderd:index/defaultAgentsModel:DefaultAgentsModel';

    /**
     * Returns true if the given object is an instance of DefaultAgentsModel.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is DefaultAgentsModel {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === DefaultAgentsModel.__pulumiType;
    }

    /**
     * ID of the <span pulumi-lang-nodejs="`coderd.AgentsModel`" pulumi-lang-dotnet="`coderd.AgentsModel`" pulumi-lang-go="`AgentsModel`" pulumi-lang-python="`AgentsModel`" pulumi-lang-yaml="`coderd.AgentsModel`" pulumi-lang-java="`coderd.AgentsModel`" pulumi-lang-hcl="`coderd_agents_model`">`coderd.AgentsModel`</span> to mark as the deployment-wide default. Usually this is `coderd_agents_model.<name>.id`.
     */
    declare public readonly modelId: pulumi.Output<string>;

    /**
     * Create a DefaultAgentsModel resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DefaultAgentsModelArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DefaultAgentsModelArgs | DefaultAgentsModelState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as DefaultAgentsModelState | undefined;
            resourceInputs["modelId"] = state?.modelId;
        } else {
            const args = argsOrState as DefaultAgentsModelArgs | undefined;
            if (args?.modelId === undefined && !opts.urn) {
                throw new Error("Missing required property 'modelId'");
            }
            resourceInputs["modelId"] = args?.modelId;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(DefaultAgentsModel.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering DefaultAgentsModel resources.
 */
export interface DefaultAgentsModelState {
    /**
     * ID of the <span pulumi-lang-nodejs="`coderd.AgentsModel`" pulumi-lang-dotnet="`coderd.AgentsModel`" pulumi-lang-go="`AgentsModel`" pulumi-lang-python="`AgentsModel`" pulumi-lang-yaml="`coderd.AgentsModel`" pulumi-lang-java="`coderd.AgentsModel`" pulumi-lang-hcl="`coderd_agents_model`">`coderd.AgentsModel`</span> to mark as the deployment-wide default. Usually this is `coderd_agents_model.<name>.id`.
     */
    modelId?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a DefaultAgentsModel resource.
 */
export interface DefaultAgentsModelArgs {
    /**
     * ID of the <span pulumi-lang-nodejs="`coderd.AgentsModel`" pulumi-lang-dotnet="`coderd.AgentsModel`" pulumi-lang-go="`AgentsModel`" pulumi-lang-python="`AgentsModel`" pulumi-lang-yaml="`coderd.AgentsModel`" pulumi-lang-java="`coderd.AgentsModel`" pulumi-lang-hcl="`coderd_agents_model`">`coderd.AgentsModel`</span> to mark as the deployment-wide default. Usually this is `coderd_agents_model.<name>.id`.
     */
    modelId: pulumi.Input<string>;
}
