// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getOrganization(args?: GetOrganizationArgs, opts?: pulumi.InvokeOptions): Promise<GetOrganizationResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("coderd:index/getOrganization:getOrganization", {
        "id": args.id,
        "isDefault": args.isDefault,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getOrganization.
 */
export interface GetOrganizationArgs {
    id?: string;
    isDefault?: boolean;
    name?: string;
}

/**
 * A collection of values returned by getOrganization.
 */
export interface GetOrganizationResult {
    readonly createdAt: number;
    readonly id: string;
    readonly isDefault: boolean;
    readonly members: string[];
    readonly name: string;
    readonly updatedAt: number;
    readonly workspaceSharing: string;
}
export function getOrganizationOutput(args?: GetOrganizationOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetOrganizationResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("coderd:index/getOrganization:getOrganization", {
        "id": args.id,
        "isDefault": args.isDefault,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getOrganization.
 */
export interface GetOrganizationOutputArgs {
    id?: pulumi.Input<string | undefined>;
    isDefault?: pulumi.Input<boolean | undefined>;
    name?: pulumi.Input<string | undefined>;
}
