// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getTemplate(args?: GetTemplateArgs, opts?: pulumi.InvokeOptions): Promise<GetTemplateResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("coderd:index/getTemplate:getTemplate", {
        "id": args.id,
        "name": args.name,
        "organizationId": args.organizationId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getTemplate.
 */
export interface GetTemplateArgs {
    id?: string;
    name?: string;
    organizationId?: string;
}

/**
 * A collection of values returned by getTemplate.
 */
export interface GetTemplateResult {
    readonly acl: outputs.GetTemplateAcl;
    readonly activeUserCount: number;
    readonly activeVersionId: string;
    readonly activityBumpMs: number;
    readonly allowUserAutostart: boolean;
    readonly allowUserAutostop: boolean;
    readonly allowUserCancelWorkspaceJobs: boolean;
    readonly autoStartPermittedDaysOfWeeks: string[];
    readonly autoStopRequirement: outputs.GetTemplateAutoStopRequirement;
    readonly corsBehavior: string;
    readonly createdAt: number;
    readonly createdByUserId: string;
    readonly defaultTtlMs: number;
    readonly deprecated: boolean;
    readonly deprecationMessage: string;
    readonly description: string;
    readonly displayName: string;
    readonly failureTtlMs: number;
    readonly icon: string;
    readonly id: string;
    readonly maxPortShareLevel: string;
    readonly name: string;
    readonly organizationId: string;
    readonly requireActiveVersion: boolean;
    readonly timeTilDormantAutodeleteMs: number;
    readonly timeTilDormantMs: number;
    readonly updatedAt: number;
}
export function getTemplateOutput(args?: GetTemplateOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetTemplateResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("coderd:index/getTemplate:getTemplate", {
        "id": args.id,
        "name": args.name,
        "organizationId": args.organizationId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getTemplate.
 */
export interface GetTemplateOutputArgs {
    id?: pulumi.Input<string | undefined>;
    name?: pulumi.Input<string | undefined>;
    organizationId?: pulumi.Input<string | undefined>;
}
