// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Group extends pulumi.CustomResource {
    /**
     * Get an existing Group resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: GroupState, opts?: pulumi.CustomResourceOptions): Group {
        return new Group(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'coderd:index/group:Group';

    /**
     * Returns true if the given object is an instance of Group.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Group {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Group.__pulumiType;
    }

    /**
     * The URL of the group's avatar.
     */
    declare public readonly avatarUrl: pulumi.Output<string>;
    /**
     * The display name of the group. Defaults to the group name.
     */
    declare public readonly displayName: pulumi.Output<string>;
    /**
     * Members of the group, by ID. If <span pulumi-lang-nodejs="`null`" pulumi-lang-dotnet="`Null`" pulumi-lang-go="`null`" pulumi-lang-python="`null`" pulumi-lang-yaml="`null`" pulumi-lang-java="`null`" pulumi-lang-hcl="`null`">`null`</span>, members will not be added or removed by Terraform. To have a group resource with unmanaged members, but be able to read the members in Terraform, use `data.coderd_group`
     */
    declare public readonly members: pulumi.Output<string[] | undefined>;
    /**
     * The unique name of the group.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The organization ID that the group belongs to. Defaults to the provider default organization ID.
     */
    declare public readonly organizationId: pulumi.Output<string>;
    /**
     * The number of quota credits to allocate to each user in the group.
     */
    declare public readonly quotaAllowance: pulumi.Output<number>;

    /**
     * Create a Group resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: GroupArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: GroupArgs | GroupState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as GroupState | undefined;
            resourceInputs["avatarUrl"] = state?.avatarUrl;
            resourceInputs["displayName"] = state?.displayName;
            resourceInputs["members"] = state?.members;
            resourceInputs["name"] = state?.name;
            resourceInputs["organizationId"] = state?.organizationId;
            resourceInputs["quotaAllowance"] = state?.quotaAllowance;
        } else {
            const args = argsOrState as GroupArgs | undefined;
            resourceInputs["avatarUrl"] = args?.avatarUrl;
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["members"] = args?.members;
            resourceInputs["name"] = args?.name;
            resourceInputs["organizationId"] = args?.organizationId;
            resourceInputs["quotaAllowance"] = args?.quotaAllowance;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Group.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Group resources.
 */
export interface GroupState {
    /**
     * The URL of the group's avatar.
     */
    avatarUrl?: pulumi.Input<string | undefined>;
    /**
     * The display name of the group. Defaults to the group name.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Members of the group, by ID. If <span pulumi-lang-nodejs="`null`" pulumi-lang-dotnet="`Null`" pulumi-lang-go="`null`" pulumi-lang-python="`null`" pulumi-lang-yaml="`null`" pulumi-lang-java="`null`" pulumi-lang-hcl="`null`">`null`</span>, members will not be added or removed by Terraform. To have a group resource with unmanaged members, but be able to read the members in Terraform, use `data.coderd_group`
     */
    members?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The unique name of the group.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The organization ID that the group belongs to. Defaults to the provider default organization ID.
     */
    organizationId?: pulumi.Input<string | undefined>;
    /**
     * The number of quota credits to allocate to each user in the group.
     */
    quotaAllowance?: pulumi.Input<number | undefined>;
}

/**
 * The set of arguments for constructing a Group resource.
 */
export interface GroupArgs {
    /**
     * The URL of the group's avatar.
     */
    avatarUrl?: pulumi.Input<string | undefined>;
    /**
     * The display name of the group. Defaults to the group name.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Members of the group, by ID. If <span pulumi-lang-nodejs="`null`" pulumi-lang-dotnet="`Null`" pulumi-lang-go="`null`" pulumi-lang-python="`null`" pulumi-lang-yaml="`null`" pulumi-lang-java="`null`" pulumi-lang-hcl="`null`">`null`</span>, members will not be added or removed by Terraform. To have a group resource with unmanaged members, but be able to read the members in Terraform, use `data.coderd_group`
     */
    members?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The unique name of the group.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The organization ID that the group belongs to. Defaults to the provider default organization ID.
     */
    organizationId?: pulumi.Input<string | undefined>;
    /**
     * The number of quota credits to allocate to each user in the group.
     */
    quotaAllowance?: pulumi.Input<number | undefined>;
}
