// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { AgentsModelArgs, AgentsModelState } from "./agentsModel";
export type AgentsModel = import("./agentsModel").AgentsModel;
export const AgentsModel: typeof import("./agentsModel").AgentsModel = null as any;
utilities.lazyLoad(exports, ["AgentsModel"], () => require("./agentsModel"));

export { AiProviderArgs, AiProviderState } from "./aiProvider";
export type AiProvider = import("./aiProvider").AiProvider;
export const AiProvider: typeof import("./aiProvider").AiProvider = null as any;
utilities.lazyLoad(exports, ["AiProvider"], () => require("./aiProvider"));

export { DefaultAgentsModelArgs, DefaultAgentsModelState } from "./defaultAgentsModel";
export type DefaultAgentsModel = import("./defaultAgentsModel").DefaultAgentsModel;
export const DefaultAgentsModel: typeof import("./defaultAgentsModel").DefaultAgentsModel = null as any;
utilities.lazyLoad(exports, ["DefaultAgentsModel"], () => require("./defaultAgentsModel"));

export { GetGroupArgs, GetGroupResult, GetGroupOutputArgs } from "./getGroup";
export const getGroup: typeof import("./getGroup").getGroup = null as any;
export const getGroupOutput: typeof import("./getGroup").getGroupOutput = null as any;
utilities.lazyLoad(exports, ["getGroup","getGroupOutput"], () => require("./getGroup"));

export { GetOrganizationArgs, GetOrganizationResult, GetOrganizationOutputArgs } from "./getOrganization";
export const getOrganization: typeof import("./getOrganization").getOrganization = null as any;
export const getOrganizationOutput: typeof import("./getOrganization").getOrganizationOutput = null as any;
utilities.lazyLoad(exports, ["getOrganization","getOrganizationOutput"], () => require("./getOrganization"));

export { GetTemplateArgs, GetTemplateResult, GetTemplateOutputArgs } from "./getTemplate";
export const getTemplate: typeof import("./getTemplate").getTemplate = null as any;
export const getTemplateOutput: typeof import("./getTemplate").getTemplateOutput = null as any;
utilities.lazyLoad(exports, ["getTemplate","getTemplateOutput"], () => require("./getTemplate"));

export { GetUserArgs, GetUserResult, GetUserOutputArgs } from "./getUser";
export const getUser: typeof import("./getUser").getUser = null as any;
export const getUserOutput: typeof import("./getUser").getUserOutput = null as any;
utilities.lazyLoad(exports, ["getUser","getUserOutput"], () => require("./getUser"));

export { GroupArgs, GroupState } from "./group";
export type Group = import("./group").Group;
export const Group: typeof import("./group").Group = null as any;
utilities.lazyLoad(exports, ["Group"], () => require("./group"));

export { LicenseArgs, LicenseState } from "./license";
export type License = import("./license").License;
export const License: typeof import("./license").License = null as any;
utilities.lazyLoad(exports, ["License"], () => require("./license"));

export { OrganizationArgs, OrganizationState } from "./organization";
export type Organization = import("./organization").Organization;
export const Organization: typeof import("./organization").Organization = null as any;
utilities.lazyLoad(exports, ["Organization"], () => require("./organization"));

export { OrganizationGroupSyncArgs, OrganizationGroupSyncState } from "./organizationGroupSync";
export type OrganizationGroupSync = import("./organizationGroupSync").OrganizationGroupSync;
export const OrganizationGroupSync: typeof import("./organizationGroupSync").OrganizationGroupSync = null as any;
utilities.lazyLoad(exports, ["OrganizationGroupSync"], () => require("./organizationGroupSync"));

export { OrganizationSyncSettingsArgs, OrganizationSyncSettingsState } from "./organizationSyncSettings";
export type OrganizationSyncSettings = import("./organizationSyncSettings").OrganizationSyncSettings;
export const OrganizationSyncSettings: typeof import("./organizationSyncSettings").OrganizationSyncSettings = null as any;
utilities.lazyLoad(exports, ["OrganizationSyncSettings"], () => require("./organizationSyncSettings"));

export * from "./provider";
import { Provider } from "./provider";

export { ProvisionerKeyArgs, ProvisionerKeyState } from "./provisionerKey";
export type ProvisionerKey = import("./provisionerKey").ProvisionerKey;
export const ProvisionerKey: typeof import("./provisionerKey").ProvisionerKey = null as any;
utilities.lazyLoad(exports, ["ProvisionerKey"], () => require("./provisionerKey"));

export { TemplateArgs, TemplateState } from "./template";
export type Template = import("./template").Template;
export const Template: typeof import("./template").Template = null as any;
utilities.lazyLoad(exports, ["Template"], () => require("./template"));

export { UserArgs, UserState } from "./user";
export type User = import("./user").User;
export const User: typeof import("./user").User = null as any;
utilities.lazyLoad(exports, ["User"], () => require("./user"));

export { WorkspaceProxyArgs, WorkspaceProxyState } from "./workspaceProxy";
export type WorkspaceProxy = import("./workspaceProxy").WorkspaceProxy;
export const WorkspaceProxy: typeof import("./workspaceProxy").WorkspaceProxy = null as any;
utilities.lazyLoad(exports, ["WorkspaceProxy"], () => require("./workspaceProxy"));


// Export sub-modules:
import * as config from "./config";
import * as types from "./types";

export {
    config,
    types,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "coderd:index/agentsModel:AgentsModel":
                return new AgentsModel(name, <any>undefined, { urn })
            case "coderd:index/aiProvider:AiProvider":
                return new AiProvider(name, <any>undefined, { urn })
            case "coderd:index/defaultAgentsModel:DefaultAgentsModel":
                return new DefaultAgentsModel(name, <any>undefined, { urn })
            case "coderd:index/group:Group":
                return new Group(name, <any>undefined, { urn })
            case "coderd:index/license:License":
                return new License(name, <any>undefined, { urn })
            case "coderd:index/organization:Organization":
                return new Organization(name, <any>undefined, { urn })
            case "coderd:index/organizationGroupSync:OrganizationGroupSync":
                return new OrganizationGroupSync(name, <any>undefined, { urn })
            case "coderd:index/organizationSyncSettings:OrganizationSyncSettings":
                return new OrganizationSyncSettings(name, <any>undefined, { urn })
            case "coderd:index/provisionerKey:ProvisionerKey":
                return new ProvisionerKey(name, <any>undefined, { urn })
            case "coderd:index/template:Template":
                return new Template(name, <any>undefined, { urn })
            case "coderd:index/user:User":
                return new User(name, <any>undefined, { urn })
            case "coderd:index/workspaceProxy:WorkspaceProxy":
                return new WorkspaceProxy(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("coderd", "index/agentsModel", _module)
pulumi.runtime.registerResourceModule("coderd", "index/aiProvider", _module)
pulumi.runtime.registerResourceModule("coderd", "index/defaultAgentsModel", _module)
pulumi.runtime.registerResourceModule("coderd", "index/group", _module)
pulumi.runtime.registerResourceModule("coderd", "index/license", _module)
pulumi.runtime.registerResourceModule("coderd", "index/organization", _module)
pulumi.runtime.registerResourceModule("coderd", "index/organizationGroupSync", _module)
pulumi.runtime.registerResourceModule("coderd", "index/organizationSyncSettings", _module)
pulumi.runtime.registerResourceModule("coderd", "index/provisionerKey", _module)
pulumi.runtime.registerResourceModule("coderd", "index/template", _module)
pulumi.runtime.registerResourceModule("coderd", "index/user", _module)
pulumi.runtime.registerResourceModule("coderd", "index/workspaceProxy", _module)
pulumi.runtime.registerResourcePackage("coderd", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:coderd") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
