// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class License extends pulumi.CustomResource {
    /**
     * Get an existing License resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: LicenseState, opts?: pulumi.CustomResourceOptions): License {
        return new License(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'coderd:index/license:License';

    /**
     * Returns true if the given object is an instance of License.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is License {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === License.__pulumiType;
    }

    /**
     * Unix timestamp of when the license expires.
     */
    declare public /*out*/ readonly expiresAt: pulumi.Output<number>;
    /**
     * A license key for Coder.
     */
    declare public readonly license: pulumi.Output<string>;
    /**
     * Integer ID of the license.
     */
    declare public /*out*/ readonly licenseId: pulumi.Output<number>;

    /**
     * Create a License resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: LicenseArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: LicenseArgs | LicenseState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as LicenseState | undefined;
            resourceInputs["expiresAt"] = state?.expiresAt;
            resourceInputs["license"] = state?.license;
            resourceInputs["licenseId"] = state?.licenseId;
        } else {
            const args = argsOrState as LicenseArgs | undefined;
            if (args?.license === undefined && !opts.urn) {
                throw new Error("Missing required property 'license'");
            }
            resourceInputs["license"] = args?.license ? pulumi.secret(args.license) : undefined;
            resourceInputs["expiresAt"] = undefined /*out*/;
            resourceInputs["licenseId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["license"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(License.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering License resources.
 */
export interface LicenseState {
    /**
     * Unix timestamp of when the license expires.
     */
    expiresAt?: pulumi.Input<number | undefined>;
    /**
     * A license key for Coder.
     */
    license?: pulumi.Input<string | undefined>;
    /**
     * Integer ID of the license.
     */
    licenseId?: pulumi.Input<number | undefined>;
}

/**
 * The set of arguments for constructing a License resource.
 */
export interface LicenseArgs {
    /**
     * A license key for Coder.
     */
    license: pulumi.Input<string>;
}
