// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Oauth2ProviderSettings extends pulumi.CustomResource {
    /**
     * Get an existing Oauth2ProviderSettings resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: Oauth2ProviderSettingsState, opts?: pulumi.CustomResourceOptions): Oauth2ProviderSettings {
        return new Oauth2ProviderSettings(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'coderd:index/oauth2ProviderSettings:Oauth2ProviderSettings';

    /**
     * Returns true if the given object is an instance of Oauth2ProviderSettings.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Oauth2ProviderSettings {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Oauth2ProviderSettings.__pulumiType;
    }

    /**
     * Whether OAuth2 Dynamic Client Registration ([RFC 7591](https://datatracker.ietf.org/doc/html/rfc7591)) is enabled for the deployment. When disabled, `POST /oauth2/register` is rejected and the <span pulumi-lang-nodejs="`registrationEndpoint`" pulumi-lang-dotnet="`RegistrationEndpoint`" pulumi-lang-go="`registrationEndpoint`" pulumi-lang-python="`registration_endpoint`" pulumi-lang-yaml="`registrationEndpoint`" pulumi-lang-java="`registrationEndpoint`" pulumi-lang-hcl="`registration_endpoint`">`registrationEndpoint`</span> is omitted from the authorization server metadata document.
     */
    declare public readonly dynamicClientRegistrationEnabled: pulumi.Output<boolean>;

    /**
     * Create a Oauth2ProviderSettings resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: Oauth2ProviderSettingsArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: Oauth2ProviderSettingsArgs | Oauth2ProviderSettingsState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as Oauth2ProviderSettingsState | undefined;
            resourceInputs["dynamicClientRegistrationEnabled"] = state?.dynamicClientRegistrationEnabled;
        } else {
            const args = argsOrState as Oauth2ProviderSettingsArgs | undefined;
            if (args?.dynamicClientRegistrationEnabled === undefined && !opts.urn) {
                throw new Error("Missing required property 'dynamicClientRegistrationEnabled'");
            }
            resourceInputs["dynamicClientRegistrationEnabled"] = args?.dynamicClientRegistrationEnabled;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Oauth2ProviderSettings.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Oauth2ProviderSettings resources.
 */
export interface Oauth2ProviderSettingsState {
    /**
     * Whether OAuth2 Dynamic Client Registration ([RFC 7591](https://datatracker.ietf.org/doc/html/rfc7591)) is enabled for the deployment. When disabled, `POST /oauth2/register` is rejected and the <span pulumi-lang-nodejs="`registrationEndpoint`" pulumi-lang-dotnet="`RegistrationEndpoint`" pulumi-lang-go="`registrationEndpoint`" pulumi-lang-python="`registration_endpoint`" pulumi-lang-yaml="`registrationEndpoint`" pulumi-lang-java="`registrationEndpoint`" pulumi-lang-hcl="`registration_endpoint`">`registrationEndpoint`</span> is omitted from the authorization server metadata document.
     */
    dynamicClientRegistrationEnabled?: pulumi.Input<boolean | undefined>;
}

/**
 * The set of arguments for constructing a Oauth2ProviderSettings resource.
 */
export interface Oauth2ProviderSettingsArgs {
    /**
     * Whether OAuth2 Dynamic Client Registration ([RFC 7591](https://datatracker.ietf.org/doc/html/rfc7591)) is enabled for the deployment. When disabled, `POST /oauth2/register` is rejected and the <span pulumi-lang-nodejs="`registrationEndpoint`" pulumi-lang-dotnet="`RegistrationEndpoint`" pulumi-lang-go="`registrationEndpoint`" pulumi-lang-python="`registration_endpoint`" pulumi-lang-yaml="`registrationEndpoint`" pulumi-lang-java="`registrationEndpoint`" pulumi-lang-hcl="`registration_endpoint`">`registrationEndpoint`</span> is omitted from the authorization server metadata document.
     */
    dynamicClientRegistrationEnabled: pulumi.Input<boolean>;
}
