// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class OrganizationSyncSettings extends pulumi.CustomResource {
    /**
     * Get an existing OrganizationSyncSettings resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: OrganizationSyncSettingsState, opts?: pulumi.CustomResourceOptions): OrganizationSyncSettings {
        return new OrganizationSyncSettings(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'coderd:index/organizationSyncSettings:OrganizationSyncSettings';

    /**
     * Returns true if the given object is an instance of OrganizationSyncSettings.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is OrganizationSyncSettings {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === OrganizationSyncSettings.__pulumiType;
    }

    /**
     * When true, every user will be added to the default organization, regardless of claims.
     */
    declare public readonly assignDefault: pulumi.Output<boolean>;
    /**
     * The claim field that specifies what organizations a user should be in.
     */
    declare public readonly field: pulumi.Output<string>;
    /**
     * A map from OIDC group name to Coder organization ID.
     */
    declare public readonly mapping: pulumi.Output<{[key: string]: string[]} | undefined>;

    /**
     * Create a OrganizationSyncSettings resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: OrganizationSyncSettingsArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: OrganizationSyncSettingsArgs | OrganizationSyncSettingsState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as OrganizationSyncSettingsState | undefined;
            resourceInputs["assignDefault"] = state?.assignDefault;
            resourceInputs["field"] = state?.field;
            resourceInputs["mapping"] = state?.mapping;
        } else {
            const args = argsOrState as OrganizationSyncSettingsArgs | undefined;
            if (args?.assignDefault === undefined && !opts.urn) {
                throw new Error("Missing required property 'assignDefault'");
            }
            if (args?.field === undefined && !opts.urn) {
                throw new Error("Missing required property 'field'");
            }
            resourceInputs["assignDefault"] = args?.assignDefault;
            resourceInputs["field"] = args?.field;
            resourceInputs["mapping"] = args?.mapping;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(OrganizationSyncSettings.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering OrganizationSyncSettings resources.
 */
export interface OrganizationSyncSettingsState {
    /**
     * When true, every user will be added to the default organization, regardless of claims.
     */
    assignDefault?: pulumi.Input<boolean | undefined>;
    /**
     * The claim field that specifies what organizations a user should be in.
     */
    field?: pulumi.Input<string | undefined>;
    /**
     * A map from OIDC group name to Coder organization ID.
     */
    mapping?: pulumi.Input<{[key: string]: pulumi.Input<pulumi.Input<string>[]>} | undefined>;
}

/**
 * The set of arguments for constructing a OrganizationSyncSettings resource.
 */
export interface OrganizationSyncSettingsArgs {
    /**
     * When true, every user will be added to the default organization, regardless of claims.
     */
    assignDefault: pulumi.Input<boolean>;
    /**
     * The claim field that specifies what organizations a user should be in.
     */
    field: pulumi.Input<string>;
    /**
     * A map from OIDC group name to Coder organization ID.
     */
    mapping?: pulumi.Input<{[key: string]: pulumi.Input<pulumi.Input<string>[]>} | undefined>;
}
