// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class OrganizationGroupSync extends pulumi.CustomResource {
    /**
     * Get an existing OrganizationGroupSync resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: OrganizationGroupSyncState, opts?: pulumi.CustomResourceOptions): OrganizationGroupSync {
        return new OrganizationGroupSync(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'coderd:index/organizationGroupSync:OrganizationGroupSync';

    /**
     * Returns true if the given object is an instance of OrganizationGroupSync.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is OrganizationGroupSync {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === OrganizationGroupSync.__pulumiType;
    }

    /**
     * Controls whether groups will be created if they are missing. Defaults to false.
     */
    declare public readonly autoCreateMissing: pulumi.Output<boolean>;
    /**
     * The claim field that specifies what groups a user should be in.
     */
    declare public readonly field: pulumi.Output<string>;
    /**
     * A map from OIDC group name to Coder group ID.
     */
    declare public readonly mapping: pulumi.Output<{[key: string]: string[]}>;
    /**
     * The ID of the organization to configure group sync for.
     */
    declare public readonly organizationId: pulumi.Output<string>;
    /**
     * A regular expression that will be used to filter the groups returned by the OIDC provider. Any group not matched will be ignored.
     */
    declare public readonly regexFilter: pulumi.Output<string | undefined>;

    /**
     * Create a OrganizationGroupSync resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: OrganizationGroupSyncArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: OrganizationGroupSyncArgs | OrganizationGroupSyncState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as OrganizationGroupSyncState | undefined;
            resourceInputs["autoCreateMissing"] = state?.autoCreateMissing;
            resourceInputs["field"] = state?.field;
            resourceInputs["mapping"] = state?.mapping;
            resourceInputs["organizationId"] = state?.organizationId;
            resourceInputs["regexFilter"] = state?.regexFilter;
        } else {
            const args = argsOrState as OrganizationGroupSyncArgs | undefined;
            if (args?.field === undefined && !opts.urn) {
                throw new Error("Missing required property 'field'");
            }
            if (args?.mapping === undefined && !opts.urn) {
                throw new Error("Missing required property 'mapping'");
            }
            if (args?.organizationId === undefined && !opts.urn) {
                throw new Error("Missing required property 'organizationId'");
            }
            resourceInputs["autoCreateMissing"] = args?.autoCreateMissing;
            resourceInputs["field"] = args?.field;
            resourceInputs["mapping"] = args?.mapping;
            resourceInputs["organizationId"] = args?.organizationId;
            resourceInputs["regexFilter"] = args?.regexFilter;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(OrganizationGroupSync.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering OrganizationGroupSync resources.
 */
export interface OrganizationGroupSyncState {
    /**
     * Controls whether groups will be created if they are missing. Defaults to false.
     */
    autoCreateMissing?: pulumi.Input<boolean | undefined>;
    /**
     * The claim field that specifies what groups a user should be in.
     */
    field?: pulumi.Input<string | undefined>;
    /**
     * A map from OIDC group name to Coder group ID.
     */
    mapping?: pulumi.Input<{[key: string]: pulumi.Input<pulumi.Input<string>[]>} | undefined>;
    /**
     * The ID of the organization to configure group sync for.
     */
    organizationId?: pulumi.Input<string | undefined>;
    /**
     * A regular expression that will be used to filter the groups returned by the OIDC provider. Any group not matched will be ignored.
     */
    regexFilter?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a OrganizationGroupSync resource.
 */
export interface OrganizationGroupSyncArgs {
    /**
     * Controls whether groups will be created if they are missing. Defaults to false.
     */
    autoCreateMissing?: pulumi.Input<boolean | undefined>;
    /**
     * The claim field that specifies what groups a user should be in.
     */
    field: pulumi.Input<string>;
    /**
     * A map from OIDC group name to Coder group ID.
     */
    mapping: pulumi.Input<{[key: string]: pulumi.Input<pulumi.Input<string>[]>}>;
    /**
     * The ID of the organization to configure group sync for.
     */
    organizationId: pulumi.Input<string>;
    /**
     * A regular expression that will be used to filter the groups returned by the OIDC provider. Any group not matched will be ignored.
     */
    regexFilter?: pulumi.Input<string | undefined>;
}
