// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Organization extends pulumi.CustomResource {
    /**
     * Get an existing Organization resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: OrganizationState, opts?: pulumi.CustomResourceOptions): Organization {
        return new Organization(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'coderd:index/organization:Organization';

    /**
     * Returns true if the given object is an instance of Organization.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Organization {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Organization.__pulumiType;
    }

    declare public readonly description: pulumi.Output<string>;
    /**
     * Display name of the organization. Defaults to name.
     */
    declare public readonly displayName: pulumi.Output<string>;
    /**
     * Group sync settings to sync groups from an IdP.
     *
     * > **Deprecated** This block is deprecated. Use the <span pulumi-lang-nodejs="`coderd.OrganizationGroupSync`" pulumi-lang-dotnet="`coderd.OrganizationGroupSync`" pulumi-lang-go="`OrganizationGroupSync`" pulumi-lang-python="`OrganizationGroupSync`" pulumi-lang-yaml="`coderd.OrganizationGroupSync`" pulumi-lang-java="`coderd.OrganizationGroupSync`" pulumi-lang-hcl="`coderd_organization_group_sync`">`coderd.OrganizationGroupSync`</span> resource instead.
     *
     * @deprecated Deprecated
     */
    declare public readonly groupSync: pulumi.Output<outputs.OrganizationGroupSync | undefined>;
    declare public readonly icon: pulumi.Output<string>;
    /**
     * Name of the organization.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Claims from the IdP provider that will give users access to this organization.
     */
    declare public readonly orgSyncIdpGroups: pulumi.Output<string[] | undefined>;
    /**
     * Role sync settings to sync organization roles from an IdP.
     */
    declare public readonly roleSync: pulumi.Output<outputs.OrganizationRoleSync | undefined>;
    /**
     * Workspace sharing setting for the organization. Valid values are <span pulumi-lang-nodejs="`everyone`" pulumi-lang-dotnet="`Everyone`" pulumi-lang-go="`everyone`" pulumi-lang-python="`everyone`" pulumi-lang-yaml="`everyone`" pulumi-lang-java="`everyone`" pulumi-lang-hcl="`everyone`">`everyone`</span> and <span pulumi-lang-nodejs="`none`" pulumi-lang-dotnet="`None`" pulumi-lang-go="`none`" pulumi-lang-python="`none`" pulumi-lang-yaml="`none`" pulumi-lang-java="`none`" pulumi-lang-hcl="`none`">`none`</span>. Requires a Coder Deployment running v2.32.0 or later.
     */
    declare public readonly workspaceSharing: pulumi.Output<string>;

    /**
     * Create a Organization resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: OrganizationArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: OrganizationArgs | OrganizationState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as OrganizationState | undefined;
            resourceInputs["description"] = state?.description;
            resourceInputs["displayName"] = state?.displayName;
            resourceInputs["groupSync"] = state?.groupSync;
            resourceInputs["icon"] = state?.icon;
            resourceInputs["name"] = state?.name;
            resourceInputs["orgSyncIdpGroups"] = state?.orgSyncIdpGroups;
            resourceInputs["roleSync"] = state?.roleSync;
            resourceInputs["workspaceSharing"] = state?.workspaceSharing;
        } else {
            const args = argsOrState as OrganizationArgs | undefined;
            resourceInputs["description"] = args?.description;
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["groupSync"] = args?.groupSync;
            resourceInputs["icon"] = args?.icon;
            resourceInputs["name"] = args?.name;
            resourceInputs["orgSyncIdpGroups"] = args?.orgSyncIdpGroups;
            resourceInputs["roleSync"] = args?.roleSync;
            resourceInputs["workspaceSharing"] = args?.workspaceSharing;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Organization.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Organization resources.
 */
export interface OrganizationState {
    description?: pulumi.Input<string | undefined>;
    /**
     * Display name of the organization. Defaults to name.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Group sync settings to sync groups from an IdP.
     *
     * > **Deprecated** This block is deprecated. Use the <span pulumi-lang-nodejs="`coderd.OrganizationGroupSync`" pulumi-lang-dotnet="`coderd.OrganizationGroupSync`" pulumi-lang-go="`OrganizationGroupSync`" pulumi-lang-python="`OrganizationGroupSync`" pulumi-lang-yaml="`coderd.OrganizationGroupSync`" pulumi-lang-java="`coderd.OrganizationGroupSync`" pulumi-lang-hcl="`coderd_organization_group_sync`">`coderd.OrganizationGroupSync`</span> resource instead.
     *
     * @deprecated Deprecated
     */
    groupSync?: pulumi.Input<inputs.OrganizationGroupSync | undefined>;
    icon?: pulumi.Input<string | undefined>;
    /**
     * Name of the organization.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Claims from the IdP provider that will give users access to this organization.
     */
    orgSyncIdpGroups?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Role sync settings to sync organization roles from an IdP.
     */
    roleSync?: pulumi.Input<inputs.OrganizationRoleSync | undefined>;
    /**
     * Workspace sharing setting for the organization. Valid values are <span pulumi-lang-nodejs="`everyone`" pulumi-lang-dotnet="`Everyone`" pulumi-lang-go="`everyone`" pulumi-lang-python="`everyone`" pulumi-lang-yaml="`everyone`" pulumi-lang-java="`everyone`" pulumi-lang-hcl="`everyone`">`everyone`</span> and <span pulumi-lang-nodejs="`none`" pulumi-lang-dotnet="`None`" pulumi-lang-go="`none`" pulumi-lang-python="`none`" pulumi-lang-yaml="`none`" pulumi-lang-java="`none`" pulumi-lang-hcl="`none`">`none`</span>. Requires a Coder Deployment running v2.32.0 or later.
     */
    workspaceSharing?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Organization resource.
 */
export interface OrganizationArgs {
    description?: pulumi.Input<string | undefined>;
    /**
     * Display name of the organization. Defaults to name.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Group sync settings to sync groups from an IdP.
     *
     * > **Deprecated** This block is deprecated. Use the <span pulumi-lang-nodejs="`coderd.OrganizationGroupSync`" pulumi-lang-dotnet="`coderd.OrganizationGroupSync`" pulumi-lang-go="`OrganizationGroupSync`" pulumi-lang-python="`OrganizationGroupSync`" pulumi-lang-yaml="`coderd.OrganizationGroupSync`" pulumi-lang-java="`coderd.OrganizationGroupSync`" pulumi-lang-hcl="`coderd_organization_group_sync`">`coderd.OrganizationGroupSync`</span> resource instead.
     *
     * @deprecated Deprecated
     */
    groupSync?: pulumi.Input<inputs.OrganizationGroupSync | undefined>;
    icon?: pulumi.Input<string | undefined>;
    /**
     * Name of the organization.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Claims from the IdP provider that will give users access to this organization.
     */
    orgSyncIdpGroups?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Role sync settings to sync organization roles from an IdP.
     */
    roleSync?: pulumi.Input<inputs.OrganizationRoleSync | undefined>;
    /**
     * Workspace sharing setting for the organization. Valid values are <span pulumi-lang-nodejs="`everyone`" pulumi-lang-dotnet="`Everyone`" pulumi-lang-go="`everyone`" pulumi-lang-python="`everyone`" pulumi-lang-yaml="`everyone`" pulumi-lang-java="`everyone`" pulumi-lang-hcl="`everyone`">`everyone`</span> and <span pulumi-lang-nodejs="`none`" pulumi-lang-dotnet="`None`" pulumi-lang-go="`none`" pulumi-lang-python="`none`" pulumi-lang-yaml="`none`" pulumi-lang-java="`none`" pulumi-lang-hcl="`none`">`none`</span>. Requires a Coder Deployment running v2.32.0 or later.
     */
    workspaceSharing?: pulumi.Input<string | undefined>;
}
