// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class ProvisionerKey extends pulumi.CustomResource {
    /**
     * Get an existing ProvisionerKey resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ProvisionerKeyState, opts?: pulumi.CustomResourceOptions): ProvisionerKey {
        return new ProvisionerKey(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'coderd:index/provisionerKey:ProvisionerKey';

    /**
     * Returns true if the given object is an instance of ProvisionerKey.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ProvisionerKey {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ProvisionerKey.__pulumiType;
    }

    /**
     * The acquired provisioner key
     */
    declare public /*out*/ readonly key: pulumi.Output<string>;
    /**
     * The name of the key.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The organization that provisioners connected with this key will be connected to.
     */
    declare public readonly organizationId: pulumi.Output<string>;
    /**
     * The tags that provisioners connected with this key will accept jobs for.
     */
    declare public readonly tags: pulumi.Output<{[key: string]: string} | undefined>;

    /**
     * Create a ProvisionerKey resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ProvisionerKeyArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ProvisionerKeyArgs | ProvisionerKeyState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ProvisionerKeyState | undefined;
            resourceInputs["key"] = state?.key;
            resourceInputs["name"] = state?.name;
            resourceInputs["organizationId"] = state?.organizationId;
            resourceInputs["tags"] = state?.tags;
        } else {
            const args = argsOrState as ProvisionerKeyArgs | undefined;
            if (args?.organizationId === undefined && !opts.urn) {
                throw new Error("Missing required property 'organizationId'");
            }
            resourceInputs["name"] = args?.name;
            resourceInputs["organizationId"] = args?.organizationId;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["key"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["key"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(ProvisionerKey.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering ProvisionerKey resources.
 */
export interface ProvisionerKeyState {
    /**
     * The acquired provisioner key
     */
    key?: pulumi.Input<string | undefined>;
    /**
     * The name of the key.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The organization that provisioners connected with this key will be connected to.
     */
    organizationId?: pulumi.Input<string | undefined>;
    /**
     * The tags that provisioners connected with this key will accept jobs for.
     */
    tags?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
}

/**
 * The set of arguments for constructing a ProvisionerKey resource.
 */
export interface ProvisionerKeyArgs {
    /**
     * The name of the key.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The organization that provisioners connected with this key will be connected to.
     */
    organizationId: pulumi.Input<string>;
    /**
     * The tags that provisioners connected with this key will accept jobs for.
     */
    tags?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
}
