// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Template extends pulumi.CustomResource {
    /**
     * Get an existing Template resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: TemplateState, opts?: pulumi.CustomResourceOptions): Template {
        return new Template(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'coderd:index/template:Template';

    /**
     * Returns true if the given object is an instance of Template.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Template {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Template.__pulumiType;
    }

    /**
     * (Enterprise) Access control list for the template. If null, ACL policies will not be added, removed, or read by Terraform.
     */
    declare public readonly acl: pulumi.Output<outputs.TemplateAcl | undefined>;
    /**
     * The activity bump duration for all workspaces created from this template, in milliseconds. Defaults to one hour.
     */
    declare public readonly activityBumpMs: pulumi.Output<number>;
    /**
     * (Enterprise) Whether users can auto-start workspaces created from this template. Defaults to true.
     */
    declare public readonly allowUserAutoStart: pulumi.Output<boolean>;
    /**
     * (Enterprise) Whether users can auto-stop workspaces created from this template. Defaults to true.
     */
    declare public readonly allowUserAutoStop: pulumi.Output<boolean>;
    /**
     * Whether users can cancel in-progress workspace jobs using this template. Defaults to true.
     */
    declare public readonly allowUserCancelWorkspaceJobs: pulumi.Output<boolean>;
    /**
     * (Enterprise) List of days of the week in which autostart is allowed to happen, for all workspaces created from this template. Defaults to all days. If no days are specified, autostart is not allowed.
     */
    declare public readonly autoStartPermittedDaysOfWeeks: pulumi.Output<string[]>;
    /**
     * (Enterprise) The auto-stop requirement for all workspaces created from this template.
     */
    declare public readonly autoStopRequirement: pulumi.Output<outputs.TemplateAutoStopRequirement>;
    /**
     * The CORS behavior for workspace apps in this template. Valid values are <span pulumi-lang-nodejs="`simple`" pulumi-lang-dotnet="`Simple`" pulumi-lang-go="`simple`" pulumi-lang-python="`simple`" pulumi-lang-yaml="`simple`" pulumi-lang-java="`simple`" pulumi-lang-hcl="`simple`">`simple`</span> (default CORS middleware) or <span pulumi-lang-nodejs="`passthru`" pulumi-lang-dotnet="`Passthru`" pulumi-lang-go="`passthru`" pulumi-lang-python="`passthru`" pulumi-lang-yaml="`passthru`" pulumi-lang-java="`passthru`" pulumi-lang-hcl="`passthru`">`passthru`</span> (bypass CORS middleware). Defaults to <span pulumi-lang-nodejs="`simple`" pulumi-lang-dotnet="`Simple`" pulumi-lang-go="`simple`" pulumi-lang-python="`simple`" pulumi-lang-yaml="`simple`" pulumi-lang-java="`simple`" pulumi-lang-hcl="`simple`">`simple`</span>. Requires a Coder deployment running v2.26.0 or later.
     */
    declare public readonly corsBehavior: pulumi.Output<string>;
    /**
     * The default time-to-live for all workspaces created from this template, in milliseconds.
     */
    declare public readonly defaultTtlMs: pulumi.Output<number>;
    /**
     * If set, the template will be marked as deprecated with the provided message and users will be blocked from creating new workspaces from it. Does nothing if set when the resource is created.
     */
    declare public readonly deprecationMessage: pulumi.Output<string>;
    /**
     * A description of the template.
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * The display name of the template. Defaults to the template name.
     */
    declare public readonly displayName: pulumi.Output<string>;
    /**
     * (Enterprise) The max lifetime before Coder stops all resources for failed workspaces created from this template, in milliseconds.
     */
    declare public readonly failureTtlMs: pulumi.Output<number>;
    /**
     * Relative path or external URL that specifies an icon to be displayed in the dashboard.
     */
    declare public readonly icon: pulumi.Output<string>;
    /**
     * (Enterprise) The maximum port share level for workspaces created from this template. Defaults to <span pulumi-lang-nodejs="`owner`" pulumi-lang-dotnet="`Owner`" pulumi-lang-go="`owner`" pulumi-lang-python="`owner`" pulumi-lang-yaml="`owner`" pulumi-lang-java="`owner`" pulumi-lang-hcl="`owner`">`owner`</span> on an Enterprise deployment, or <span pulumi-lang-nodejs="`public`" pulumi-lang-dotnet="`Public`" pulumi-lang-go="`public`" pulumi-lang-python="`public`" pulumi-lang-yaml="`public`" pulumi-lang-java="`public`" pulumi-lang-hcl="`public`">`public`</span> otherwise.
     */
    declare public readonly maxPortShareLevel: pulumi.Output<string>;
    /**
     * The name of the template.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The ID of the organization. Defaults to the provider's default organization
     */
    declare public readonly organizationId: pulumi.Output<string>;
    /**
     * (Enterprise) Whether workspaces must be created from the active version of this template. Defaults to false.
     */
    declare public readonly requireActiveVersion: pulumi.Output<boolean>;
    /**
     * (Enterprise) The max lifetime before Coder permanently deletes dormant workspaces created from this template.
     */
    declare public readonly timeTilDormantAutodeleteMs: pulumi.Output<number>;
    /**
     * (Enterprise) The max lifetime before Coder locks inactive workspaces created from this template, in milliseconds.
     */
    declare public readonly timeTilDormantMs: pulumi.Output<number>;
    /**
     * If true, the classic parameter flow will be used when creating workspaces from this template. Defaults to false.
     */
    declare public readonly useClassicParameterFlow: pulumi.Output<boolean>;
    /**
     * The template versions to manage. If null, Terraform will not create, update, or read template versions, and will only manage the template's other settings. At least one version (with `active = true`) is required when creating a new template, since Coder templates cannot exist without a version.
     */
    declare public readonly versions: pulumi.Output<outputs.TemplateVersion[] | undefined>;

    /**
     * Create a Template resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: TemplateArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: TemplateArgs | TemplateState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as TemplateState | undefined;
            resourceInputs["acl"] = state?.acl;
            resourceInputs["activityBumpMs"] = state?.activityBumpMs;
            resourceInputs["allowUserAutoStart"] = state?.allowUserAutoStart;
            resourceInputs["allowUserAutoStop"] = state?.allowUserAutoStop;
            resourceInputs["allowUserCancelWorkspaceJobs"] = state?.allowUserCancelWorkspaceJobs;
            resourceInputs["autoStartPermittedDaysOfWeeks"] = state?.autoStartPermittedDaysOfWeeks;
            resourceInputs["autoStopRequirement"] = state?.autoStopRequirement;
            resourceInputs["corsBehavior"] = state?.corsBehavior;
            resourceInputs["defaultTtlMs"] = state?.defaultTtlMs;
            resourceInputs["deprecationMessage"] = state?.deprecationMessage;
            resourceInputs["description"] = state?.description;
            resourceInputs["displayName"] = state?.displayName;
            resourceInputs["failureTtlMs"] = state?.failureTtlMs;
            resourceInputs["icon"] = state?.icon;
            resourceInputs["maxPortShareLevel"] = state?.maxPortShareLevel;
            resourceInputs["name"] = state?.name;
            resourceInputs["organizationId"] = state?.organizationId;
            resourceInputs["requireActiveVersion"] = state?.requireActiveVersion;
            resourceInputs["timeTilDormantAutodeleteMs"] = state?.timeTilDormantAutodeleteMs;
            resourceInputs["timeTilDormantMs"] = state?.timeTilDormantMs;
            resourceInputs["useClassicParameterFlow"] = state?.useClassicParameterFlow;
            resourceInputs["versions"] = state?.versions;
        } else {
            const args = argsOrState as TemplateArgs | undefined;
            resourceInputs["acl"] = args?.acl;
            resourceInputs["activityBumpMs"] = args?.activityBumpMs;
            resourceInputs["allowUserAutoStart"] = args?.allowUserAutoStart;
            resourceInputs["allowUserAutoStop"] = args?.allowUserAutoStop;
            resourceInputs["allowUserCancelWorkspaceJobs"] = args?.allowUserCancelWorkspaceJobs;
            resourceInputs["autoStartPermittedDaysOfWeeks"] = args?.autoStartPermittedDaysOfWeeks;
            resourceInputs["autoStopRequirement"] = args?.autoStopRequirement;
            resourceInputs["corsBehavior"] = args?.corsBehavior;
            resourceInputs["defaultTtlMs"] = args?.defaultTtlMs;
            resourceInputs["deprecationMessage"] = args?.deprecationMessage;
            resourceInputs["description"] = args?.description;
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["failureTtlMs"] = args?.failureTtlMs;
            resourceInputs["icon"] = args?.icon;
            resourceInputs["maxPortShareLevel"] = args?.maxPortShareLevel;
            resourceInputs["name"] = args?.name;
            resourceInputs["organizationId"] = args?.organizationId;
            resourceInputs["requireActiveVersion"] = args?.requireActiveVersion;
            resourceInputs["timeTilDormantAutodeleteMs"] = args?.timeTilDormantAutodeleteMs;
            resourceInputs["timeTilDormantMs"] = args?.timeTilDormantMs;
            resourceInputs["useClassicParameterFlow"] = args?.useClassicParameterFlow;
            resourceInputs["versions"] = args?.versions;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Template.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Template resources.
 */
export interface TemplateState {
    /**
     * (Enterprise) Access control list for the template. If null, ACL policies will not be added, removed, or read by Terraform.
     */
    acl?: pulumi.Input<inputs.TemplateAcl | undefined>;
    /**
     * The activity bump duration for all workspaces created from this template, in milliseconds. Defaults to one hour.
     */
    activityBumpMs?: pulumi.Input<number | undefined>;
    /**
     * (Enterprise) Whether users can auto-start workspaces created from this template. Defaults to true.
     */
    allowUserAutoStart?: pulumi.Input<boolean | undefined>;
    /**
     * (Enterprise) Whether users can auto-stop workspaces created from this template. Defaults to true.
     */
    allowUserAutoStop?: pulumi.Input<boolean | undefined>;
    /**
     * Whether users can cancel in-progress workspace jobs using this template. Defaults to true.
     */
    allowUserCancelWorkspaceJobs?: pulumi.Input<boolean | undefined>;
    /**
     * (Enterprise) List of days of the week in which autostart is allowed to happen, for all workspaces created from this template. Defaults to all days. If no days are specified, autostart is not allowed.
     */
    autoStartPermittedDaysOfWeeks?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * (Enterprise) The auto-stop requirement for all workspaces created from this template.
     */
    autoStopRequirement?: pulumi.Input<inputs.TemplateAutoStopRequirement | undefined>;
    /**
     * The CORS behavior for workspace apps in this template. Valid values are <span pulumi-lang-nodejs="`simple`" pulumi-lang-dotnet="`Simple`" pulumi-lang-go="`simple`" pulumi-lang-python="`simple`" pulumi-lang-yaml="`simple`" pulumi-lang-java="`simple`" pulumi-lang-hcl="`simple`">`simple`</span> (default CORS middleware) or <span pulumi-lang-nodejs="`passthru`" pulumi-lang-dotnet="`Passthru`" pulumi-lang-go="`passthru`" pulumi-lang-python="`passthru`" pulumi-lang-yaml="`passthru`" pulumi-lang-java="`passthru`" pulumi-lang-hcl="`passthru`">`passthru`</span> (bypass CORS middleware). Defaults to <span pulumi-lang-nodejs="`simple`" pulumi-lang-dotnet="`Simple`" pulumi-lang-go="`simple`" pulumi-lang-python="`simple`" pulumi-lang-yaml="`simple`" pulumi-lang-java="`simple`" pulumi-lang-hcl="`simple`">`simple`</span>. Requires a Coder deployment running v2.26.0 or later.
     */
    corsBehavior?: pulumi.Input<string | undefined>;
    /**
     * The default time-to-live for all workspaces created from this template, in milliseconds.
     */
    defaultTtlMs?: pulumi.Input<number | undefined>;
    /**
     * If set, the template will be marked as deprecated with the provided message and users will be blocked from creating new workspaces from it. Does nothing if set when the resource is created.
     */
    deprecationMessage?: pulumi.Input<string | undefined>;
    /**
     * A description of the template.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * The display name of the template. Defaults to the template name.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * (Enterprise) The max lifetime before Coder stops all resources for failed workspaces created from this template, in milliseconds.
     */
    failureTtlMs?: pulumi.Input<number | undefined>;
    /**
     * Relative path or external URL that specifies an icon to be displayed in the dashboard.
     */
    icon?: pulumi.Input<string | undefined>;
    /**
     * (Enterprise) The maximum port share level for workspaces created from this template. Defaults to <span pulumi-lang-nodejs="`owner`" pulumi-lang-dotnet="`Owner`" pulumi-lang-go="`owner`" pulumi-lang-python="`owner`" pulumi-lang-yaml="`owner`" pulumi-lang-java="`owner`" pulumi-lang-hcl="`owner`">`owner`</span> on an Enterprise deployment, or <span pulumi-lang-nodejs="`public`" pulumi-lang-dotnet="`Public`" pulumi-lang-go="`public`" pulumi-lang-python="`public`" pulumi-lang-yaml="`public`" pulumi-lang-java="`public`" pulumi-lang-hcl="`public`">`public`</span> otherwise.
     */
    maxPortShareLevel?: pulumi.Input<string | undefined>;
    /**
     * The name of the template.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The ID of the organization. Defaults to the provider's default organization
     */
    organizationId?: pulumi.Input<string | undefined>;
    /**
     * (Enterprise) Whether workspaces must be created from the active version of this template. Defaults to false.
     */
    requireActiveVersion?: pulumi.Input<boolean | undefined>;
    /**
     * (Enterprise) The max lifetime before Coder permanently deletes dormant workspaces created from this template.
     */
    timeTilDormantAutodeleteMs?: pulumi.Input<number | undefined>;
    /**
     * (Enterprise) The max lifetime before Coder locks inactive workspaces created from this template, in milliseconds.
     */
    timeTilDormantMs?: pulumi.Input<number | undefined>;
    /**
     * If true, the classic parameter flow will be used when creating workspaces from this template. Defaults to false.
     */
    useClassicParameterFlow?: pulumi.Input<boolean | undefined>;
    /**
     * The template versions to manage. If null, Terraform will not create, update, or read template versions, and will only manage the template's other settings. At least one version (with `active = true`) is required when creating a new template, since Coder templates cannot exist without a version.
     */
    versions?: pulumi.Input<pulumi.Input<inputs.TemplateVersion>[] | undefined>;
}

/**
 * The set of arguments for constructing a Template resource.
 */
export interface TemplateArgs {
    /**
     * (Enterprise) Access control list for the template. If null, ACL policies will not be added, removed, or read by Terraform.
     */
    acl?: pulumi.Input<inputs.TemplateAcl | undefined>;
    /**
     * The activity bump duration for all workspaces created from this template, in milliseconds. Defaults to one hour.
     */
    activityBumpMs?: pulumi.Input<number | undefined>;
    /**
     * (Enterprise) Whether users can auto-start workspaces created from this template. Defaults to true.
     */
    allowUserAutoStart?: pulumi.Input<boolean | undefined>;
    /**
     * (Enterprise) Whether users can auto-stop workspaces created from this template. Defaults to true.
     */
    allowUserAutoStop?: pulumi.Input<boolean | undefined>;
    /**
     * Whether users can cancel in-progress workspace jobs using this template. Defaults to true.
     */
    allowUserCancelWorkspaceJobs?: pulumi.Input<boolean | undefined>;
    /**
     * (Enterprise) List of days of the week in which autostart is allowed to happen, for all workspaces created from this template. Defaults to all days. If no days are specified, autostart is not allowed.
     */
    autoStartPermittedDaysOfWeeks?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * (Enterprise) The auto-stop requirement for all workspaces created from this template.
     */
    autoStopRequirement?: pulumi.Input<inputs.TemplateAutoStopRequirement | undefined>;
    /**
     * The CORS behavior for workspace apps in this template. Valid values are <span pulumi-lang-nodejs="`simple`" pulumi-lang-dotnet="`Simple`" pulumi-lang-go="`simple`" pulumi-lang-python="`simple`" pulumi-lang-yaml="`simple`" pulumi-lang-java="`simple`" pulumi-lang-hcl="`simple`">`simple`</span> (default CORS middleware) or <span pulumi-lang-nodejs="`passthru`" pulumi-lang-dotnet="`Passthru`" pulumi-lang-go="`passthru`" pulumi-lang-python="`passthru`" pulumi-lang-yaml="`passthru`" pulumi-lang-java="`passthru`" pulumi-lang-hcl="`passthru`">`passthru`</span> (bypass CORS middleware). Defaults to <span pulumi-lang-nodejs="`simple`" pulumi-lang-dotnet="`Simple`" pulumi-lang-go="`simple`" pulumi-lang-python="`simple`" pulumi-lang-yaml="`simple`" pulumi-lang-java="`simple`" pulumi-lang-hcl="`simple`">`simple`</span>. Requires a Coder deployment running v2.26.0 or later.
     */
    corsBehavior?: pulumi.Input<string | undefined>;
    /**
     * The default time-to-live for all workspaces created from this template, in milliseconds.
     */
    defaultTtlMs?: pulumi.Input<number | undefined>;
    /**
     * If set, the template will be marked as deprecated with the provided message and users will be blocked from creating new workspaces from it. Does nothing if set when the resource is created.
     */
    deprecationMessage?: pulumi.Input<string | undefined>;
    /**
     * A description of the template.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * The display name of the template. Defaults to the template name.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * (Enterprise) The max lifetime before Coder stops all resources for failed workspaces created from this template, in milliseconds.
     */
    failureTtlMs?: pulumi.Input<number | undefined>;
    /**
     * Relative path or external URL that specifies an icon to be displayed in the dashboard.
     */
    icon?: pulumi.Input<string | undefined>;
    /**
     * (Enterprise) The maximum port share level for workspaces created from this template. Defaults to <span pulumi-lang-nodejs="`owner`" pulumi-lang-dotnet="`Owner`" pulumi-lang-go="`owner`" pulumi-lang-python="`owner`" pulumi-lang-yaml="`owner`" pulumi-lang-java="`owner`" pulumi-lang-hcl="`owner`">`owner`</span> on an Enterprise deployment, or <span pulumi-lang-nodejs="`public`" pulumi-lang-dotnet="`Public`" pulumi-lang-go="`public`" pulumi-lang-python="`public`" pulumi-lang-yaml="`public`" pulumi-lang-java="`public`" pulumi-lang-hcl="`public`">`public`</span> otherwise.
     */
    maxPortShareLevel?: pulumi.Input<string | undefined>;
    /**
     * The name of the template.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The ID of the organization. Defaults to the provider's default organization
     */
    organizationId?: pulumi.Input<string | undefined>;
    /**
     * (Enterprise) Whether workspaces must be created from the active version of this template. Defaults to false.
     */
    requireActiveVersion?: pulumi.Input<boolean | undefined>;
    /**
     * (Enterprise) The max lifetime before Coder permanently deletes dormant workspaces created from this template.
     */
    timeTilDormantAutodeleteMs?: pulumi.Input<number | undefined>;
    /**
     * (Enterprise) The max lifetime before Coder locks inactive workspaces created from this template, in milliseconds.
     */
    timeTilDormantMs?: pulumi.Input<number | undefined>;
    /**
     * If true, the classic parameter flow will be used when creating workspaces from this template. Defaults to false.
     */
    useClassicParameterFlow?: pulumi.Input<boolean | undefined>;
    /**
     * The template versions to manage. If null, Terraform will not create, update, or read template versions, and will only manage the template's other settings. At least one version (with `active = true`) is required when creating a new template, since Coder templates cannot exist without a version.
     */
    versions?: pulumi.Input<pulumi.Input<inputs.TemplateVersion>[] | undefined>;
}
