// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class User extends pulumi.CustomResource {
    /**
     * Get an existing User resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: UserState, opts?: pulumi.CustomResourceOptions): User {
        return new User(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'coderd:index/user:User';

    /**
     * Returns true if the given object is an instance of User.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is User {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === User.__pulumiType;
    }

    /**
     * Email address of the user. Required unless <span pulumi-lang-nodejs="`isServiceAccount`" pulumi-lang-dotnet="`IsServiceAccount`" pulumi-lang-go="`isServiceAccount`" pulumi-lang-python="`is_service_account`" pulumi-lang-yaml="`isServiceAccount`" pulumi-lang-java="`isServiceAccount`" pulumi-lang-hcl="`is_service_account`">`isServiceAccount`</span> is <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>, in which case it must be omitted (service accounts have no email).
     */
    declare public readonly email: pulumi.Output<string>;
    /**
     * Whether the user is a service account. Service accounts are admin-managed accounts that cannot log in interactively: they have no password or email and use <span pulumi-lang-nodejs="`loginType`" pulumi-lang-dotnet="`LoginType`" pulumi-lang-go="`loginType`" pulumi-lang-python="`login_type`" pulumi-lang-yaml="`loginType`" pulumi-lang-java="`loginType`" pulumi-lang-hcl="`login_type`">`loginType`</span> <span pulumi-lang-nodejs="`none`" pulumi-lang-dotnet="`None`" pulumi-lang-go="`none`" pulumi-lang-python="`none`" pulumi-lang-yaml="`none`" pulumi-lang-java="`none`" pulumi-lang-hcl="`none`">`none`</span>. Unlike a regular <span pulumi-lang-nodejs="`loginType " pulumi-lang-dotnet="`LoginType " pulumi-lang-go="`loginType " pulumi-lang-python="`login_type " pulumi-lang-yaml="`loginType " pulumi-lang-java="`loginType " pulumi-lang-hcl="`login_type ">`loginType </span>= none` user, a service account does not consume a licensed user seat. Changing this attribute forces replacement.
     */
    declare public readonly isServiceAccount: pulumi.Output<boolean>;
    /**
     * Type of login for the user. Valid types are <span pulumi-lang-nodejs="`none`" pulumi-lang-dotnet="`None`" pulumi-lang-go="`none`" pulumi-lang-python="`none`" pulumi-lang-yaml="`none`" pulumi-lang-java="`none`" pulumi-lang-hcl="`none`">`none`</span>, <span pulumi-lang-nodejs="`password`" pulumi-lang-dotnet="`Password`" pulumi-lang-go="`password`" pulumi-lang-python="`password`" pulumi-lang-yaml="`password`" pulumi-lang-java="`password`" pulumi-lang-hcl="`password`">`password`</span>, <span pulumi-lang-nodejs="`github`" pulumi-lang-dotnet="`Github`" pulumi-lang-go="`github`" pulumi-lang-python="`github`" pulumi-lang-yaml="`github`" pulumi-lang-java="`github`" pulumi-lang-hcl="`github`">`github`</span>, and <span pulumi-lang-nodejs="`oidc`" pulumi-lang-dotnet="`Oidc`" pulumi-lang-go="`oidc`" pulumi-lang-python="`oidc`" pulumi-lang-yaml="`oidc`" pulumi-lang-java="`oidc`" pulumi-lang-hcl="`oidc`">`oidc`</span>.
     */
    declare public readonly loginType: pulumi.Output<string>;
    /**
     * Display name of the user. Defaults to username.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Password for the user. Required when <span pulumi-lang-nodejs="`loginType`" pulumi-lang-dotnet="`LoginType`" pulumi-lang-go="`loginType`" pulumi-lang-python="`login_type`" pulumi-lang-yaml="`loginType`" pulumi-lang-java="`loginType`" pulumi-lang-hcl="`login_type`">`loginType`</span> is <span pulumi-lang-nodejs="`password`" pulumi-lang-dotnet="`Password`" pulumi-lang-go="`password`" pulumi-lang-python="`password`" pulumi-lang-yaml="`password`" pulumi-lang-java="`password`" pulumi-lang-hcl="`password`">`password`</span>. Passwords are saved into the state as plain text and should only be used for testing purposes.
     */
    declare public readonly password: pulumi.Output<string | undefined>;
    /**
     * Roles assigned to the user. Valid roles are <span pulumi-lang-nodejs="`owner`" pulumi-lang-dotnet="`Owner`" pulumi-lang-go="`owner`" pulumi-lang-python="`owner`" pulumi-lang-yaml="`owner`" pulumi-lang-java="`owner`" pulumi-lang-hcl="`owner`">`owner`</span>, `template-admin`, `user-admin`, and <span pulumi-lang-nodejs="`auditor`" pulumi-lang-dotnet="`Auditor`" pulumi-lang-go="`auditor`" pulumi-lang-python="`auditor`" pulumi-lang-yaml="`auditor`" pulumi-lang-java="`auditor`" pulumi-lang-hcl="`auditor`">`auditor`</span>. If <span pulumi-lang-nodejs="`null`" pulumi-lang-dotnet="`Null`" pulumi-lang-go="`null`" pulumi-lang-python="`null`" pulumi-lang-yaml="`null`" pulumi-lang-java="`null`" pulumi-lang-hcl="`null`">`null`</span>, roles will not be managed by Terraform. This attribute must be null if the user is an OIDC user and role sync is configured
     */
    declare public readonly roles: pulumi.Output<string[] | undefined>;
    /**
     * Whether the user is suspended.
     */
    declare public readonly suspended: pulumi.Output<boolean>;
    /**
     * Username of the user.
     */
    declare public readonly username: pulumi.Output<string>;

    /**
     * Create a User resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: UserArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: UserArgs | UserState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as UserState | undefined;
            resourceInputs["email"] = state?.email;
            resourceInputs["isServiceAccount"] = state?.isServiceAccount;
            resourceInputs["loginType"] = state?.loginType;
            resourceInputs["name"] = state?.name;
            resourceInputs["password"] = state?.password;
            resourceInputs["roles"] = state?.roles;
            resourceInputs["suspended"] = state?.suspended;
            resourceInputs["username"] = state?.username;
        } else {
            const args = argsOrState as UserArgs | undefined;
            if (args?.username === undefined && !opts.urn) {
                throw new Error("Missing required property 'username'");
            }
            resourceInputs["email"] = args?.email;
            resourceInputs["isServiceAccount"] = args?.isServiceAccount;
            resourceInputs["loginType"] = args?.loginType;
            resourceInputs["name"] = args?.name;
            resourceInputs["password"] = args?.password ? pulumi.secret(args.password) : undefined;
            resourceInputs["roles"] = args?.roles;
            resourceInputs["suspended"] = args?.suspended;
            resourceInputs["username"] = args?.username;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["password"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(User.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering User resources.
 */
export interface UserState {
    /**
     * Email address of the user. Required unless <span pulumi-lang-nodejs="`isServiceAccount`" pulumi-lang-dotnet="`IsServiceAccount`" pulumi-lang-go="`isServiceAccount`" pulumi-lang-python="`is_service_account`" pulumi-lang-yaml="`isServiceAccount`" pulumi-lang-java="`isServiceAccount`" pulumi-lang-hcl="`is_service_account`">`isServiceAccount`</span> is <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>, in which case it must be omitted (service accounts have no email).
     */
    email?: pulumi.Input<string | undefined>;
    /**
     * Whether the user is a service account. Service accounts are admin-managed accounts that cannot log in interactively: they have no password or email and use <span pulumi-lang-nodejs="`loginType`" pulumi-lang-dotnet="`LoginType`" pulumi-lang-go="`loginType`" pulumi-lang-python="`login_type`" pulumi-lang-yaml="`loginType`" pulumi-lang-java="`loginType`" pulumi-lang-hcl="`login_type`">`loginType`</span> <span pulumi-lang-nodejs="`none`" pulumi-lang-dotnet="`None`" pulumi-lang-go="`none`" pulumi-lang-python="`none`" pulumi-lang-yaml="`none`" pulumi-lang-java="`none`" pulumi-lang-hcl="`none`">`none`</span>. Unlike a regular <span pulumi-lang-nodejs="`loginType " pulumi-lang-dotnet="`LoginType " pulumi-lang-go="`loginType " pulumi-lang-python="`login_type " pulumi-lang-yaml="`loginType " pulumi-lang-java="`loginType " pulumi-lang-hcl="`login_type ">`loginType </span>= none` user, a service account does not consume a licensed user seat. Changing this attribute forces replacement.
     */
    isServiceAccount?: pulumi.Input<boolean | undefined>;
    /**
     * Type of login for the user. Valid types are <span pulumi-lang-nodejs="`none`" pulumi-lang-dotnet="`None`" pulumi-lang-go="`none`" pulumi-lang-python="`none`" pulumi-lang-yaml="`none`" pulumi-lang-java="`none`" pulumi-lang-hcl="`none`">`none`</span>, <span pulumi-lang-nodejs="`password`" pulumi-lang-dotnet="`Password`" pulumi-lang-go="`password`" pulumi-lang-python="`password`" pulumi-lang-yaml="`password`" pulumi-lang-java="`password`" pulumi-lang-hcl="`password`">`password`</span>, <span pulumi-lang-nodejs="`github`" pulumi-lang-dotnet="`Github`" pulumi-lang-go="`github`" pulumi-lang-python="`github`" pulumi-lang-yaml="`github`" pulumi-lang-java="`github`" pulumi-lang-hcl="`github`">`github`</span>, and <span pulumi-lang-nodejs="`oidc`" pulumi-lang-dotnet="`Oidc`" pulumi-lang-go="`oidc`" pulumi-lang-python="`oidc`" pulumi-lang-yaml="`oidc`" pulumi-lang-java="`oidc`" pulumi-lang-hcl="`oidc`">`oidc`</span>.
     */
    loginType?: pulumi.Input<string | undefined>;
    /**
     * Display name of the user. Defaults to username.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Password for the user. Required when <span pulumi-lang-nodejs="`loginType`" pulumi-lang-dotnet="`LoginType`" pulumi-lang-go="`loginType`" pulumi-lang-python="`login_type`" pulumi-lang-yaml="`loginType`" pulumi-lang-java="`loginType`" pulumi-lang-hcl="`login_type`">`loginType`</span> is <span pulumi-lang-nodejs="`password`" pulumi-lang-dotnet="`Password`" pulumi-lang-go="`password`" pulumi-lang-python="`password`" pulumi-lang-yaml="`password`" pulumi-lang-java="`password`" pulumi-lang-hcl="`password`">`password`</span>. Passwords are saved into the state as plain text and should only be used for testing purposes.
     */
    password?: pulumi.Input<string | undefined>;
    /**
     * Roles assigned to the user. Valid roles are <span pulumi-lang-nodejs="`owner`" pulumi-lang-dotnet="`Owner`" pulumi-lang-go="`owner`" pulumi-lang-python="`owner`" pulumi-lang-yaml="`owner`" pulumi-lang-java="`owner`" pulumi-lang-hcl="`owner`">`owner`</span>, `template-admin`, `user-admin`, and <span pulumi-lang-nodejs="`auditor`" pulumi-lang-dotnet="`Auditor`" pulumi-lang-go="`auditor`" pulumi-lang-python="`auditor`" pulumi-lang-yaml="`auditor`" pulumi-lang-java="`auditor`" pulumi-lang-hcl="`auditor`">`auditor`</span>. If <span pulumi-lang-nodejs="`null`" pulumi-lang-dotnet="`Null`" pulumi-lang-go="`null`" pulumi-lang-python="`null`" pulumi-lang-yaml="`null`" pulumi-lang-java="`null`" pulumi-lang-hcl="`null`">`null`</span>, roles will not be managed by Terraform. This attribute must be null if the user is an OIDC user and role sync is configured
     */
    roles?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Whether the user is suspended.
     */
    suspended?: pulumi.Input<boolean | undefined>;
    /**
     * Username of the user.
     */
    username?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a User resource.
 */
export interface UserArgs {
    /**
     * Email address of the user. Required unless <span pulumi-lang-nodejs="`isServiceAccount`" pulumi-lang-dotnet="`IsServiceAccount`" pulumi-lang-go="`isServiceAccount`" pulumi-lang-python="`is_service_account`" pulumi-lang-yaml="`isServiceAccount`" pulumi-lang-java="`isServiceAccount`" pulumi-lang-hcl="`is_service_account`">`isServiceAccount`</span> is <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>, in which case it must be omitted (service accounts have no email).
     */
    email?: pulumi.Input<string | undefined>;
    /**
     * Whether the user is a service account. Service accounts are admin-managed accounts that cannot log in interactively: they have no password or email and use <span pulumi-lang-nodejs="`loginType`" pulumi-lang-dotnet="`LoginType`" pulumi-lang-go="`loginType`" pulumi-lang-python="`login_type`" pulumi-lang-yaml="`loginType`" pulumi-lang-java="`loginType`" pulumi-lang-hcl="`login_type`">`loginType`</span> <span pulumi-lang-nodejs="`none`" pulumi-lang-dotnet="`None`" pulumi-lang-go="`none`" pulumi-lang-python="`none`" pulumi-lang-yaml="`none`" pulumi-lang-java="`none`" pulumi-lang-hcl="`none`">`none`</span>. Unlike a regular <span pulumi-lang-nodejs="`loginType " pulumi-lang-dotnet="`LoginType " pulumi-lang-go="`loginType " pulumi-lang-python="`login_type " pulumi-lang-yaml="`loginType " pulumi-lang-java="`loginType " pulumi-lang-hcl="`login_type ">`loginType </span>= none` user, a service account does not consume a licensed user seat. Changing this attribute forces replacement.
     */
    isServiceAccount?: pulumi.Input<boolean | undefined>;
    /**
     * Type of login for the user. Valid types are <span pulumi-lang-nodejs="`none`" pulumi-lang-dotnet="`None`" pulumi-lang-go="`none`" pulumi-lang-python="`none`" pulumi-lang-yaml="`none`" pulumi-lang-java="`none`" pulumi-lang-hcl="`none`">`none`</span>, <span pulumi-lang-nodejs="`password`" pulumi-lang-dotnet="`Password`" pulumi-lang-go="`password`" pulumi-lang-python="`password`" pulumi-lang-yaml="`password`" pulumi-lang-java="`password`" pulumi-lang-hcl="`password`">`password`</span>, <span pulumi-lang-nodejs="`github`" pulumi-lang-dotnet="`Github`" pulumi-lang-go="`github`" pulumi-lang-python="`github`" pulumi-lang-yaml="`github`" pulumi-lang-java="`github`" pulumi-lang-hcl="`github`">`github`</span>, and <span pulumi-lang-nodejs="`oidc`" pulumi-lang-dotnet="`Oidc`" pulumi-lang-go="`oidc`" pulumi-lang-python="`oidc`" pulumi-lang-yaml="`oidc`" pulumi-lang-java="`oidc`" pulumi-lang-hcl="`oidc`">`oidc`</span>.
     */
    loginType?: pulumi.Input<string | undefined>;
    /**
     * Display name of the user. Defaults to username.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Password for the user. Required when <span pulumi-lang-nodejs="`loginType`" pulumi-lang-dotnet="`LoginType`" pulumi-lang-go="`loginType`" pulumi-lang-python="`login_type`" pulumi-lang-yaml="`loginType`" pulumi-lang-java="`loginType`" pulumi-lang-hcl="`login_type`">`loginType`</span> is <span pulumi-lang-nodejs="`password`" pulumi-lang-dotnet="`Password`" pulumi-lang-go="`password`" pulumi-lang-python="`password`" pulumi-lang-yaml="`password`" pulumi-lang-java="`password`" pulumi-lang-hcl="`password`">`password`</span>. Passwords are saved into the state as plain text and should only be used for testing purposes.
     */
    password?: pulumi.Input<string | undefined>;
    /**
     * Roles assigned to the user. Valid roles are <span pulumi-lang-nodejs="`owner`" pulumi-lang-dotnet="`Owner`" pulumi-lang-go="`owner`" pulumi-lang-python="`owner`" pulumi-lang-yaml="`owner`" pulumi-lang-java="`owner`" pulumi-lang-hcl="`owner`">`owner`</span>, `template-admin`, `user-admin`, and <span pulumi-lang-nodejs="`auditor`" pulumi-lang-dotnet="`Auditor`" pulumi-lang-go="`auditor`" pulumi-lang-python="`auditor`" pulumi-lang-yaml="`auditor`" pulumi-lang-java="`auditor`" pulumi-lang-hcl="`auditor`">`auditor`</span>. If <span pulumi-lang-nodejs="`null`" pulumi-lang-dotnet="`Null`" pulumi-lang-go="`null`" pulumi-lang-python="`null`" pulumi-lang-yaml="`null`" pulumi-lang-java="`null`" pulumi-lang-hcl="`null`">`null`</span>, roles will not be managed by Terraform. This attribute must be null if the user is an OIDC user and role sync is configured
     */
    roles?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Whether the user is suspended.
     */
    suspended?: pulumi.Input<boolean | undefined>;
    /**
     * Username of the user.
     */
    username: pulumi.Input<string>;
}
