// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class WorkspaceProxy extends pulumi.CustomResource {
    /**
     * Get an existing WorkspaceProxy resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: WorkspaceProxyState, opts?: pulumi.CustomResourceOptions): WorkspaceProxy {
        return new WorkspaceProxy(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'coderd:index/workspaceProxy:WorkspaceProxy';

    /**
     * Returns true if the given object is an instance of WorkspaceProxy.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is WorkspaceProxy {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === WorkspaceProxy.__pulumiType;
    }

    /**
     * Display name of the workspace proxy.
     */
    declare public readonly displayName: pulumi.Output<string>;
    /**
     * Relative path or external URL that specifies an icon to be displayed in the dashboard.
     */
    declare public readonly icon: pulumi.Output<string>;
    /**
     * Name of the workspace proxy.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Session token for the workspace proxy.
     */
    declare public /*out*/ readonly sessionToken: pulumi.Output<string>;

    /**
     * Create a WorkspaceProxy resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: WorkspaceProxyArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: WorkspaceProxyArgs | WorkspaceProxyState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as WorkspaceProxyState | undefined;
            resourceInputs["displayName"] = state?.displayName;
            resourceInputs["icon"] = state?.icon;
            resourceInputs["name"] = state?.name;
            resourceInputs["sessionToken"] = state?.sessionToken;
        } else {
            const args = argsOrState as WorkspaceProxyArgs | undefined;
            if (args?.icon === undefined && !opts.urn) {
                throw new Error("Missing required property 'icon'");
            }
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["icon"] = args?.icon;
            resourceInputs["name"] = args?.name;
            resourceInputs["sessionToken"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["sessionToken"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(WorkspaceProxy.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering WorkspaceProxy resources.
 */
export interface WorkspaceProxyState {
    /**
     * Display name of the workspace proxy.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Relative path or external URL that specifies an icon to be displayed in the dashboard.
     */
    icon?: pulumi.Input<string | undefined>;
    /**
     * Name of the workspace proxy.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Session token for the workspace proxy.
     */
    sessionToken?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a WorkspaceProxy resource.
 */
export interface WorkspaceProxyArgs {
    /**
     * Display name of the workspace proxy.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Relative path or external URL that specifies an icon to be displayed in the dashboard.
     */
    icon: pulumi.Input<string>;
    /**
     * Name of the workspace proxy.
     */
    name?: pulumi.Input<string | undefined>;
}
