# check=skip=InvalidDefaultArgInFrom

ARG USER_NAME

FROM mcr.microsoft.com/devcontainers/base:dev-noble

USER root

RUN set -eux; \
    sed -i 's/kr.archive.ubuntu.com/mirror.kakao.com/g' /etc/apt/sources.list; \
    sed -i 's|http://archive.ubuntu.com|http://mirror.kakao.com|g' /etc/apt/sources.list.d/ubuntu.sources; \
    sed -i 's|http://security.ubuntu.com|http://mirror.kakao.com|g' /etc/apt/sources.list.d/ubuntu.sources;

USER ${USER_NAME}